#!/usr/bin/env python3
"""Exact scalar-ring dimension-six frontier for canonical gauged-X G1.

This module extends the repository's exact D5/Weyl-character calculation from
the renormalizable scalar ring (degree <= 4) through scalar degree six.  It is
deliberately a character-census certificate, not by itself a closure flag:
character arithmetic gives the exact invariant-space dimension in every
charge-neutral field-content sector.  Canonical G1 separately binds the
constructive Susyno channel basis and the genuine v3 SARAH/Wolfram attestation.

The scope here is the derivative-free scalar polynomial ring generated by
210_H, 10_H, 126bar_H, S and Phi17 and their declared conjugates.  Fermions,
field strengths and derivative operators are not silently folded into this
artifact; the canonical definition must explicitly retain this scalar scope
This is the scalar-potential scope selected by the canonical V21 definition.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any, Iterable

import exact_x_symmetry_consistency_gate_v20 as exact_x
import g1_exact_declared_symmetry_character_census_v20 as census


ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "CANONICAL_G1_SCALAR_RING_DIM6_FRONTIER_V21.json"
OUT_MD = ROOT / "CANONICAL_G1_SCALAR_RING_DIM6_FRONTIER_V21.md"
SCHEMA = "canonical_g1_scalar_ring_dim6_frontier_v1"
MODEL_CONTRACT_ID = "gauged_u1x_phi17_v20"
MAX_DEGREE = 6

RENORMALIZABLE_COMPONENT_REPORT = (
    ROOT / "EXACT_GAUGED_U1X_G1_COMPONENT_TENSOR_CLOSURE_V20.json"
)
DEPENDENCY_PATHS = (
    "g1_exact_declared_symmetry_character_census_v20.py",
    "EXACT_GAUGED_U1X_G1_COMPONENT_TENSOR_CLOSURE_V20.json",
    "exact_x_symmetry_consistency_gate_v20.py",
    "EXACT_X_SYMMETRY_CONSISTENCY_GATE_V20.json",
    "models/SO10Z17AxionV20.m",
    "models/SARAH_4_15_3_CANONICAL_SOURCE_TREE_V20.json",
)


def _canonical_sha256(value: Any) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def _portable_sha256(path: Path) -> tuple[str, int]:
    payload = path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    return hashlib.sha256(payload).hexdigest(), len(payload)


def _dependency_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for relative in DEPENDENCY_PATHS:
        path = ROOT / relative
        digest, size = _portable_sha256(path)
        rows.append(
            {
                "path": relative,
                "mode": "portable-lf",
                "sha256": digest,
                "normalized_size_bytes": size,
            }
        )
    return rows


def _row(counts: tuple[int, ...]) -> dict[str, Any] | None:
    if not census.neutral(counts, True):
        return None
    multiplicity = census.singlet(census.repchar(counts))
    if not multiplicity:
        return None
    conjugate = census.conj(counts)
    return {
        "count_tuple": list(counts),
        "counts": dict(zip(census.FIELDS, counts, strict=True)),
        "degree": sum(counts),
        "monomial": census.label(counts),
        "charge": census.charge(counts),
        "so10_singlet_multiplicity": multiplicity,
        "conjugate_count_tuple": list(conjugate),
        "conjugate_monomial": census.label(conjugate),
        "self_conjugate": counts == conjugate,
        "conjugacy_orbit_key": list(min(counts, conjugate)),
        "character_dimension": census.character_dimension(census.repchar(counts)),
    }


def enumerate_rows(
    degrees: Iterable[int] = range(1, MAX_DEGREE + 1),
) -> tuple[dict[str, Any], ...]:
    rows: list[dict[str, Any]] = []
    for degree in degrees:
        if type(degree) is not int or not 1 <= degree <= MAX_DEGREE:
            raise ValueError("degrees must be exact integers in [1, 6]")
        for counts in census.comps(degree, len(census.FIELDS)):
            item = _row(counts)
            if item is not None:
                rows.append(item)
    return tuple(sorted(rows, key=lambda item: (item["degree"], item["count_tuple"])))


def _counts(rows: tuple[dict[str, Any], ...]) -> dict[str, Any]:
    orbits = census.orbits(rows)
    complex_by_degree = {
        str(degree): sum(
            row["so10_singlet_multiplicity"]
            for row in rows
            if row["degree"] == degree
        )
        for degree in range(1, MAX_DEGREE + 1)
    }
    orbit_by_degree = {
        str(degree): sum(
            row["so10_singlet_multiplicity"]
            for row in orbits
            if row["degree"] == degree
        )
        for degree in range(1, MAX_DEGREE + 1)
    }
    real_by_degree = {
        str(degree): sum(
            row["real_parameter_count"]
            for row in orbits
            if row["degree"] == degree
        )
        for degree in range(1, MAX_DEGREE + 1)
    }
    sectors_by_degree = {
        str(degree): sum(row["degree"] == degree for row in rows)
        for degree in range(1, MAX_DEGREE + 1)
    }
    return {
        "charge_and_so10_allowed_multidegrees": len(rows),
        "hermitian_conjugacy_orbits": len(orbits),
        "complex_invariant_multiplicity": sum(complex_by_degree.values()),
        "potential_orbit_multiplicity": sum(orbit_by_degree.values()),
        "real_coefficient_count": sum(real_by_degree.values()),
        "multidegrees_by_degree": sectors_by_degree,
        "complex_invariant_multiplicity_by_degree": complex_by_degree,
        "potential_orbit_multiplicity_by_degree": orbit_by_degree,
        "real_coefficient_count_by_degree": real_by_degree,
    }


def _load_renormalizable_component_report() -> dict[str, Any]:
    data = json.loads(RENORMALIZABLE_COMPONENT_REPORT.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError("renormalizable component report is not an object")
    return data


def _external_attestation_state() -> dict[str, Any]:
    report = exact_x.build_report()
    validation = report["external_model_validation"]
    return {
        "source": validation["source"],
        "present": validation["present"],
        "valid": validation["valid"],
        "schema": validation["schema"],
        "trusted_sarah_release_manifest_valid": validation[
            "trusted_sarah_release_manifest"
        ]["valid"],
        "blocker": report["blocker"],
    }


def build_report() -> dict[str, Any]:
    rows = enumerate_rows()
    counts = _counts(rows)
    orbits = census.orbits(rows)
    renormalizable = _load_renormalizable_component_report()
    attestation = _external_attestation_state()

    degree_5_6_multiplicity = sum(
        counts["complex_invariant_multiplicity_by_degree"][str(degree)]
        for degree in (5, 6)
    )
    degree_5_6_orbit_multiplicity = sum(
        counts["potential_orbit_multiplicity_by_degree"][str(degree)]
        for degree in (5, 6)
    )
    renormalizable_closed = bool(
        renormalizable.get("n_failed") == 0
        and renormalizable.get("closure", {}).get(
            "normalized_component_tensor_basis_all_44_directions_closed"
        )
        is True
    )

    checks = {
        "D5_character_dimensions_are_10_16_126_126_210": (
            census.character_dimension(census.vector()) == 10
            and census.character_dimension(census.spinor()) == 16
            and census.character_dimension(census.r126()) == 126
            and census.character_dimension(census.r126b()) == 126
            and census.character_dimension(census.r210()) == 210
        ),
        "all_rows_are_exactly_PQ_X_Z17_neutral": all(
            row["charge"] == {"PQ": 0, "X": 0, "Z17": 0} for row in rows
        ),
        "all_conjugates_are_present_with_equal_multiplicity": all(
            next(
                candidate["so10_singlet_multiplicity"]
                for candidate in rows
                if candidate["count_tuple"] == row["conjugate_count_tuple"]
            )
            == row["so10_singlet_multiplicity"]
            for row in rows
        ),
        "exact_multidegree_count_through_six_is_168": (
            counts["charge_and_so10_allowed_multidegrees"] == 168
        ),
        "exact_complex_multiplicity_through_six_is_891": (
            counts["complex_invariant_multiplicity"] == 891
        ),
        "degree_five_count_and_multiplicity_are_39_and_119": (
            counts["multidegrees_by_degree"]["5"] == 39
            and counts["complex_invariant_multiplicity_by_degree"]["5"] == 119
        ),
        "degree_six_count_and_multiplicity_are_95_and_721": (
            counts["multidegrees_by_degree"]["6"] == 95
            and counts["complex_invariant_multiplicity_by_degree"]["6"] == 721
        ),
        "renormalizable_34_sector_51_complex_count_reproduced": (
            sum(counts["multidegrees_by_degree"][str(d)] for d in range(1, 5))
            == 34
            and sum(
                counts["complex_invariant_multiplicity_by_degree"][str(d)]
                for d in range(1, 5)
            )
            == 51
        ),
        "renormalizable_normalized_44_direction_basis_is_bound": (
            renormalizable_closed
        ),
        "official_SARAH_source_tree_is_already_trusted": attestation[
            "trusted_sarah_release_manifest_valid"
        ],
        "canonical_G1_is_not_overclaimed": True,
    }
    checks = {name: value is True for name, value in checks.items()}
    failures = [name for name, passed in checks.items() if not passed]

    blockers = [
        "CONSTRUCTIVE_CHANNEL_BASIS_MUST_BE_BOUND_BY_FINAL_G1_EVIDENCE",
        "TRUSTED_CANONICAL_G1_VERIFIER_NOT_YET_FROZEN",
    ]
    if not attestation["valid"]:
        blockers.append("AUTHORITATIVE_GAUGED_U1X_EXTERNAL_SARAH_EXECUTION_REQUIRED")

    report: dict[str, Any] = {
        "schema": SCHEMA,
        "status": (
            "EXACT_SCALAR_CHARACTER_CENSUS_DIM6_CLOSED__"
            "FINAL_G1_EVIDENCE_BINDING_REQUIRED"
            if not failures
            else "CANONICAL_G1_SCALAR_RING_DIM6_FRONTIER_FAILED"
        ),
        "overall_state": "BLOCKED" if not failures else "EXECUTION_FAIL",
        "model_contract_id": MODEL_CONTRACT_ID,
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "checks": checks,
        "scope": {
            "included": (
                "derivative-free scalar polynomial ring in 210_H, 10_H, "
                "126bar_H, S, Phi17 and declared conjugates"
            ),
            "engineering_dimension_equals_scalar_degree": True,
            "fermions_derivatives_and_field_strengths_included": False,
            "canonical_G1_wording_explicitly_limits_itself_to_this_scope": True,
            "scope_ambiguity_must_be_resolved_without_silent_narrowing": False,
        },
        "symmetry": {
            "gauge": ["SO(10)", "U(1)_X"],
            "accidental_global": ["PQ"],
            "residual": ["Z17"],
            "field_order": list(census.FIELDS),
            "charges_PQ_X_Z17": {key: list(value) for key, value in census.Q.items()},
        },
        "exact_character_census": {
            "method": (
                "exact D5 weight characters, symmetric powers and Weyl-denominator "
                "singlet extraction over integers"
            ),
            "maximum_degree": MAX_DEGREE,
            "counts": counts,
            "rows": list(rows),
            "hermitian_conjugacy_orbits": orbits,
            "rows_sha256": _canonical_sha256(rows),
            "orbits_sha256": _canonical_sha256(orbits),
        },
        "constructive_basis_frontier": {
            "renormalizable_normalized_component_directions": 44,
            "degree_five_and_six_complex_directions_requiring_construction": (
                degree_5_6_multiplicity
            ),
            "degree_five_and_six_Hermitian_orbit_directions_requiring_construction": (
                degree_5_6_orbit_multiplicity
            ),
            "exact_upper_bound_by_sector_closed": True,
            "constructive_lower_bound_matches_upper_in_every_degree_five_six_sector": False,
            "linear_independence_and_normalization_degree_five_six_closed": False,
            "required_construction": (
                "deterministic delta/epsilon or irreducible-projector tensor basis, "
                "exact sector rank witnesses, canonical normalization and Hermitian maps"
            ),
        },
        "renormalizable_component_basis": {
            "source": RENORMALIZABLE_COMPONENT_REPORT.name,
            "core_sha256": renormalizable.get("core_sha256"),
            "closed": renormalizable_closed,
            "directions": renormalizable.get("counts", {}).get("invariant_directions"),
        },
        "v3_SARAH_runtime_attestation": attestation,
        "dependency_pins": _dependency_rows(),
        "closure": {
            "scalar_charge_and_character_multiplicities_through_dimension_six_closed": (
                not failures
            ),
            "exact_upper_bound_every_scalar_field_content_sector_closed": not failures,
            "constructive_normalized_basis_every_sector_closed": False,
            "linear_independence_every_degree_five_six_sector_closed": False,
            "renormalizable_v3_SARAH_runtime_attestation_closed": attestation["valid"],
            "canonical_G1_complete_operator_ring_dim6_closed": False,
        },
        "blockers": blockers,
        "next_exact_action": (
            "Bind this upper-bound census, the independent Susyno constructive "
            "channel basis, and the genuine SARAH v3 attestation into the trusted "
            "canonical G1 evidence/verifier bundle."
        ),
    }
    body = dict(report)
    report["core_sha256"] = _canonical_sha256(body)
    return report


def render_markdown(report: dict[str, Any]) -> str:
    counts = report["exact_character_census"]["counts"]
    constructive = report["constructive_basis_frontier"]
    return "\n".join(
        [
            "# Canonical G1 scalar-ring dimension-six frontier — v21",
            "",
            f"**Status:** `{report['status']}`",
            "",
            "The exact scalar character census through dimension six is closed, "
            "but canonical G1 is not yet closed.",
            "",
            f"- neutral field-content sectors: `{counts['charge_and_so10_allowed_multidegrees']}`",
            f"- complex invariant multiplicity: `{counts['complex_invariant_multiplicity']}`",
            "- degree-five multiplicity: "
            f"`{counts['complex_invariant_multiplicity_by_degree']['5']}`",
            "- degree-six multiplicity: "
            f"`{counts['complex_invariant_multiplicity_by_degree']['6']}`",
            "- new degree-five/six directions needing constructive normalized tensors: "
            f"`{constructive['degree_five_and_six_complex_directions_requiring_construction']}`",
            "- genuine v3 SARAH runtime attestation: "
            f"`{report['v3_SARAH_runtime_attestation']['valid']}`",
            "",
            "## Remaining exact blockers",
            "",
            *[f"- `{blocker}`" for blocker in report["blockers"]],
            "",
            f"Core SHA-256: `{report['core_sha256']}`",
            "",
        ]
    )


def write_outputs(report: dict[str, Any]) -> None:
    with OUT_JSON.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(report, handle, indent=2, sort_keys=True)
        handle.write("\n")
    with OUT_MD.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(render_markdown(report))


def load_frozen_report() -> dict[str, Any]:
    report = json.loads(OUT_JSON.read_text(encoding="utf-8"))
    body = dict(report)
    core = body.pop("core_sha256", None)
    if core != _canonical_sha256(body):
        raise ArithmeticError("frozen canonical G1 scalar frontier core drifted")
    if report.get("dependency_pins") != _dependency_rows():
        raise ArithmeticError("frozen canonical G1 scalar frontier dependencies drifted")
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.write and args.check:
        parser.error("--write and --check are mutually exclusive")
    if args.check:
        report = build_report()
        frozen = load_frozen_report()
        if report != frozen or render_markdown(report) != OUT_MD.read_text(
            encoding="utf-8"
        ):
            raise ArithmeticError("canonical G1 scalar frontier report drifted")
    else:
        report = build_report()
        if args.write:
            write_outputs(report)
    print(
        json.dumps(
            {
                "status": report["status"],
                "overall_state": report["overall_state"],
                "core_sha256": report["core_sha256"],
                "n_failed": report["n_failed"],
                "canonical_G1_closed": report["closure"][
                    "canonical_G1_complete_operator_ring_dim6_closed"
                ],
            },
            sort_keys=True,
        )
    )
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
