#!/usr/bin/env python3
"""Canonical, closure-capable G1--G8 contract for gauged-U(1)_X v21.

The repository historically used the labels ``G1``--``G8`` for two different
dependency graphs.  A renormalizable scalar-audit ledger called G4 a quotient
Hessian and G5 boundedness, while an older phenomenology contract called G4
the electroweak hierarchy and G5 the cal-G/axion phase check.  Bare gate
numbers are therefore not proof identifiers.

This module freezes one qualified phenomenology namespace.  Every gate has a
unique ID, definition hash, dedicated artifact, exact dependency list and
machine-checkable acceptance evidence.  It is deliberately closure-capable:
valid future artifacts can move every gate to CLOSED.  Missing or malformed
evidence fails closed; historical scalar-ledger results remain useful scoped
evidence but cannot substitute for a canonical gate.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
from typing import Any


ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "CANONICAL_G1_G8_GAUGED_U1X_V21.json"
OUT_MD = ROOT / "CANONICAL_G1_G8_GAUGED_U1X_V21.md"

SCHEMA = "canonical_g1_g8_gauged_u1x_v21"
EVIDENCE_SCHEMA = "canonical_gauged_u1x_gate_evidence_v1"
VERIFIER_SCHEMA = "canonical_gauged_u1x_gate_verification_v1"
CONTRACT_NAMESPACE = "canonical.gauged_u1x.phenomenology.v21"
MODEL_CONTRACT_ID = "gauged_u1x_phi17_v20"

SO10_GENERATOR_DIMENSION = 45
U1X_GENERATOR_DIMENSION = 1
SU3C_STABILIZER_DIMENSION = 8
U1EM_STABILIZER_DIMENSION = 1
EXPECTED_BROKEN_GAUGE_DIRECTIONS = (
    SO10_GENERATOR_DIMENSION
    + U1X_GENERATOR_DIMENSION
    - SU3C_STABILIZER_DIMENSION
    - U1EM_STABILIZER_DIMENSION
)


def _gate(
    number: int,
    slug: str,
    title: str,
    artifact: str,
    dependencies: list[str],
    acceptance: list[str],
    verifier_sha256: str | None = None,
) -> dict[str, Any]:
    return {
        "gate_number": number,
        "qualified_gate_id": f"{CONTRACT_NAMESPACE}.G{number}.{slug}",
        "title": title,
        "required_artifact": artifact,
        "dependencies": dependencies,
        "acceptance": acceptance,
        "trusted_verifier": {
            "path": f"verify_canonical_g{number}_{slug}_v21.py",
            "mode": "raw",
            "protocol": VERIFIER_SCHEMA,
            # A gate cannot close until a reviewed verifier is landed and its
            # source hash is frozen into this definition.
            "sha256": verifier_sha256,
        },
    }


G1_ID = f"{CONTRACT_NAMESPACE}.G1.complete_operator_ring_dim6"
G2_ID = f"{CONTRACT_NAMESPACE}.G2.full_component_projection_dim6"
G3_ID = f"{CONTRACT_NAMESPACE}.G3.physical_ew_global_vacuum"
G4_ID = f"{CONTRACT_NAMESPACE}.G4.protected_ew_hierarchy"
G5_ID = f"{CONTRACT_NAMESPACE}.G5.calg_axion_phase_revalidation"
G6_ID = f"{CONTRACT_NAMESPACE}.G6.full_nonsusy_two_loop_chain"
G7_ID = f"{CONTRACT_NAMESPACE}.G7.physical_pole_threshold_spectrum"
G8_ID = f"{CONTRACT_NAMESPACE}.G8.unique_proton_lifetime_distribution"

GATES: tuple[dict[str, Any], ...] = (
    _gate(
        1,
        "complete_operator_ring_dim6",
        "Complete gauged-X derivative-free scalar potential ring through engineering dimension six",
        "CANONICAL_G1_COMPLETE_OPERATOR_RING_DIM6_V21.json",
        [],
        [
            "all derivative-free SO(10)xU(1)_XxZ17/PQ-neutral scalar polynomial potential operators generated by 210_H, 10_H, 126bar_H, S, Phi17 and their Hermitian conjugates through engineering dimension six are enumerated",
            "exact upper and constructive lower bounds agree in every field-content sector",
            "linear independence, normalization and Hermitian-conjugation conventions are exact",
            "the renormalizable 44-direction component basis is exact, and the model representation/charge convention plus registered scalar audit Lagrangian are bound to a genuine v3 SARAH source-tree/runtime/process-log attestation",
        ],
        "26f5dfe44355923b25e264871765b82b779c9bccaa86630b18254fd8a690f2d1",
    ),
    _gate(
        2,
        "full_component_projection_dim6",
        "Full component projection of every canonical operator",
        "CANONICAL_G2_FULL_COMPONENT_PROJECTION_DIM6_V21.json",
        [G1_ID],
        [
            "every independent invariant is projected to normalized PS and SM components",
            "canonical kinetic normalization and representation ancestry are verified exactly",
            "lambda4 and every retained dimension-six lock coefficient are explicit",
            "component reconstruction reproduces every canonical invariant before symmetry breaking",
        ],
        "a13ceb61871da641fce3ca1146c9bb91d1045418686712e3373a56e4233370e7",
    ),
    _gate(
        3,
        "physical_ew_global_vacuum",
        "Physical-EW global vacuum and complete component Hessian",
        "CANONICAL_G3_PHYSICAL_EW_GLOBAL_VACUUM_V21.json",
        [G2_ID],
        [
            "the physical-EW vacuum is source-exact stationary for the complete accepted potential",
            f"the gauge quotient contains exactly {EXPECTED_BROKEN_GAUGE_DIRECTIONS} broken gauge directions derived as 45+1-8-1",
            "all non-symmetry component Hessian modes are strictly positive with the intended axion direction identified",
            "boundedness and global equality-orbit classification exclude every deeper or disconnected competing extremum",
        ],
        "49bff6ba5b89f321565a30a762fd5559adfcbca1ee157943082acf770b9d461b",
    ),
    _gate(
        4,
        "protected_ew_hierarchy",
        "Technically protected h=174 GeV electroweak hierarchy",
        "CANONICAL_G4_PROTECTED_EW_HIERARCHY_V21.json",
        [G2_ID, G3_ID],
        [
            "h=174 GeV is obtained on the same physical-EW vacuum without an excluded historical lambda4 point",
            "all required dimensionless couplings remain perturbative over the declared running interval",
            "radiative stability or a source-bound symmetry protection mechanism is demonstrated",
            "the hierarchy mechanism introduces no tachyon or deeper unwanted vacuum",
        ],
    ),
    _gate(
        5,
        "calg_axion_phase_revalidation",
        "cal-G lock and axion-phase revalidation on the physical branch",
        "CANONICAL_G5_CALG_AXION_PHASE_REVALIDATION_V21.json",
        [G3_ID, G4_ID],
        [
            "the cal-G mode is lifted above a declared source-bound tolerance",
            "the axion is the only intended light phase direction",
            "the selected physical-EW vacuum and complete scalar spectrum remain positive",
            "the result uses live lambda-lock component tensors from the canonical G2 projection",
        ],
    ),
    _gate(
        6,
        "full_nonsusy_two_loop_chain",
        "Complete non-supersymmetric two-loop RGE and matching chain",
        "CANONICAL_G6_FULL_NONSUSY_TWO_LOOP_CHAIN_V21.json",
        [G2_ID, G3_ID, G4_ID, G5_ID],
        [
            "complete tensor-valued gauge, Yukawa, scalar and dimensionful beta functions are included",
            "SO10-to-PS, PS-to-pre-EW and pre-EW-to-SM matching use physical component pole inputs",
            "renormalization, tadpole/VEV, threshold and normalization schemes are declared",
            "an independent complete implementation reproduces symbolic limits and at least 100 nonsingular numerical points",
        ],
    ),
    _gate(
        7,
        "physical_pole_threshold_spectrum",
        "Complete physical pole spectrum and threshold inventory",
        "CANONICAL_G7_PHYSICAL_POLE_THRESHOLD_SPECTRUM_V21.json",
        [G2_ID, G3_ID, G4_ID, G5_ID],
        [
            "source-exact scalar, vector and fermion mass/mixing matrices are complete at every breaking stage",
            "eaten directions and forbidden operators are removed while allowed lambda4 triplet mixing is explicit",
            "self-energy pole equations yield positive physical masses in a declared tadpole/VEV scheme",
            "all finite scalar, fermion and vector thresholds have complete SM quantum numbers and multiplicities",
        ],
    ),
    _gate(
        8,
        "unique_proton_lifetime_distribution",
        "Unique proton lifetime or propagated prediction distribution",
        "CANONICAL_G8_UNIQUE_PROTON_LIFETIME_V21.json",
        [G5_ID, G6_ID, G7_ID],
        [
            "all gauge and scalar mediators are included with physical pole masses",
            "mass-basis Wilson coefficients are matched and run in a declared scheme",
            "the flavour/Clebsch solution is unique or its fitted covariance distribution is propagated",
            "gauge-scalar interference phases are fixed by the same physical vacuum and flavour solution",
            "every reported channel is compared with a versioned experimental-limit and lattice-input ledger",
        ],
    ),
)


LEGACY_NAMESPACES = {
    "RENORMALIZABLE_SCALAR_CHAIN_V20": {
        "definition_sha256": "1b96316304b80a995a0d39b581d3d6d942599b0efaa69035562ff6f72c4f0e62",
        "scope": "degree<=4 scalar ring/potential, vacuum, quotient, BFB, spectrum and RGE audit",
        "can_satisfy_canonical_gate_by_number": False,
    },
    "IRREDUCIBLE_GAP_CONTRACT_V20_LEGACY": {
        "definition_sha256": "87e35c776a024d3129d41c232d22343652ef2cb9905128bae38c1ca63007cb80",
        "scope": "historical phenomenology draft with stale 33-Goldstone and soft-beta wording",
        "can_satisfy_canonical_gate_by_number": False,
    },
}
LEGACY_SOURCE_BINDINGS = {
    "RENORMALIZABLE_SCALAR_CHAIN_V20": {
        "path": "g1_g8_gate_ledger_v20.py",
        "binding_mode": "semantic-definition",
        "semantic_projection": "gate_titles_and_dependency_DAG",
        "definition_sha256": LEGACY_NAMESPACES[
            "RENORMALIZABLE_SCALAR_CHAIN_V20"
        ]["definition_sha256"],
    },
    "IRREDUCIBLE_GAP_CONTRACT_V20_LEGACY": {
        "path": "irreducible_gap_closure_contract_v20.py",
        "binding_mode": "raw",
        "raw_sha256": "2121c87b0eadd001156a70ce08dd1b3e26ca205d15c438bf07773c114cf165c0",
    },
}


def _json_bytes(value: Any) -> bytes:
    return (
        json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
        + "\n"
    ).encode("utf-8")


def _sha(value: Any) -> str:
    return hashlib.sha256(_json_bytes(value)).hexdigest()


DEFINITION_PAYLOAD = {
    "schema": SCHEMA,
    "contract_namespace": CONTRACT_NAMESPACE,
    "model_contract_id": MODEL_CONTRACT_ID,
    "gauge_dimension_derivation": {
        "SO10": SO10_GENERATOR_DIMENSION,
        "U1X": U1X_GENERATOR_DIMENSION,
        "SU3C_stabilizer": SU3C_STABILIZER_DIMENSION,
        "U1em_stabilizer": U1EM_STABILIZER_DIMENSION,
        "broken": EXPECTED_BROKEN_GAUGE_DIRECTIONS,
    },
    "gates": GATES,
}
DEFINITION_SHA256 = _sha(DEFINITION_PAYLOAD)


def canonical_gate_id(number: int) -> str:
    if type(number) is not int:
        raise TypeError("canonical gate number must be an exact integer")
    matches = [g["qualified_gate_id"] for g in GATES if g["gate_number"] == number]
    if len(matches) != 1:
        raise KeyError(f"canonical gate number is absent or ambiguous: {number}")
    return matches[0]


def _portable_digest(path: Path) -> tuple[str, int]:
    raw = path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    return hashlib.sha256(raw).hexdigest(), len(raw)


def _raw_digest(path: Path) -> tuple[str, int]:
    raw = path.read_bytes()
    return hashlib.sha256(raw).hexdigest(), len(raw)


def _contains_symlink_component(base: Path, relative: Path) -> bool:
    current = base
    for part in relative.parts:
        current = current / part
        if current.is_symlink() or (
            hasattr(current, "is_junction") and current.is_junction()
        ):
            return True
    return False


def _safe_bound_file(root: Path, item: Any, prefix: str, errors: list[str]) -> None:
    if not isinstance(item, dict):
        errors.append(f"{prefix}_not_object")
        return
    relative = item.get("path")
    expected = item.get("sha256")
    mode = item.get("mode")
    if not isinstance(relative, str) or not relative or Path(relative).is_absolute():
        errors.append(f"{prefix}_path_invalid")
        return
    relative_path = Path(relative)
    if _contains_symlink_component(root, relative_path):
        errors.append(f"{prefix}_symlink_rejected")
        return
    candidate = (root / relative_path).resolve()
    try:
        candidate.relative_to(root.resolve())
    except ValueError:
        errors.append(f"{prefix}_path_escapes_root")
        return
    if not candidate.is_file():
        errors.append(f"{prefix}_file_missing_or_not_regular")
        return
    if mode == "raw":
        observed, _ = _raw_digest(candidate)
    elif mode == "portable-lf":
        observed, _ = _portable_digest(candidate)
    else:
        errors.append(f"{prefix}_mode_invalid")
        return
    if not isinstance(expected, str) or observed != expected:
        errors.append(f"{prefix}_sha256_mismatch")


def _artifact_core(payload: dict[str, Any]) -> str:
    body = dict(payload)
    body.pop("core_sha256", None)
    return _sha(body)


def _run_trusted_gate_verifier(
    gate: dict[str, Any],
    base: Path,
    artifact_path: Path,
    artifact_core: Any,
    errors: list[str],
) -> dict[str, Any] | None:
    """Execute the reviewed, definition-pinned verifier for one gate.

    Evidence JSON is never self-authenticating.  Closure additionally requires
    an executable verifier whose source hash is part of the canonical gate
    definition and whose complete result is validated here.  Empty verifier
    hashes are intentional fail-closed placeholders for unfinished gates.
    """
    descriptor = gate.get("trusted_verifier")
    if not isinstance(descriptor, dict) or set(descriptor) != {
        "path",
        "mode",
        "protocol",
        "sha256",
    }:
        errors.append("trusted_verifier_descriptor_invalid")
        return None
    relative = descriptor.get("path")
    expected_sha = descriptor.get("sha256")
    if (
        descriptor.get("mode") != "raw"
        or descriptor.get("protocol") != VERIFIER_SCHEMA
        or not isinstance(relative, str)
        or not relative
        or Path(relative).is_absolute()
    ):
        errors.append("trusted_verifier_descriptor_invalid")
        return None
    if (
        not isinstance(expected_sha, str)
        or len(expected_sha) != 64
        or any(character not in "0123456789abcdef" for character in expected_sha)
    ):
        errors.append("trusted_verifier_not_frozen")
        return None
    relative_path = Path(relative)
    if _contains_symlink_component(base, relative_path):
        errors.append("trusted_verifier_symlink_rejected")
        return None
    verifier_path = (base / relative_path).resolve()
    try:
        verifier_path.relative_to(base.resolve())
    except ValueError:
        errors.append("trusted_verifier_path_escapes_root")
        return None
    if not verifier_path.is_file():
        errors.append("trusted_verifier_missing_or_not_regular")
        return None
    observed_sha = hashlib.sha256(verifier_path.read_bytes()).hexdigest()
    if observed_sha != expected_sha:
        errors.append("trusted_verifier_sha256_mismatch")
        return None
    environment = os.environ.copy()
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    artifact_raw_before = hashlib.sha256(artifact_path.read_bytes()).hexdigest()
    try:
        completed = subprocess.run(
            [
                sys.executable,
                "-I",
                "-B",
                str(verifier_path),
                "--verify-artifact",
                str(artifact_path),
                "--definition-sha256",
                DEFINITION_SHA256,
                "--qualified-gate-id",
                gate["qualified_gate_id"],
                "--gate-definition-sha256",
                _sha(gate),
                "--dependencies-json",
                json.dumps(gate["dependencies"], separators=(",", ":")),
                "--acceptance-count",
                str(len(gate["acceptance"])),
            ],
            cwd=base,
            env=environment,
            check=False,
            capture_output=True,
            text=True,
            timeout=300,
        )
    except (OSError, subprocess.SubprocessError):
        errors.append("trusted_verifier_execution_failed")
        return None
    if completed.returncode != 0:
        errors.append("trusted_verifier_nonzero_exit")
        return None
    if completed.stderr:
        errors.append("trusted_verifier_emitted_stderr")
        return None
    if len(completed.stdout.encode("utf-8")) > 1_000_000:
        errors.append("trusted_verifier_output_too_large")
        return None
    if hashlib.sha256(verifier_path.read_bytes()).hexdigest() != expected_sha:
        errors.append("trusted_verifier_changed_during_execution")
        return None
    if hashlib.sha256(artifact_path.read_bytes()).hexdigest() != artifact_raw_before:
        errors.append("artifact_changed_during_verification")
        return None
    try:
        result = json.loads(completed.stdout)
    except (json.JSONDecodeError, TypeError):
        errors.append("trusted_verifier_output_invalid_json")
        return None
    expected_keys = {
        "schema",
        "contract_namespace",
        "definition_sha256",
        "qualified_gate_id",
        "gate_definition_sha256",
        "dependencies",
        "artifact_core_sha256",
        "verifier_sha256",
        "acceptance_results",
        "all_acceptance_criteria_verified",
        "n_failed",
        "failures",
        "verification_core_sha256",
    }
    acceptance_keys = [f"A{index}" for index in range(1, len(gate["acceptance"]) + 1)]
    if not isinstance(result, dict) or set(result) != expected_keys:
        errors.append("trusted_verifier_output_schema_mismatch")
        return result if isinstance(result, dict) else None
    body = dict(result)
    reported_core = body.pop("verification_core_sha256", None)
    exact = bool(
        result.get("schema") == VERIFIER_SCHEMA
        and result.get("contract_namespace") == CONTRACT_NAMESPACE
        and result.get("definition_sha256") == DEFINITION_SHA256
        and result.get("qualified_gate_id") == gate["qualified_gate_id"]
        and result.get("gate_definition_sha256") == _sha(gate)
        and result.get("dependencies") == gate["dependencies"]
        and result.get("artifact_core_sha256") == artifact_core
        and result.get("verifier_sha256") == expected_sha
        and isinstance(result.get("acceptance_results"), dict)
        and list(result["acceptance_results"]) == acceptance_keys
        and all(
            result["acceptance_results"].get(key) is True
            for key in acceptance_keys
        )
        and result.get("all_acceptance_criteria_verified") is True
        and type(result.get("n_failed")) is int
        and result.get("n_failed") == 0
        and result.get("failures") == []
        and reported_core == _sha(body)
    )
    if not exact:
        errors.append("trusted_verifier_result_not_exact")
    return result


def _legacy_scalar_definition_sha256(path: Path) -> str | None:
    """Hash only the legacy gate titles and DAG, avoiding a source-hash cycle.

    The legacy ledger consumes scoped evidence whose own provenance reaches this
    canonical definition.  Raw-hashing that ledger here would create the cycle
    ``canonical -> G8 frontier -> ledger -> canonical``.  Its namespace identity
    is instead the exact, AST-extracted title+DAG projection originally used to
    distinguish the two historical G-number taxonomies.
    """
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
        dependencies: dict[str, list[str]] | None = None
        specifications: dict[str, Any] | None = None
        for node in ast.walk(tree):
            if not isinstance(node, (ast.Assign, ast.AnnAssign)):
                continue
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for target in targets:
                if not isinstance(target, ast.Name):
                    continue
                if target.id == "DEPENDENCIES":
                    dependencies = ast.literal_eval(node.value)
                elif target.id == "specifications":
                    try:
                        specifications = ast.literal_eval(node.value)
                    except (TypeError, ValueError):
                        pass
        gate_ids = [f"G{index}" for index in range(1, 9)]
        if dependencies is None or specifications is None:
            return None
        projection = {
            gate_id: {
                "title": specifications[gate_id][0],
                "dependencies": dependencies[gate_id],
            }
            for gate_id in gate_ids
        }
        return _sha(projection)
    except (OSError, SyntaxError, KeyError, TypeError, ValueError):
        return None


def _legacy_binding_valid(name: str, row: dict[str, Any]) -> bool:
    path = ROOT / row.get("path", "")
    if not path.is_file():
        return False
    if row.get("binding_mode") == "raw":
        return hashlib.sha256(path.read_bytes()).hexdigest() == row.get("raw_sha256")
    if (
        name == "RENORMALIZABLE_SCALAR_CHAIN_V20"
        and row.get("binding_mode") == "semantic-definition"
        and row.get("semantic_projection") == "gate_titles_and_dependency_DAG"
    ):
        return _legacy_scalar_definition_sha256(path) == row.get(
            "definition_sha256"
        )
    return False


def validate_gate_artifact(
    gate: dict[str, Any], root: Path | str | None = None
) -> dict[str, Any]:
    base = Path(root).resolve() if root is not None else ROOT
    relative_artifact = Path(gate["required_artifact"])
    if (
        relative_artifact.is_absolute()
        or _contains_symlink_component(base, relative_artifact)
    ):
        return {
            "exists": True,
            "valid": False,
            "closed": False,
            "reason": "canonical artifact path is unsafe",
            "errors": ["artifact_path_unsafe_or_symlink"],
        }
    path = (base / relative_artifact).resolve()
    try:
        path.relative_to(base)
    except ValueError:
        return {
            "exists": True,
            "valid": False,
            "closed": False,
            "reason": "canonical artifact path escapes root",
            "errors": ["artifact_path_escapes_root"],
        }
    if not path.is_file():
        return {
            "exists": False,
            "valid": False,
            "closed": False,
            "reason": "required canonical artifact absent",
            "errors": [],
        }
    errors: list[str] = []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return {
            "exists": True,
            "valid": False,
            "closed": False,
            "reason": f"invalid JSON: {exc}",
            "errors": ["invalid_json"],
        }
    if not isinstance(payload, dict):
        errors.append("payload_not_object")
        payload = {}
    exact_scalars = {
        "schema": EVIDENCE_SCHEMA,
        "contract_namespace": CONTRACT_NAMESPACE,
        "definition_sha256": DEFINITION_SHA256,
        "model_contract_id": MODEL_CONTRACT_ID,
        "qualified_gate_id": gate["qualified_gate_id"],
    }
    for key, expected in exact_scalars.items():
        if payload.get(key) != expected:
            errors.append(f"{key}_mismatch")
    if payload.get("dependencies") != gate["dependencies"]:
        errors.append("dependency_manifest_mismatch")
    if payload.get("closure_complete") is not True:
        errors.append("closure_complete_not_true")
    if type(payload.get("n_failed")) is not int or payload.get("n_failed") != 0:
        errors.append("n_failed_nonzero_or_invalid")
    if not isinstance(payload.get("producer"), str) or not payload.get("producer", "").strip():
        errors.append("producer_missing")
    if not isinstance(payload.get("normalization_conventions"), dict) or not payload.get("normalization_conventions"):
        errors.append("normalization_conventions_missing")
    source_manifest = payload.get("source_manifest")
    if not isinstance(source_manifest, list) or not source_manifest:
        errors.append("source_manifest_missing")
    else:
        for index, item in enumerate(source_manifest):
            _safe_bound_file(base, item, f"source_manifest_{index}", errors)
    evidence = payload.get("acceptance_evidence")
    expected_keys = [f"A{i}" for i in range(1, len(gate["acceptance"]) + 1)]
    if not isinstance(evidence, dict) or sorted(evidence) != sorted(expected_keys):
        errors.append("acceptance_evidence_keys_mismatch")
    else:
        for index, criterion in enumerate(gate["acceptance"], start=1):
            key = f"A{index}"
            item = evidence[key]
            if not isinstance(item, dict):
                errors.append(f"{key}_not_object")
                continue
            if item.get("criterion") != criterion:
                errors.append(f"{key}_criterion_mismatch")
            if item.get("passed") is not True:
                errors.append(f"{key}_not_passed")
            artifacts = item.get("artifacts")
            if not isinstance(artifacts, list) or not artifacts:
                errors.append(f"{key}_artifacts_missing")
            else:
                for item_index, bound in enumerate(artifacts):
                    _safe_bound_file(
                        base, bound, f"{key}_artifact_{item_index}", errors
                    )
    if payload.get("core_sha256") != _artifact_core(payload):
        errors.append("core_sha256_mismatch")
    verifier_result = _run_trusted_gate_verifier(
        gate,
        base,
        path,
        payload.get("core_sha256"),
        errors,
    )
    # Recheck every evidence dependency after verifier execution to close the
    # read/verify/use window.  Any mutation is compared with the artifact's
    # already parsed frozen hashes and therefore fails closed.
    if isinstance(source_manifest, list):
        for index, item in enumerate(source_manifest):
            _safe_bound_file(base, item, f"post_source_manifest_{index}", errors)
    if isinstance(evidence, dict):
        for key in expected_keys:
            item = evidence.get(key)
            if not isinstance(item, dict) or not isinstance(item.get("artifacts"), list):
                continue
            for item_index, bound in enumerate(item["artifacts"]):
                _safe_bound_file(
                    base, bound, f"post_{key}_artifact_{item_index}", errors
                )
    valid = not errors
    return {
        "exists": True,
        "valid": valid,
        "closed": valid,
        "reason": "accepted" if valid else "canonical artifact validation failed",
        "raw_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "core_sha256": payload.get("core_sha256"),
        "trusted_verifier_result": verifier_result,
        "errors": errors,
    }


def _definition_checks() -> dict[str, bool]:
    ids = [gate["qualified_gate_id"] for gate in GATES]
    positions = {gate_id: index for index, gate_id in enumerate(ids)}
    dependency_ordered = all(
        positions[dependency] < positions[gate["qualified_gate_id"]]
        for gate in GATES
        for dependency in gate["dependencies"]
    )
    g6_text = " ".join(GATES[5]["acceptance"]).lower()
    return {
        "eight_unique_qualified_gate_ids": len(ids) == len(set(ids)) == 8,
        "no_naked_gate_id_is_canonical": all(gate_id.count(".") >= 5 for gate_id in ids),
        "dependency_DAG_is_topologically_ordered": dependency_ordered,
        "definition_sha256_is_canonical": DEFINITION_SHA256 == _sha(DEFINITION_PAYLOAD),
        "broken_gauge_count_is_derived_as_37": EXPECTED_BROKEN_GAUGE_DIRECTIONS == 37,
        "G6_is_explicitly_nonsupersymmetric": "dimensionful beta" in g6_text and "soft beta" not in g6_text,
        "legacy_namespaces_cannot_satisfy_by_gate_number": all(
            row["can_satisfy_canonical_gate_by_number"] is False
            for row in LEGACY_NAMESPACES.values()
        ),
        "dedicated_artifacts_are_unique": len({g["required_artifact"] for g in GATES}) == 8,
        "trusted_verifier_slots_are_unique_and_fail_closed": (
            len({g["trusted_verifier"]["path"] for g in GATES}) == 8
            and all(
                g["trusted_verifier"]["protocol"] == VERIFIER_SCHEMA
                and g["trusted_verifier"]["mode"] == "raw"
                and (
                    g["trusted_verifier"]["sha256"] is None
                    or (
                        isinstance(g["trusted_verifier"]["sha256"], str)
                        and len(g["trusted_verifier"]["sha256"]) == 64
                        and all(
                            character in "0123456789abcdef"
                            for character in g["trusted_verifier"]["sha256"]
                        )
                    )
                )
                for g in GATES
            )
        ),
        "legacy_namespace_definitions_are_bound_without_hash_cycles": all(
            _legacy_binding_valid(name, row)
            for name, row in LEGACY_SOURCE_BINDINGS.items()
        ),
    }


def build_report(root: Path | str | None = None) -> dict[str, Any]:
    base = Path(root).resolve() if root is not None else ROOT
    rows: list[dict[str, Any]] = []
    closed: set[str] = set()
    for gate in GATES:
        evidence = validate_gate_artifact(gate, base)
        dependencies_closed = all(dep in closed for dep in gate["dependencies"])
        gate_closed = bool(evidence["valid"] and dependencies_closed)
        if gate_closed:
            closed.add(gate["qualified_gate_id"])
        rows.append(
            {
                **gate,
                "definition_sha256": DEFINITION_SHA256,
                "required_evidence_schema": EVIDENCE_SCHEMA,
                "evidence_state": evidence,
                "dependencies_closed": dependencies_closed,
                "closed": gate_closed,
            }
        )
    checks = _definition_checks()
    failures = [name for name, passed in checks.items() if not passed]
    report: dict[str, Any] = {
        "schema": SCHEMA,
        "status": "CANONICAL_GAUGED_U1X_G1_G8_V21_EVALUATED",
        "overall_state": "PASS" if len(closed) == 8 and not failures else "BLOCKED",
        "contract_namespace": CONTRACT_NAMESPACE,
        "model_contract_id": MODEL_CONTRACT_ID,
        "definition_sha256": DEFINITION_SHA256,
        "gauge_dimension_derivation": DEFINITION_PAYLOAD["gauge_dimension_derivation"],
        "gates": rows,
        "closure_counts": {"closed": len(closed), "open": 8 - len(closed)},
        "legacy_mapping": LEGACY_NAMESPACES,
        "legacy_source_bindings": LEGACY_SOURCE_BINDINGS,
        "checks": checks,
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "classification": {
            "all_canonical_gates_closed": len(closed) == 8,
            "whole_model_validated": len(closed) == 8 and not failures,
            "legacy_bare_gate_numbers_authoritative": False,
        },
        "verdict": (
            "All eight qualified canonical gates are closed."
            if len(closed) == 8 and not failures
            else "The canonical definition is valid and closure-capable, but one or more dedicated gate artifacts or dependencies remain open."
        ),
    }
    report["integrity"] = {"core_sha256": _sha(report)}
    return report


def _markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Canonical gauged-U(1)_X G1--G8 contract v21",
        "",
        f"**Namespace:** `{CONTRACT_NAMESPACE}`",
        f"**Definition SHA-256:** `{DEFINITION_SHA256}`",
        f"**Overall state:** `{report['overall_state']}`",
        "",
        report["verdict"],
        "",
        "The historical renormalizable scalar ledger and the legacy irreducible-gap draft are qualified evidence namespaces; matching bare gate numbers cannot close this contract.",
        "",
        "## Gates",
        "",
    ]
    for gate in report["gates"]:
        lines.extend(
            [
                f"### G{gate['gate_number']} -- {gate['title']}",
                "",
                f"- Qualified ID: `{gate['qualified_gate_id']}`",
                f"- Artifact: `{gate['required_artifact']}`",
                f"- Closed: `{gate['closed']}`",
                f"- Evidence: `{gate['evidence_state']['reason']}`",
                "",
            ]
        )
    lines.extend(
        [
            "## Derived gauge count",
            "",
            "The current gauged-X physical target has `45 + 1 - 8 - 1 = 37` broken gauge directions. The legacy 33-Goldstone requirement is not used.",
            "",
            "## G6 scope",
            "",
            "G6 is non-supersymmetric and requires gauge, Yukawa, scalar and dimensionful beta functions; no supersymmetric soft-beta proxy is accepted.",
            "",
        ]
    )
    return "\n".join(lines)


def write_outputs(report: dict[str, Any]) -> None:
    OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    OUT_MD.write_text(_markdown(report), encoding="utf-8", newline="\n")


def _check_outputs(report: dict[str, Any]) -> None:
    expected_json = json.dumps(report, indent=2, sort_keys=True) + "\n"
    expected_md = _markdown(report)
    if not OUT_JSON.exists() or OUT_JSON.read_text(encoding="utf-8") != expected_json:
        raise ArithmeticError("canonical V21 JSON report drifted")
    if not OUT_MD.exists() or OUT_MD.read_text(encoding="utf-8") != expected_md:
        raise ArithmeticError("canonical V21 Markdown report drifted")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    report = build_report()
    if args.write:
        write_outputs(report)
    else:
        _check_outputs(report)
    print(json.dumps({
        "status": report["status"],
        "overall_state": report["overall_state"],
        "definition_sha256": report["definition_sha256"],
        "core_sha256": report["integrity"]["core_sha256"],
        "closed": report["closure_counts"]["closed"],
        "open": report["closure_counts"]["open"],
    }, indent=2))
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
