#!/usr/bin/env python3
"""Decay-safe continuous completion and operator audit for v20.

The v19 completion cancels the continuous ``U(1)_X`` anomalies, but its
singlet anomalons have no renormalizable decay portal.  This module replaces
that sector by three complete Spin(10) ``16 + 16bar`` pairs.  All masses are
generated by the charge-17 scalar ``Phi`` and every pair has a portal to the
ordinary ``16_F`` matter sector.

The claims are deliberately scoped.  In an anomaly sector built only from
complete ``16 + 16bar`` pairs whose renormalizable masses use one ``Phi``
or ``Phi_dagger`` insertion (no Spin(10)-singlet anomalons), three pairs are
minimal.  The displayed solution is also the unique
three-pair solution in the finite portal basis built from the already-present
``10_H``, ``S`` and ``210_H`` fields.  This is not a classification of all
possible Spin(10) representations or all UV completions.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass
from functools import lru_cache
import heapq
import itertools
import math
from typing import Iterable, Mapping, Sequence


LIGHT_ANOMALY = (-34, -272, -16592)
MPL = 2.435e18
HBAR_GEV_S = 6.582119569e-25


@dataclass(frozen=True)
class HeavyPair:
    name: str
    x16: int
    xbar16: int
    pq16: int
    pqbar16: int
    phi_charge_in_mass: int
    portal: str
    portal_x_sum: int
    portal_pq_sum: int

    @property
    def x_sum(self) -> int:
        return self.x16 + self.xbar16

    @property
    def cubic_before_dimension(self) -> int:
        return self.x16**3 + self.xbar16**3

    @property
    def x2_before_dimension(self) -> int:
        return self.x16**2 + self.xbar16**2


HEAVY_PAIRS: tuple[HeavyPair, ...] = (
    HeavyPair(
        "A",
        +1,
        +16,
        +1,
        -1,
        -17,
        "16_A,1 16_F,1 10_H,-2",
        1 + 1 - 2,
        1 + 1 - 2,
    ),
    HeavyPair(
        "B",
        +14,
        +3,
        -3,
        +3,
        -17,
        "16bar_B,3 16_F,1 S_dagger,-4",
        3 + 1 - 4,
        3 + 1 - 4,
    ),
    HeavyPair(
        "C",
        +1,
        -18,
        +1,
        -1,
        +17,
        "16_C,1 16_F,1 10_H,-2",
        1 + 1 - 2,
        1 + 1 - 2,
    ),
)


def anomaly_report() -> dict:
    x_sum = sum(pair.x_sum for pair in HEAVY_PAIRS)
    cubic_base = sum(pair.cubic_before_dimension for pair in HEAVY_PAIRS)
    heavy = (2 * x_sum, 16 * x_sum, 16 * cubic_base)
    total = tuple(light + extra for light, extra in zip(LIGHT_ANOMALY, heavy))
    heavy_pq_mixed = 2 * sum(pair.pq16 + pair.pqbar16 for pair in HEAVY_PAIRS)
    return {
        "convention": "(A[Spin(10)^2 U(1)_X], A[grav^2 U(1)_X], A[U(1)_X^3])",
        "light": LIGHT_ANOMALY,
        "three_complete_pairs": heavy,
        "total": total,
        "all_continuous_anomalies_cancel": total == (0, 0, 0),
        "heavy_accidental_PQ_mixed_Spin10_anomaly": heavy_pq_mixed,
        "qcd_axion_anomaly_unchanged": heavy_pq_mixed == 0,
        "pair_cubic_units_before_dim16": [
            pair.cubic_before_dimension for pair in HEAVY_PAIRS
        ],
    }


def portal_pair_options(phi_mass_sign: int) -> tuple[tuple[int, int, str], ...]:
    """Finite decay-portal basis using fields already present in the model.

    The returned tuples are ``(X_16, X_16bar, portal)``.  The first two
    options couple the heavy 16 to ``16_F 10_H^(dagger)``; the next two
    couple the heavy 16bar to ``16_F S^(dagger)``; the last uses
    ``16bar 16_F 210_H``.  ``phi_mass_sign`` is +1 for pair charge sum +17
    (a Phi-dagger mass) and -1 for sum -17 (a Phi mass).
    """
    if phi_mass_sign not in (-1, +1):
        raise ValueError("phi_mass_sign must be +1 or -1")
    total = 17 * phi_mass_sign
    return (
        (+1, total - 1, "16 16_F 10_H"),
        (-3, total + 3, "16 16_F 10_H_dagger"),
        (total + 5, -5, "16bar 16_F S"),
        (total - 3, +3, "16bar 16_F S_dagger"),
        (total + 1, -1, "16bar 16_F 210_H"),
    )


def minimality_report() -> dict:
    """Prove the one-pair obstruction and enumerate the three-pair portal basis."""
    # Mixed and gravitational cancellation require n_plus - n_minus = 1.
    # Therefore the number of Phi-massed pairs is odd.  For one pair,
    # x+y=17 and x^3+y^3=1037 imply xy=76 and discriminant -15.
    one_pair_discriminant = 17**2 - 4 * 76
    positive = portal_pair_options(+1)
    negative = portal_pair_options(-1)
    solutions: list[tuple[tuple[int, int], ...]] = []
    for plus_pairs in itertools.combinations_with_replacement(positive, 2):
        for minus_pair in negative:
            fields = plus_pairs + (minus_pair,)
            cubic = sum(x**3 + y**3 for x, y, _portal in fields)
            if cubic == 1037:
                solutions.append(tuple((x, y) for x, y, _portal in fields))
    canonical = ((1, 16), (14, 3), (1, -18))
    return {
        "ansatz": (
            "anomaly sector built only from complete 16+16bar pairs, each "
            "massed renormalizably by one Phi or Phi_dagger (no singlet "
            "anomalons); portal enumeration uses existing 10_H, S, 210_H"
        ),
        "mixed_anomaly_condition": "n_plus - n_minus = 1",
        "pair_number_must_be_odd": True,
        "one_pair_required_product_xy": 76,
        "one_pair_quadratic_discriminant": one_pair_discriminant,
        "one_pair_impossible_even_over_real_charges": one_pair_discriminant < 0,
        "minimum_number_of_pairs": 3,
        "three_pair_portal_basis_solutions": solutions,
        "canonical_solution": canonical,
        "canonical_is_unique_in_portal_basis": solutions == [canonical],
    }


def mass_and_portal_audit() -> dict:
    rows = []
    for pair in HEAVY_PAIRS:
        rows.append(
            {
                "pair": pair.name,
                "X": [pair.x16, pair.xbar16],
                "PQ": [pair.pq16, pair.pqbar16],
                "mass_X_sum": pair.phi_charge_in_mass + pair.x_sum,
                "mass_PQ_sum": pair.pq16 + pair.pqbar16,
                "portal": pair.portal,
                "portal_X_sum": pair.portal_x_sum,
                "portal_PQ_sum": pair.portal_pq_sum,
            }
        )
    return {
        "pairs": rows,
        "all_masses_gauge_and_PQ_invariant": all(
            row["mass_X_sum"] == row["mass_PQ_sum"] == 0 for row in rows
        ),
        "all_portals_gauge_and_PQ_invariant": all(
            row["portal_X_sum"] == row["portal_PQ_sum"] == 0 for row in rows
        ),
        "ordinary_chiral_families_after_generic_rank_two_X1_mass_matrix": 3,
        "explanation": (
            "the three ordinary 16_F plus two added 16_1 fields pair with "
            "16bar_16 and 16bar_-18 at rank two, leaving three light 16s"
        ),
    }


def decay_report(
    v_phi: float = 1.0e17,
    heavy_yukawa: float = 1.0,
    example_portal: float = 1.0e-8,
    final_mass: float = 0.0,
) -> dict:
    """One-channel widths with explicit two-body kinematics.

    The massless expression ``|lambda|^2 M/(32 pi)`` is an *upper* benchmark:
    ``Gamma = |lambda|^2 M/(32 pi) * (1 - m_final^2/M^2)^2`` for
    ``m_final < M``.  Lifetime claims that use the massless formula as a
    lower bound on the width are therefore too optimistic.
    """
    mass = heavy_yukawa * v_phi / math.sqrt(2.0)
    massless = example_portal**2 * mass / (32.0 * math.pi)
    if final_mass >= mass:
        kinematic = 0.0
        width = 0.0
    else:
        kinematic = (1.0 - (final_mass / mass) ** 2) ** 2
        width = massless * kinematic
    lifetime = float("inf") if width == 0.0 else HBAR_GEV_S / width
    portal_for_one_second = math.sqrt(32.0 * math.pi * HBAR_GEV_S / mass)
    return {
        "heavy_mass_GeV": mass,
        "width_formula": (
            "Gamma = |lambda|^2 M/(32 pi) * (1-m_final^2/M^2)^2 "
            "<= |lambda|^2 M/(32 pi) for one open normalized channel"
        ),
        "example_portal": example_portal,
        "example_final_mass_GeV": final_mass,
        "example_kinematic_factor": kinematic,
        "example_massless_upper_width_GeV": massless,
        "example_width_GeV": width,
        "example_lifetime_s": lifetime,
        "minimum_normalized_portal_for_lifetime_below_one_second": portal_for_one_second,
        "minimum_portal_scope": (
            "massless upper-width inversion; massive finals require a larger |lambda|"
        ),
        "no_exact_anomalon_number": True,
        "scope": (
            "the Spin(10) tensor audit proves every 16 component has a nonzero "
            "10-channel; a detailed broken-phase Clebsch and flavour fit remains external"
        ),
    }


def running_report(v_phi: float = 1.0e17, cutoff: float = MPL) -> dict:
    light_fermion_q2 = 3 * 16 * 1**2 + 5 * 16 * (2**2 + (-6) ** 2)
    heavy_fermion_q2 = 16 * sum(pair.x2_before_dimension for pair in HEAVY_PAIRS)
    fermion_q2 = light_fermion_q2 + heavy_fermion_q2
    scalar_q2 = 1 * 4**2 + 10 * (-2) ** 2 + 126 * (-2) ** 2 + 1 * 17**2
    b_x = (2.0 / 3.0) * fermion_q2 + (1.0 / 3.0) * scalar_q2
    logarithm = math.log(cutoff / v_phi)
    gx_max = math.sqrt(8.0 * math.pi**2 / (b_x * logarithm))
    example_gx = 0.04

    # Conservative unified-running envelope: treat even the real 210_H as
    # complex.  T(16,10,126,210)=(2,1,35,56), C2(adj)=8.
    sum_weyl_t = 3 * 2 + 10 * 2 + 6 * 2
    sum_scalar_t_conservative = 1 + 35 + 56
    b_10_conservative = (
        -(11.0 / 3.0) * 8
        + (2.0 / 3.0) * sum_weyl_t
        + (1.0 / 3.0) * sum_scalar_t_conservative
    )
    alpha10_max = 2.0 * math.pi / (b_10_conservative * logarithm)
    # Historical envelope used in earlier drafts.  Kept only as a diagnostic:
    # it is *not* the continuous value implied by the model's alpha_GUT.
    example_alpha10_reset = 1.0 / 40.0
    m_gut = 9.9176e15
    alpha_inv_gut = 37.313 - (40.0 / 3.0) / (2.0 * math.pi) * math.log(m_gut / 6.313855e11)
    b_10_physical = (
        -(11.0 / 3.0) * 8
        + (2.0 / 3.0) * sum_weyl_t
        + (1.0 / 3.0) * (1 + 35)
        + (1.0 / 6.0) * 56
    )
    alpha_inv_vphi_cons = alpha_inv_gut - (b_10_conservative / (2.0 * math.pi)) * math.log(
        v_phi / m_gut
    )
    alpha_inv_mpl_cons = alpha_inv_vphi_cons - (
        b_10_conservative / (2.0 * math.pi)
    ) * math.log(cutoff / v_phi)
    alpha_inv_vphi_phys = alpha_inv_gut - (b_10_physical / (2.0 * math.pi)) * math.log(
        v_phi / m_gut
    )
    alpha_inv_mpl_phys = alpha_inv_vphi_phys - (b_10_physical / (2.0 * math.pi)) * math.log(
        cutoff / v_phi
    )
    return {
        "sum_Weyl_dimR_X2_light": light_fermion_q2,
        "sum_Weyl_dimR_X2_heavy": heavy_fermion_q2,
        "sum_Weyl_dimR_X2_total": fermion_q2,
        "sum_complex_scalar_dimR_X2": scalar_q2,
        "b_X_one_loop": b_x,
        "maximum_gX_for_landau_pole_above_cutoff": gx_max,
        "example_gX": example_gx,
        "example_U1X_landau_pole_GeV": v_phi
        * math.exp(8.0 * math.pi**2 / (b_x * example_gx**2)),
        "conservative_b_Spin10_above_vPhi": b_10_conservative,
        "physical_b_Spin10_above_vPhi": b_10_physical,
        "maximum_alpha10_vPhi_for_landau_pole_above_cutoff": alpha10_max,
        "example_alpha10_inconsistent_reset": example_alpha10_reset,
        "example_alpha10": example_alpha10_reset,
        "example_Spin10_landau_pole_GeV": v_phi
        * math.exp(2.0 * math.pi / (b_10_conservative * example_alpha10_reset)),
        "continuous_from_spectator_corrected_alpha_GUT": {
            "alpha_inv_GUT": alpha_inv_gut,
            "conservative": {
                "alpha_inv_vPhi": alpha_inv_vphi_cons,
                "alpha_inv_MPl": alpha_inv_mpl_cons,
                "landau_pole_below_MPl": alpha_inv_mpl_cons <= 0.0,
            },
            "physical_real_210": {
                "alpha_inv_vPhi": alpha_inv_vphi_phys,
                "alpha_inv_MPl": alpha_inv_mpl_phys,
                "alpha_MPl": None
                if alpha_inv_mpl_phys <= 0.0
                else 1.0 / alpha_inv_mpl_phys,
                "weakly_coupled_alpha_lt_0.25": alpha_inv_mpl_phys > 4.0,
            },
            "verdict": (
                "resetting alpha_10(v_Phi)=1/40 is inconsistent with continuous "
                "one-loop running; the continuous trajectory is not perturbative "
                "to M_Pl under these betas"
            ),
        },
        "complete_multiplets_preserve_one_loop_relative_unification": True,
        "cutoff_GeV": cutoff,
    }


@dataclass(frozen=True)
class Field:
    name: str
    x: int
    pq: int
    centre: int
    spectator_vector: int


# The two added 16_1 fields share the charge state of F and need not be
# duplicated in a necessary-condition charge frontier.  Multiplicity is
# restored in the explicit anomaly and graph audits.
_BASE_FERMIONS: tuple[Field, ...] = (
    Field("F", +1, +1, +1, 0),
    Field("s", +2, +2, +1, +1),
    Field("b", -6, -6, -1, -1),
    Field("Q", +14, -3, +1, 0),
    Field("Bp", +16, -1, -1, 0),
    Field("Bq", +3, +3, -1, 0),
    Field("Bm", -18, -1, -1, 0),
)


def _with_conjugates(fields: Iterable[Field]) -> tuple[Field, ...]:
    answer: list[Field] = []
    for field in fields:
        answer.append(field)
        answer.append(
            Field(
                field.name + "d",
                -field.x,
                -field.pq,
                -field.centre,
                -field.spectator_vector,
            )
        )
    return tuple(answer)


FERMIONS = _with_conjugates(_BASE_FERMIONS)
SCALARS: tuple[Field, ...] = (
    Field("S", +4, +4, 0, 0),
    Field("Sd", -4, -4, 0, 0),
    Field("Hm", -2, -2, +2, 0),
    Field("Hp", +2, +2, +2, 0),
    Field("Phi", +17, 0, 0, 0),
    Field("Phid", -17, 0, 0, 0),
)


@dataclass(frozen=True)
class Operator:
    dimension: int
    x: int
    pq: int
    spectator_vector: int
    n_fermions: int
    labels: tuple[str, ...]

    @property
    def planck_power(self) -> int:
        return self.dimension - 4

    @property
    def label(self) -> str:
        counts = Counter(self.labels)
        return " ".join(
            name if count == 1 else f"{name}^{count}"
            for name, count in sorted(counts.items())
        )

    def as_dict(self) -> dict:
        return {
            "label": self.label,
            "dimension": self.dimension,
            "P": self.planck_power,
            "X": self.x,
            "Q_PQ": self.pq,
            "V_s": self.spectator_vector,
            "n_fermions": self.n_fermions,
        }


@dataclass(frozen=True)
class Closure:
    planck_power: int
    pq: int
    spectator_vector: int
    operators: tuple[Operator, ...]

    def as_dict(self) -> dict:
        counts = Counter(operator.label for operator in self.operators)
        representatives = {operator.label: operator for operator in self.operators}
        return {
            "P": self.planck_power,
            "Q_PQ": self.pq,
            "V_s": self.spectator_vector,
            "operators": [
                {"multiplicity": counts[label], **representatives[label].as_dict()}
                for label in sorted(counts)
            ],
        }


def _layers(fields: Sequence[Field], maximum_number: int) -> tuple[dict, ...]:
    layers: list[dict] = [{(0, 0, 0, 0): ()}]
    for _ in range(maximum_number):
        new: dict[tuple[int, int, int, int], tuple[str, ...]] = {}
        for (x, pq, centre, vector), labels in layers[-1].items():
            for field in fields:
                key = (
                    x + field.x,
                    pq + field.pq,
                    (centre + field.centre) % 4,
                    vector + field.spectator_vector,
                )
                candidate = tuple(sorted(labels + (field.name,)))
                if key not in new or candidate < new[key]:
                    new[key] = candidate
        layers.append(new)
    return tuple(layers)


@lru_cache(maxsize=None)
def operator_frontier(maximum_dimension: int = 16) -> dict[tuple[int, int], Operator]:
    """Necessary-condition frontier tracking the one exact spectator number."""
    fermion_layers = _layers(FERMIONS, 2 * maximum_dimension // 3)
    scalar_layers = _layers(SCALARS, maximum_dimension)
    scalar_index: list[dict[tuple[int, int], list[tuple[int, tuple[str, ...]]]]] = []
    for layer in scalar_layers:
        index: dict[tuple[int, int], list[tuple[int, tuple[str, ...]]]] = defaultdict(list)
        for (x, pq, centre, _vector), labels in layer.items():
            index[(x, centre)].append((pq, labels))
        scalar_index.append(index)

    frontier: dict[tuple[int, int], Operator] = {}
    for n_fermions in range(0, 2 * maximum_dimension // 3 + 1, 2):
        fermion_dimension = 3 * n_fermions // 2
        for n_scalars in range(maximum_dimension - fermion_dimension + 1):
            dimension = fermion_dimension + n_scalars
            if dimension < 5:
                continue
            for (fx, fpq, centre, vector), flabels in fermion_layers[n_fermions].items():
                for spq, slabels in scalar_index[n_scalars].get((-fx, (-centre) % 4), ()):
                    pq = fpq + spq
                    if pq == 0 and vector == 0:
                        continue
                    operator = Operator(
                        dimension,
                        0,
                        pq,
                        vector,
                        n_fermions,
                        flabels + slabels,
                    )
                    key = (pq, vector)
                    old = frontier.get(key)
                    if old is None or (operator.dimension, operator.label) < (
                        old.dimension,
                        old.label,
                    ):
                        frontier[key] = operator
    return frontier


def renormalizable_accidental_audit() -> dict:
    """Conservative superset of all dimension-four-or-lower monomials."""
    fermion_layers = _layers(FERMIONS, 2)
    scalar_layers = _layers(SCALARS, 4)
    dangerous: list[Operator] = []
    for n_fermions in (0, 2):
        fermion_dimension = 3 * n_fermions // 2
        for n_scalars in range(5 - fermion_dimension):
            dimension = fermion_dimension + n_scalars
            if dimension == 0 or dimension > 4:
                continue
            for (fx, fpq, centre, vector), flabels in fermion_layers[n_fermions].items():
                for (sx, spq, scalar_centre, _), slabels in scalar_layers[n_scalars].items():
                    if fx + sx or (centre + scalar_centre) % 4:
                        continue
                    pq = fpq + spq
                    if pq == 0 and vector == 0:
                        continue
                    dangerous.append(
                        Operator(
                            dimension,
                            0,
                            pq,
                            vector,
                            n_fermions,
                            flabels + slabels,
                        )
                    )
    unique = {(operator.dimension, operator.label): operator for operator in dangerous}
    ordered = [unique[key].as_dict() for key in sorted(unique)]
    return {
        "catalogue": "Lorentz parity + Spin(10)-centre necessary-condition superset",
        "pq_or_spectator_vector_breaking_candidates": ordered,
        "accidental_PQ_and_spectator_vector_exact_at_d_le_4": not ordered,
    }


def minimum_vacuum_closure(
    frontier: Mapping[tuple[int, int], Operator],
    maximum_planck_power: int = 16,
) -> Closure | None:
    useful = sorted(
        (operator for operator in frontier.values() if operator.planck_power > 0),
        key=lambda operator: (
            operator.planck_power,
            abs(operator.pq),
            abs(operator.spectator_vector),
            operator.label,
        ),
    )
    start = (0, 0)
    best: dict[tuple[int, int], int] = {start: 0}
    previous: dict[tuple[int, int], tuple[tuple[int, int], Operator]] = {}
    queue: list[tuple[int, int, int]] = [(0, 0, 0)]
    while queue:
        cost, pq, vector = heapq.heappop(queue)
        state = (pq, vector)
        if cost != best.get(state) or cost > maximum_planck_power:
            continue
        if state != start and pq and pq % 4 == 0 and vector == 0:
            path: list[Operator] = []
            while state != start:
                old, operator = previous[state]
                path.append(operator)
                state = old
            path.reverse()
            return Closure(cost, pq, vector, tuple(path))
        for operator in useful:
            new_cost = cost + operator.planck_power
            if new_cost > maximum_planck_power:
                continue
            new_state = (pq + operator.pq, vector + operator.spectator_vector)
            if new_cost < best.get(new_state, math.inf):
                best[new_state] = new_cost
                previous[new_state] = (state, operator)
                heapq.heappush(queue, (new_cost, *new_state))
    return None


def explicit_p8_certificate() -> Closure:
    operators = operator_frontier(16).values()

    def find(dimension: int, required: Counter[str]) -> Operator:
        for operator in operators:
            if operator.dimension == dimension and Counter(operator.labels) == required:
                return operator
        raise RuntimeError(f"explicit operator not found: {required}")

    portal = find(5, Counter({"Q": 1, "b": 1, "Sd": 2}))
    light = find(8, Counter({"s": 4, "Sd": 2}))
    selected = (portal, portal, portal, portal, light)
    return Closure(
        sum(operator.planck_power for operator in selected),
        sum(operator.pq for operator in selected),
        sum(operator.spectator_vector for operator in selected),
        selected,
    )


def p8_one_loop_lorentz_factor() -> int:
    """Explicit two-component contraction for one factorized v20 loop.

    The contraction includes the central ``ss`` bilinear, two ``Qb``
    bilinears, spectator and heavy chirality-flipping propagators, two decay
    vertices, two family kinetic numerators (evaluated in a unit Euclidean
    time-momentum direction), and one conjugate family Yukawa.  Lorentz
    invariance then promotes the unit result to the coefficient of ``p^2``.
    The second factorized loop gives the same factor.
    """
    epsilon_down = ((0, 1), (-1, 0))
    epsilon_up = ((0, -1), (1, 0))
    sigma_time = ((1, 0), (0, 1))
    total = 0
    # s[2], q[2], b[2], qbar[2], f[2], fdot[2]
    for values in itertools.product(range(2), repeat=12):
        s = values[0:2]
        q = values[2:4]
        b = values[4:6]
        qbar = values[6:8]
        family = values[8:10]
        dotted = values[10:12]
        term = epsilon_down[s[0]][s[1]] * epsilon_up[dotted[0]][dotted[1]]
        for index in range(2):
            term *= epsilon_down[q[index]][b[index]]
            term *= epsilon_up[s[index]][b[index]]
            term *= epsilon_up[q[index]][qbar[index]]
            term *= epsilon_down[qbar[index]][family[index]]
            term *= sigma_time[family[index]][dotted[index]]
        total += term
    return total


def build_report(v_s: float = 6.313855e11, v_phi: float = 1.0e17) -> dict:
    frontier = operator_frontier(16)
    closure = minimum_vacuum_closure(frontier, 16)
    certificate = explicit_p8_certificate()
    return {
        "status": "minimal three-pair decay-safe U(1)_X completion",
        "charges": [
            {
                "pair": pair.name,
                "Spin10": ["16", "16bar"],
                "X": [pair.x16, pair.xbar16],
                "PQ": [pair.pq16, pair.pqbar16],
            }
            for pair in HEAVY_PAIRS
        ],
        "anomalies": anomaly_report(),
        "minimality": minimality_report(),
        "masses_and_portals": mass_and_portal_audit(),
        "decays": decay_report(v_phi),
        "renormalizable_audit": renormalizable_accidental_audit(),
        "quality_overcatalogue": {
            "maximum_local_dimension": 16,
            "frontier_states": len(frontier),
            "no_vacuum_closure_through_P7": closure is not None
            and closure.planck_power == 8,
            "minimum": None if closure is None else closure.as_dict(),
            "explicit_spin10_certificate": certificate.as_dict(),
            "explicit_graph": {
                "operators": "4 (Sd)^2 (16_14 b) + (Sd)^2 (s s)_10 (s s)_10",
                "renormalizable_structure": (
                    "four left-left s-b propagators carrying Sd, four left-left "
                    "16_14-16bar_3 propagators carrying Phi, four 16bar_3 F Sd "
                    "portals, and two conjugate F F 10_H Yukawas"
                ),
                "topology": "connected factorized two-loop graph",
                "resulting_phase": "Phi^4 (Sd)^18 (Hp)^2",
                "Q_PQ": -68,
                "X": 0,
            },
        },
        "running": running_report(v_phi),
        "declared_limitations": [
            "minimality assumes an anomalon sector made only of complete 16+16bar pairs massed by one Phi insertion",
            "broken-phase Clebsch factors and flavour textures are not fitted",
            "the vPhi/vS hierarchy still needs radiative stabilization",
            "Planck-scale Wilson tensors remain unknown normalized coefficients",
            "the U(1)_X cosmic-string network remains unsimulated",
            "continuous one-loop Spin(10) running from spectator-corrected alpha_GUT is not perturbative to M_Pl",
            "extra gauge/PQ-invariant portals beyond the displayed list remain unfitted",
            "massless decay-width formulae are upper benchmarks, not lower bounds",
        ],
        "benchmark": {"v_s_GeV": v_s, "v_phi_GeV": v_phi},
    }


__all__ = [
    "FERMIONS",
    "HEAVY_PAIRS",
    "SCALARS",
    "anomaly_report",
    "build_report",
    "decay_report",
    "explicit_p8_certificate",
    "mass_and_portal_audit",
    "minimality_report",
    "minimum_vacuum_closure",
    "operator_frontier",
    "p8_one_loop_lorentz_factor",
    "portal_pair_options",
    "renormalizable_accidental_audit",
    "running_report",
]


if __name__ == "__main__":
    import json

    print(json.dumps(build_report(), indent=2))
