#!/usr/bin/env python3
"""Invalidate the former EFJX-to-lambda4 CGC route and point to the direct tensor map.

Aulakh hep-ph/0405074 Appendix-A E/F/J/X matrices include a final gaugino
row/column. Their entries proportional to ``g`` are generated by the SO(10)
gauge coupling through the super-Higgs mechanism. They are not entries
proportional to the superpotential coupling ``gamma`` in Eq. (1).

Earlier repository versions mapped that ``g`` to the Python key ``gamma`` and
then treated the resulting response as a target for the non-SUSY lambda4
portal. That category error invalidates the EFJX-derived CGC normalization and
the later 8.8e29 bound.

The replacement is ``direct_phi_h_sigmabar_tensor_v20.py``, which constructs
the non-SUSY 10 x 126 scalar mixing tensor directly from antisymmetric forms.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import direct_phi_h_sigmabar_tensor_v20 as direct

ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "EFJX_CGC_PHYSICAL_NORMALIZATION_GATE_V20.json"
OUT_MD = ROOT / "EFJX_CGC_PHYSICAL_NORMALIZATION_GATE_V20.md"


def build_report() -> dict[str, Any]:
    tensor = direct.build_report()
    checks = {
        "aulakh_EFJX_last_states_are_gauginos": True,
        "aulakh_EFJX_g_is_gauge_coupling": True,
        "aulakh_gamma_is_distinct_superpotential_parameter": True,
        "old_python_gamma_symbol_collision_identified": True,
        "old_8p8e29_bound_invalidated": True,
        "direct_nonsusy_tensor_map_executes": tensor.get("n_failed") == 0,
        "whole_model_not_overclaimed": True,
    }
    failures = [name for name, passed in checks.items() if not passed]
    return {
        "status": (
            "EFJX_CGC_ROUTE_INVALIDATED__G_IS_GAUGE_COUPLING"
            if not failures
            else "EFJX_SOURCE_CORRECTION_FAILED"
        ),
        "overall_state": "BLOCKED",
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failed_checks": failures,
        "checks": checks,
        "source_audit": {
            "primary_source": "Aulakh and Girdhar, hep-ph/0405074",
            "eq1": (
                "gamma and gamma_bar multiply H_i Phi_jklm Sigma_ijklm in the "
                "superpotential with prefactor 1/4!."
            ),
            "eq27": "g multiplies Higgs-fermion/gaugino terms from the gauge interaction.",
            "appendix_eqs_87_90": (
                "E/F/J/X include gaugino states in the final row/column; the "
                "displayed g entries are gauge-super-Higgs mixings."
            ),
            "repository_error": (
                "mixed_210_126_10_cw_v20.py assigned p['gamma'] to a local variable g "
                "inside E/F/J/X, conflating two physically distinct couplings."
            ),
        },
        "direct_tensor_replacement": {
            "status": tensor.get("status"),
            "map_shape": tensor.get("representation", {}).get("tensor_map_shape"),
            "p_rank": tensor.get("fingerprints", {}).get("p", {}).get("rank"),
            "a_rank": tensor.get("fingerprints", {}).get("a", {}).get("rank"),
            "omega_rank": tensor.get("fingerprints", {}).get("omega", {}).get("rank"),
            "equivariance_residual": tensor.get("equivariance_max_abs_residual"),
        },
        "normalization_artifact": {
            "exists": False,
            "accepted": False,
            "reason": (
                "EFJX is not a valid target for lambda4 CGC closure; a direct non-SUSY "
                "component mass-squared artifact is required instead."
            ),
            "validation_errors": ["wrong_physical_target_EFJX_gaugino_blocks"],
        },
        "proxy_dependency_audit": {
            "reported_proxy_c_cgc_needed_abs_approx": None,
            "reported_8p8e29_bound": None,
            "classification": "invalidated by source-symbol collision",
            "physical_H10_EW_GeV": 174.0,
        },
        "remaining_blockers": {
            "canonical_Phi_H_Sigmabar_tensor_contraction": False,
            "published_state_label_dictionary": True,
            "direct_nonsusy_component_mass_squared_insertion": True,
            "full_component_hessian": True,
            "global_vacuum_and_boundedness": True,
        },
        "flags": {
            "exact_EFJX_gamma_response_known": False,
            "exact_EFJX_gauge_response_known": True,
            "EFJX_response_known_but_physical_CGC_open": False,
            "efjx_cgc_route_invalidated": True,
            "old_8p8e29_bound_valid": False,
            "proxy_cgc_ratio_invalid_as_physical_prediction": True,
            "physical_CGC_normalization_derived": False,
            "physical_EW_branch_revalidated": False,
            "CGC_subproblem_closed": False,
            "whole_model_excluded": False,
            "whole_model_validated": False,
        },
        "verdict": (
            "The E/F/J/X lambda4-CGC campaign is invalid: its g entries are gauge/gaugino "
            "super-Higgs mixings, not gamma. The direct non-SUSY p,a,omega tensor map now "
            "replaces that route. The prior 8.8e29 no-go is withdrawn; the full scalar "
            "mass-squared Hessian remains open."
        ),
    }


def main() -> int:
    argparse.ArgumentParser(description=__doc__).parse_args()
    report = build_report()
    OUT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    OUT_MD.write_text("# EFJX source correction — v20\n\n" + report["verdict"] + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2))
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
