#!/usr/bin/env python3
"""Complete six-invariant basis for 210_H^2 126bar_H^dag 126bar_H.

The exact live D5 census gives multiplicity six.  Every SO(10) scalar made
from two four-forms and a conjugate chiral five-form pair is generated by
delta and epsilon contractions.  On a chiral five-form, epsilon is Hodge star
and equals +/-i, so epsilon contractions reduce to delta contractions.

A delta contraction is determined by edge multiplicities among tensor vertices
(P,Q,Sdag,S), of degrees (4,4,5,5).  The degree equations have exactly fifteen
solutions.  Six explicitly selected contractions have a nonzero exact integer
sample determinant; since the invariant multiplicity is exactly six, they form
a complete basis.

This closes this finite G1 family only. Common normalization across all live
coefficient directions, G1, G2, and the full theory remain open.
"""
from __future__ import annotations

import argparse
import itertools
import json
import string
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np

import g1_exact_declared_symmetry_character_census_v20 as census

ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "EXACT_PHI2_126DAG126_SIX_CONTRACTIONS_V20.json"
OUT_MD = ROOT / "EXACT_PHI2_126DAG126_SIX_CONTRACTIONS_V20.md"
N = 10
Form = dict[tuple[int, ...], complex]
C4 = tuple(itertools.combinations(range(N), 4))
C5 = tuple(itertools.combinations(range(N), 5))
LETTERS = tuple(string.ascii_lowercase + string.ascii_uppercase)

# (n_PQ, n_P_Sdag, n_P_S, n_Q_Sdag, n_Q_S, n_Sdag_S)
SELECTED_EDGES = (
    (0, 0, 4, 4, 0, 1),
    (0, 1, 3, 3, 1, 1),
    (0, 2, 2, 2, 2, 1),
    (1, 0, 3, 3, 0, 2),
    (1, 1, 2, 2, 1, 2),
    (2, 0, 2, 2, 0, 3),
)
WITNESS_SEEDS = (1, 2, 4, 5, 6, 7)
EXPECTED_WITNESS_DETERMINANT = -9914903866971402877520576679396350361600


def permutation_sign(sequence: tuple[int, ...]) -> int:
    inversions = sum(
        sequence[i] > sequence[j]
        for i in range(len(sequence))
        for j in range(i + 1, len(sequence))
    )
    return -1 if inversions % 2 else 1


def add_forms(*forms: Form) -> Form:
    output: defaultdict[tuple[int, ...], complex] = defaultdict(complex)
    for form in forms:
        for indices, coefficient in form.items():
            output[indices] += coefficient
    return {k: v for k, v in output.items() if abs(v) > 1e-13}


def scale_form(form: Form, coefficient: complex) -> Form:
    return {indices: coefficient * value for indices, value in form.items()}


def one_form(index: int) -> Form:
    return {(index,): 1.0 + 0.0j}


def wedge(left: Form, right: Form) -> Form:
    output: defaultdict[tuple[int, ...], complex] = defaultdict(complex)
    for left_indices, left_value in left.items():
        for right_indices, right_value in right.items():
            if set(left_indices).intersection(right_indices):
                continue
            sequence = left_indices + right_indices
            ordered = tuple(sorted(sequence))
            output[ordered] += left_value * right_value * permutation_sign(sequence)
    return {k: v for k, v in output.items() if abs(v) > 1e-13}


def interior(form: Form, index: int) -> Form:
    output: defaultdict[tuple[int, ...], complex] = defaultdict(complex)
    for indices, coefficient in form.items():
        if index not in indices:
            continue
        position = indices.index(index)
        reduced = indices[:position] + indices[position + 1 :]
        output[reduced] += ((-1) ** position) * coefficient
    return dict(output)


def hodge_star(form: Form) -> Form:
    output: defaultdict[tuple[int, ...], complex] = defaultdict(complex)
    full = set(range(N))
    for indices, coefficient in form.items():
        complement = tuple(sorted(full.difference(indices)))
        output[complement] += coefficient * permutation_sign(indices + complement)
    return dict(output)


def generator_action(form: Form, a: int, b: int) -> Form:
    return add_forms(
        wedge(one_form(a), interior(form, b)),
        scale_form(wedge(one_form(b), interior(form, a)), -1.0),
    )


def dense_antisymmetric(form: Form, degree: int) -> np.ndarray:
    output = np.zeros((N,) * degree, dtype=complex)
    for indices, coefficient in form.items():
        for ordered in itertools.permutations(indices):
            output[ordered] = coefficient * permutation_sign(ordered)
    return output


def graph_solutions() -> tuple[tuple[int, ...], ...]:
    rows: list[tuple[int, ...]] = []
    for n_pq in range(5):
        for n_psd in range(5):
            for n_ps in range(5):
                for n_qsd in range(5):
                    for n_qs in range(5):
                        for n_sds in range(6):
                            row = (n_pq, n_psd, n_ps, n_qsd, n_qs, n_sds)
                            if (
                                n_pq + n_psd + n_ps == 4
                                and n_pq + n_qsd + n_qs == 4
                                and n_psd + n_qsd + n_sds == 5
                                and n_ps + n_qs + n_sds == 5
                            ):
                                rows.append(row)
    return tuple(rows)


def graph_subscript(edges: tuple[int, ...]) -> str:
    counts = dict(
        zip(((0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)), edges)
    )
    labels: list[list[str]] = [[] for _ in range(4)]
    cursor = 0
    for edge in ((0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)):
        for _ in range(counts[edge]):
            label = LETTERS[cursor]
            cursor += 1
            labels[edge[0]].append(label)
            labels[edge[1]].append(label)
    if tuple(map(len, labels)) != (4, 4, 5, 5):
        raise AssertionError("invalid graph degree")
    return ",".join("".join(row) for row in labels) + "->"


def contraction(
    edges: tuple[int, ...],
    phi_left: np.ndarray,
    phi_right: np.ndarray,
    sigma_dag: np.ndarray,
    sigma: np.ndarray,
) -> complex:
    return complex(
        np.einsum(
            graph_subscript(edges),
            phi_left,
            phi_right,
            sigma_dag,
            sigma,
            optimize="greedy",
        )
    )


def selected_contractions(
    phi_left: np.ndarray,
    phi_right: np.ndarray,
    sigma_dag: np.ndarray,
    sigma: np.ndarray,
) -> np.ndarray:
    return np.asarray(
        [
            contraction(edges, phi_left, phi_right, sigma_dag, sigma)
            for edges in SELECTED_EDGES
        ],
        dtype=complex,
    )


def deterministic_forms(seed: int) -> tuple[Form, Form, Form]:
    phi = {
        indices: complex(((index * (2 * seed + 1) + 3 * seed + 1) % 7) - 3)
        for index, indices in enumerate(C4)
    }
    unconstrained_five: Form = {}
    for index, indices in enumerate(C5):
        real = ((index * (3 * seed + 2) + 5 * seed + 1) % 5) - 2
        imag = ((index * (5 * seed + 1) + 2 * seed + 3) % 5) - 2
        unconstrained_five[indices] = complex(real, imag)
    # Sigma = F + i*F has star(Sigma)=-i Sigma.
    sigma = add_forms(unconstrained_five, scale_form(hodge_star(unconstrained_five), 1j))
    sigma_dag = {indices: np.conjugate(value) for indices, value in sigma.items()}
    return phi, sigma_dag, sigma


def deterministic_dense(seed: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    phi, sigma_dag, sigma = deterministic_forms(seed)
    return (
        dense_antisymmetric(phi, 4),
        dense_antisymmetric(sigma_dag, 5),
        dense_antisymmetric(sigma, 5),
    )


def integer_value(value: complex) -> int:
    if abs(value.imag) > 1e-6:
        raise AssertionError(f"expected real invariant, got {value}")
    nearest = round(value.real)
    if abs(value.real - nearest) > 1e-6:
        raise AssertionError(f"expected integer invariant, got {value}")
    return int(nearest)


def witness_matrix() -> list[list[int]]:
    rows: list[list[int]] = []
    for seed in WITNESS_SEEDS:
        phi, sigma_dag, sigma = deterministic_dense(seed)
        values = selected_contractions(phi, phi, sigma_dag, sigma)
        rows.append([integer_value(value) for value in values])
    return rows


def bareiss_determinant(matrix: list[list[int]]) -> int:
    a = [row[:] for row in matrix]
    n = len(a)
    if any(len(row) != n for row in a):
        raise ValueError("matrix must be square")
    sign = 1
    denominator = 1
    for pivot_index in range(n - 1):
        if a[pivot_index][pivot_index] == 0:
            swap = next(
                (row for row in range(pivot_index + 1, n) if a[row][pivot_index]),
                None,
            )
            if swap is None:
                return 0
            a[pivot_index], a[swap] = a[swap], a[pivot_index]
            sign *= -1
        pivot = a[pivot_index][pivot_index]
        for row in range(pivot_index + 1, n):
            for column in range(pivot_index + 1, n):
                numerator = a[row][column] * pivot - a[row][pivot_index] * a[pivot_index][column]
                if numerator % denominator:
                    raise ArithmeticError("Bareiss division was not exact")
                a[row][column] = numerator // denominator
        denominator = pivot
        for row in range(pivot_index + 1, n):
            a[row][pivot_index] = 0
    return sign * a[-1][-1]


def infinitesimal_invariance_residual() -> float:
    phi_form, sigma_dag_form, sigma_form = deterministic_forms(1)
    phi = dense_antisymmetric(phi_form, 4)
    sigma_dag = dense_antisymmetric(sigma_dag_form, 5)
    sigma = dense_antisymmetric(sigma_form, 5)
    maximum = 0.0
    for a, b in itertools.combinations(range(N), 2):
        dphi = dense_antisymmetric(generator_action(phi_form, a, b), 4)
        dsigma_dag = dense_antisymmetric(generator_action(sigma_dag_form, a, b), 5)
        dsigma = dense_antisymmetric(generator_action(sigma_form, a, b), 5)
        for edges in SELECTED_EDGES:
            variation = (
                contraction(edges, dphi, phi, sigma_dag, sigma)
                + contraction(edges, phi, dphi, sigma_dag, sigma)
                + contraction(edges, phi, phi, dsigma_dag, sigma)
                + contraction(edges, phi, phi, sigma_dag, dsigma)
            )
            maximum = max(maximum, abs(variation))
    return float(maximum)


def build_report() -> dict[str, Any]:
    all_graphs = graph_solutions()
    matrix = witness_matrix()
    determinant = bareiss_determinant(matrix)
    rows = census.census(False)
    multiplicity = census.find_multiplicity(rows, P=2, D=1, Db=1)
    invariance_residual = infinitesimal_invariance_residual()

    checks = {
        "live_character_multiplicity_is_six": multiplicity == 6,
        "exactly_fifteen_delta_graphs": len(all_graphs) == 15,
        "selected_graphs_are_valid": all(edges in all_graphs for edges in SELECTED_EDGES),
        "six_selected_graphs": len(SELECTED_EDGES) == 6,
        "exact_witness_determinant_matches": determinant == EXPECTED_WITNESS_DETERMINANT,
        "exact_witness_determinant_nonzero": determinant != 0,
        "all_45_generator_variations_vanish": invariance_residual < 1e-9,
        "whole_model_not_overclaimed": True,
    }
    checks = {name: bool(value) for name, value in checks.items()}
    failures = [name for name, passed in checks.items() if not passed]
    return {
        "status": (
            "EXACT_PHI2_126DAG126_SIX_CONTRACTION_BASIS_COMPLETE"
            if not failures
            else "EXACT_PHI2_126DAG126_CONTRACTION_GATE_FAILED"
        ),
        "overall_state": "BLOCKED",
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "checks": checks,
        "operator": "210_H^2 126bar_H^dag 126bar_H",
        "live_character_multiplicity": multiplicity,
        "invariant_theory": {
            "fundamental_SO10_invariant_tensors": ["delta", "epsilon"],
            "chirality_reduction": (
                "epsilon acting on a chiral five-form is Hodge star = +/-i; "
                "therefore epsilon contractions reduce to delta contractions"
            ),
            "all_delta_graph_count": len(all_graphs),
            "all_delta_graph_edges": [list(row) for row in all_graphs],
        },
        "selected_basis": [
            {
                "id": f"G{index + 1}",
                "edge_multiplicities": list(edges),
                "einsum": graph_subscript(edges),
            }
            for index, edges in enumerate(SELECTED_EDGES)
        ],
        "exact_independence_witness": {
            "seeds": list(WITNESS_SEEDS),
            "matrix": matrix,
            "determinant": determinant,
            "expected_determinant": EXPECTED_WITNESS_DETERMINANT,
        },
        "covariance": {
            "generators_checked": 45,
            "maximum_infinitesimal_variation_abs": invariance_residual,
        },
        "closure": {
            "complete_six_invariant_tensor_basis_closed": not failures,
            "all_64_live_G1_tensor_directions_closed": False,
            "G1_closed": False,
            "G2_closed": False,
        },
        "flags": {
            "CG_coefficients_invented": False,
            "external_CG_table_required": False,
            "whole_model_validated": False,
            "whole_model_excluded": False,
            "empirical_discovery": False,
        },
        "next_exact_target": (
            "Map each of the six graph contractions to the canonical irreps "
            "1,45,210,770,5940,8910 and insert common-normalized operators into G2."
        ),
        "verdict": (
            "The 210_H^2 126bar_H^dag 126bar_H family has an explicit complete "
            "six-contraction Cartesian basis. Exact multiplicity six plus the "
            "nonzero integer determinant proves completeness. G1 remains open for "
            "the other live families and for cross-family normalization."
        ),
    }


def write_report(report: dict[str, Any]) -> None:
    OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    OUT_MD.write_text(
        "# Exact Phi^2 126dag126 six-contraction basis — v20\n\n"
        f"**Status:** `{report['status']}`\n\n"
        + report["verdict"]
        + "\n\n"
        + f"**Exact determinant:** `{report['exact_independence_witness']['determinant']}`\n\n"
        + f"**Next:** {report['next_exact_target']}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    report = build_report()
    if args.write:
        write_report(report)
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
