#!/usr/bin/env python3
"""Full 10_H component Hessian on the verified fixed GUT background.

The previous gate closed only the neutral H_u^0,H_d^0,S,Phi17 subspace.
This module adds all twenty real components of the complex SO(10) vector H.
It derives the positive colour projector generated by the singlet and 54
channels of 210_H^2 10_H^dag 10_H on the normalized Pati-Salam p background.

The benchmark is a fixed-GUT-background calculation: the 210 and 126bar
backgrounds are not varied here.  It proves positivity of every H10 component
modulo the three electroweak gauge Goldstones and the physical PQ zero, but it
does not yet prove simultaneous GUT-background stationarity or the complete
210+126bar+10+S+Phi17 Hessian.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import numpy as np

import direct_phi_h_sigmabar_tensor_v20 as direct
import exact_neutral_h10_s_phi17_hessian_v20 as neutral

ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "EXACT_FULL_H10_FIXED_GUT_HESSIAN_V20.json"


def vector_generator_matrix(a: int, b: int) -> np.ndarray:
    matrix = np.zeros((10, 10), dtype=float)
    for column in range(10):
        action = direct.generator_action(direct.one_form(column), a, b)
        for (row,), value in action.items():
            if abs(value.imag) > 1.0e-13:
                raise AssertionError("real vector generator acquired imaginary entry")
            matrix[row, column] = float(value.real)
    return matrix


def p_background_channel_operators() -> dict[str, Any]:
    p = direct.singlet_basis()["p"]
    contraction = np.zeros((10, 10), dtype=float)
    for i in range(10):
        left = direct.interior(p, i)
        for j in range(10):
            value = direct.tensor_inner(left, direct.interior(p, j))
            contraction[i, j] = float(np.real_if_close(value).real)

    trace = float(np.trace(contraction))
    q54 = contraction - (trace / 10.0) * np.eye(10)
    q_weak = float(np.mean(np.diag(q54)[6:10]))
    colour_projector = q_weak * np.eye(10) - q54
    colour_projector = 0.5 * (colour_projector + colour_projector.T)

    p_wedge_p = direct.wedge(p, p)
    adjoint_45 = direct.hodge_star(p_wedge_p)

    unbroken = [
        vector_generator_matrix(a, b)
        for a in range(10)
        for b in range(a + 1, 10)
        if (a < 6 and b < 6) or (a >= 6 and b >= 6)
    ]
    commutator_residual = max(
        float(np.max(np.abs(generator @ colour_projector - colour_projector @ generator)))
        for generator in unbroken
    )

    eigenvalues = np.linalg.eigvalsh(colour_projector)
    return {
        "p_norm": direct.tensor_norm(p),
        "interior_contraction": contraction.tolist(),
        "interior_trace": trace,
        "q54": q54.tolist(),
        "q54_trace": float(np.trace(q54)),
        "q54_colour_eigenvalue": float(np.mean(np.diag(q54)[:6])),
        "q54_weak_eigenvalue": q_weak,
        "colour_projector": colour_projector.tolist(),
        "colour_projector_eigenvalues": [float(x) for x in eigenvalues],
        "colour_projector_rank": int(np.linalg.matrix_rank(colour_projector, 1.0e-12)),
        "colour_projector_idempotence_residual": float(
            np.max(np.abs(colour_projector @ colour_projector - colour_projector))
        ),
        "p_squared_45_wedge_norm": direct.tensor_norm(p_wedge_p),
        "p_squared_45_dual_norm": direct.tensor_norm(adjoint_45),
        "pati_salam_commutator_residual": commutator_residual,
        "normalization": (
            "Q54_ij=<i_i p,i_j p>-(Tr/10)delta_ij; "
            "P_colour=q_weak I-Q54=diag(1_6,0_4)."
        ),
    }


def _add_generator_actions(
    form: direct.Form, terms: tuple[tuple[float, int, int], ...]
) -> direct.Form:
    return direct.add_forms(
        *[
            direct.scale_form(direct.generator_action(form, a, b), coefficient)
            for coefficient, a, b in terms
        ]
    )


def electroweak_tangent_certificate() -> dict[str, Any]:
    # SU(2)_L generators in the repository SO(4) convention.
    generators = {
        "L3": ((0.5, 6, 7), (-0.5, 8, 9)),
        "L1": ((0.5, 6, 8), (0.5, 7, 9)),
        "L2": ((0.5, 6, 9), (-0.5, 7, 8)),
    }
    h0 = direct.one_form(8, 2.0)
    p = direct.singlet_basis()["p"]
    delta = direct.delta_r()

    tangents = []
    rows = {}
    for name, terms in generators.items():
        h_tangent = _add_generator_actions(h0, terms)
        p_tangent = _add_generator_actions(p, terms)
        delta_tangent = _add_generator_actions(delta, terms)
        vector = np.asarray(
            [h_tangent.get((index,), 0.0).real for index in range(10)],
            dtype=float,
        )
        tangents.append(vector)
        rows[name] = {
            "H_tangent": vector.tolist(),
            "P_tangent_norm": direct.tensor_norm(p_tangent),
            "DeltaR_tangent_norm": direct.sigma_kinetic_norm(delta_tangent),
        }
    matrix = np.column_stack(tangents)
    return {
        "generators": rows,
        "H_tangent_rank": int(np.linalg.matrix_rank(matrix, 1.0e-12)),
        "P_invariance_max": max(row["P_tangent_norm"] for row in rows.values()),
        "DeltaR_invariance_max": max(
            row["DeltaR_tangent_norm"] for row in rows.values()
        ),
    }


def parameters() -> dict[str, float]:
    values = neutral.params()
    values["m_colour_squared"] = 5.0
    return values


def full_hessian_benchmark() -> dict[str, Any]:
    p = parameters()
    projector = np.asarray(
        p_background_channel_operators()["colour_projector"], dtype=float
    )
    n = 24
    background = np.zeros(n, dtype=float)
    # H_i=(x_i+i y_i)/sqrt(2); literal <H_8>=v_H.
    background[8] = math.sqrt(2.0) * p["vH"]
    background[20] = p["vS"]
    background[22] = p["vP"]
    variables = [neutral.J.x(value, index, n) for index, value in enumerate(background)]
    x = variables[:10]
    y = variables[10:20]
    s_r, s_i, phi_r, phi_i = variables[20:]

    h_norm = sum(
        0.5 * (x_i.sq() + y_i.sq()) for x_i, y_i in zip(x, y)
    )
    y_re = sum(
        0.5 * (x_i.sq() - y_i.sq()) for x_i, y_i in zip(x, y)
    )
    y_im = sum(x_i * y_i for x_i, y_i in zip(x, y))
    s_norm = 0.5 * (s_r.sq() + s_i.sq())
    phi_norm = 0.5 * (phi_r.sq() + phi_i.sq())
    mu = math.sqrt(2.0) * p["vH"] ** 2 / p["vS"]
    f_re = y_re - (mu / math.sqrt(2.0)) * s_r
    f_im = y_im + (mu / math.sqrt(2.0)) * s_i

    colour_lift = neutral.J.c(0.0, n)
    for i in range(10):
        for j in range(10):
            coefficient = 0.5 * p["m_colour_squared"] * projector[i, j]
            if coefficient:
                colour_lift = colour_lift + coefficient * (
                    x[i] * x[j] + y[i] * y[j]
                )

    potential = (
        p["lX"] * (h_norm - p["vH"] ** 2).sq()
        + p["lA"] * (h_norm.sq() - y_re.sq() - y_im.sq())
        + p["lF"] * (f_re.sq() + f_im.sq())
        + p["lS"] * (s_norm - p["vS"] ** 2 / 2.0).sq()
        + p["lP"] * (phi_norm - p["vP"] ** 2 / 2.0).sq()
        + 0.5 * p["mP2"] * phi_i.sq()
        + colour_lift
    )
    hessian = 0.5 * (potential.h + potential.h.T)
    eigenvalues, eigenvectors = np.linalg.eigh(hessian)
    tolerance = 1.0e-9

    gauge = np.zeros((24, 3), dtype=float)
    gauge[6, 0] = 1.0
    gauge[7, 1] = 1.0
    gauge[9, 2] = 1.0
    pq = np.zeros(24, dtype=float)
    pq[18] = -2.0 * math.sqrt(2.0) * p["vH"]
    pq[21] = 4.0 * p["vS"]
    pq /= np.linalg.norm(pq)

    symmetry_basis, _ = np.linalg.qr(np.column_stack([gauge, pq]))
    null_vectors = eigenvectors[:, np.abs(eigenvalues) <= tolerance]
    null_alignment = float(
        np.max(
            np.abs(
                null_vectors @ null_vectors.T
                - symmetry_basis @ symmetry_basis.T
            )
        )
    )

    # Quotient only the three gauge directions, retaining the physical PQ mode.
    _, _, vh = np.linalg.svd(gauge.T, full_matrices=True)
    complement = vh[3:].T
    quotient_eigenvalues = np.linalg.eigvalsh(complement.T @ hessian @ complement)

    real_indices = list(range(10)) + [20, 22]
    imaginary_indices = list(range(10, 20)) + [21, 23]
    cross_residual = float(
        np.max(np.abs(hessian[np.ix_(real_indices, imaginary_indices)]))
    )

    return {
        "coordinates": [
            *[f"x_{i}" for i in range(10)],
            *[f"y_{i}" for i in range(10)],
            "s_r",
            "s_i",
            "phi_r",
            "phi_i",
        ],
        "parameters": {**p, "mu": mu},
        "gradient_max": float(np.max(np.abs(potential.g))),
        "hessian_eigenvalues": [float(value) for value in eigenvalues],
        "zero_modes": int(np.count_nonzero(np.abs(eigenvalues) <= tolerance)),
        "negative_modes": int(np.count_nonzero(eigenvalues < -tolerance)),
        "minimum_positive_eigenvalue": float(
            np.min(eigenvalues[eigenvalues > tolerance])
        ),
        "symmetry": {
            "gauge_rank": int(np.linalg.matrix_rank(gauge)),
            "gauge_residual": float(np.max(np.abs(hessian @ gauge))),
            "PQ_residual": float(np.max(np.abs(hessian @ pq))),
            "null_alignment_residual": null_alignment,
        },
        "gauge_quotient": {
            "dimension": int(complement.shape[1]),
            "eigenvalues": [float(value) for value in quotient_eigenvalues],
            "zero_modes": int(
                np.count_nonzero(np.abs(quotient_eigenvalues) <= tolerance)
            ),
            "negative_modes": int(
                np.count_nonzero(quotient_eigenvalues < -tolerance)
            ),
            "remaining_zero": "PQ",
        },
        "CP_even_odd_cross_residual": cross_residual,
        "bounded_for_fixed_GUT_background": True,
        "boundedness_argument": (
            "Every term is a nonnegative square, lambda_A[(HdagH)^2-|H.H|^2] "
            "is nonnegative by Cauchy, and m_colour^2 Hdag P_colour H is "
            "positive semidefinite."
        ),
        "spectrum_clusters": {
            "zero_gauge_plus_PQ": 4,
            "phi17_phase": 1,
            "colour_real": 6,
            "weak_CP_odd_transverse": 3,
            "colour_imaginary": 6,
            "neutral_radial_and_phase_positive": 4,
        },
    }


def build_report() -> dict[str, Any]:
    channels = p_background_channel_operators()
    gauge = electroweak_tangent_certificate()
    point = full_hessian_benchmark()
    eigs = np.asarray(point["hessian_eigenvalues"])
    checks = {
        "normalized_p_background": abs(channels["p_norm"] - 1.0) < 1.0e-12,
        "q54_traceless": abs(channels["q54_trace"]) < 1.0e-12,
        "colour_projector_rank_six": channels["colour_projector_rank"] == 6,
        "colour_projector_exact": channels[
            "colour_projector_idempotence_residual"
        ]
        < 1.0e-12,
        "colour_projector_spectrum": np.max(
            np.abs(
                np.sort(channels["colour_projector_eigenvalues"])
                - np.asarray([0.0] * 4 + [1.0] * 6)
            )
        )
        < 1.0e-12,
        "p_squared_45_background_null": channels["p_squared_45_dual_norm"]
        < 1.0e-12,
        "pati_salam_covariance": channels["pati_salam_commutator_residual"]
        < 1.0e-12,
        "three_electroweak_tangents": gauge["H_tangent_rank"] == 3,
        "GUT_background_SU2L_invariant": max(
            gauge["P_invariance_max"], gauge["DeltaR_invariance_max"]
        )
        < 1.0e-12,
        "stationary_in_H_S_Phi17_subspace": point["gradient_max"] < 1.0e-12,
        "four_expected_zeros": point["zero_modes"] == 4,
        "no_tachyons": point["negative_modes"] == 0,
        "gauge_and_PQ_alignment": point["symmetry"]["null_alignment_residual"]
        < 1.0e-10,
        "three_gauge_directions_annihilated": point["symmetry"][
            "gauge_residual"
        ]
        < 1.0e-12,
        "PQ_direction_annihilated": point["symmetry"]["PQ_residual"]
        < 1.0e-12,
        "one_PQ_zero_after_gauge_quotient": point["gauge_quotient"][
            "zero_modes"
        ]
        == 1,
        "no_quotient_tachyons": point["gauge_quotient"]["negative_modes"] == 0,
        "CP_blocks_decouple": point["CP_even_odd_cross_residual"] < 1.0e-12,
        "full_backreaction_not_claimed": True,
    }
    failures = [name for name, passed in checks.items() if not passed]
    return {
        "status": (
            "FULL_H10_FIXED_GUT_HESSIAN_CLOSED__BACKREACTION_OPEN"
            if not failures
            else "FULL_H10_FIXED_GUT_HESSIAN_FAILED"
        ),
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "checks": checks,
        "p_background_channels": channels,
        "electroweak_gauge_certificate": gauge,
        "benchmark": point,
        "flag": {
            "all_20_real_H10_components_included": not failures,
            "three_electroweak_goldstones_identified": not failures,
            "PQ_zero_after_gauge_quotient": not failures,
            "fixed_GUT_background_H10_hessian_complete": not failures,
            "simultaneous_210_126bar_10_S_Phi17_stationarity": False,
            "full_backreacted_multifield_hessian": False,
            "global_vacuum_proved": False,
            "whole_model_validated": False,
            "empirical_discovery": False,
        },
        "verdict": (
            "On the verified fixed P+DeltaR background, an exact singlet-54 "
            "combination gives P_colour=diag(1_6,0_4). The complete 20-real "
            "H10 plus S/Phi17 Hessian is positive apart from three electroweak "
            "gauge Goldstones and the PQ zero. GUT-field backreaction remains open."
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", type=Path, default=OUT_JSON)
    args = parser.parse_args(argv)
    report = build_report()
    text = json.dumps(report, indent=2, sort_keys=True) + "\n"
    args.json.write_text(text, encoding="utf-8")
    print(text, end="")
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
