#!/usr/bin/env python3
"""Exact five-amplitude stationary-equality theorem for the physical-SM target.

Restrict the frozen physical-SM renormalizable witness to real rescalings of
the five nonzero field blocks,

    (Phi, H, Sigma, S, Phi17) = (p Phi*, h H*, d Sigma*, s S*, x Phi17*).

Every contributing invariant is homogeneous in these five amplitudes.  The
exact rational source table below therefore gives the restriction without
sampling or polynomial fitting.  Over QQ, the ideal generated by the five
slice derivatives and ``V+1`` has reduced Groebner basis

    p-1, h^2-1, d^2-1, s^2-1, x^2-1.

Consequently the only slice-stationary equality points are the sixteen real
sign variants with p=1.  The active witness is even in H, Sigma, S and Phi17,
so these are exact discrete sign symmetries of this witness.  This theorem
does not identify them as one orbit of the declared continuous symmetry and
does not classify equality points outside the five-amplitude slice.  It does
not close physical G3, G4, or G5.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from fractions import Fraction
from pathlib import Path
from typing import Any, Iterable

import sympy as sp


ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "EXACT_PHYSICAL_SM_FIVE_AMPLITUDE_EQUALITY_V20.json"
OUT_MD = ROOT / "EXACT_PHYSICAL_SM_FIVE_AMPLITUDE_EQUALITY_V20.md"

SCHEMA = "exact_physical_sm_five_amplitude_equality_v20"
STATUS = "EXACT_FIVE_AMPLITUDE_STATIONARY_EQUALITY_CLASSIFIED__FULL_486_ORBIT_OPEN"
MODEL_CONTRACT_ID = "gauged_u1x_phi17_v20"
FOUNDATION_CORE_SHA256 = "01f565d3382756bc467bfaa99d187188bc1bfc4060f2c3a472650f5e57537e80"

SOURCE_HASHES = {
    "physical_sm_vacuum_local_feasibility_v20.py": "629ea8c45f101f82b6b4e963fd1fb19dcc5735fe52a1d8efb1fb0812dbaa565c",
    "PHYSICAL_SM_VACUUM_LOCAL_FEASIBILITY_V20.json": "ac575067550472afeae1d87503c04a47bf27386223a4417cf7c2341ad75af315",
    "live_g2_arbitrary_component_potential_values_v20.py": "3c868c724c67ee012fa819400924d1c50864e5d9da0392e1ce3c7f9f013e7506",
    "gauged_u1x_g2_derivative_audit_v20.py": "584e03994ca1187228377c3e4c145d95446ade50616e2d58068e0fee9f96507d",
    "live_g1_tensor_closure_ledger_v20.py": "e17dd3a443ddd04ab412844f8d4273c27322371518bbc805705be9c030287d57",
    "direct_phi_h_sigmabar_tensor_v20.py": "3a87470a06362a2a4c05eac6b71fe9cd4cd6c9b8a41732786184cbfeae89fac4",
    "exact_h10_self_quartic_family_v20.py": "a6a54818fce5a98b9e06d657581bb43482eb63a8598860840bc2553060b3f94e",
    "exact_210_self_invariant_basis_v20.py": "663747aa896d8609a0a12fb0bbf5374520ef4fc3a205b6525cbba66022654ae5",
    "exact_p_delta_second_stage_hessian_v20.py": "6f03a6305c9a302d6a1664c3100d1f629bd8af08ac303e5766d6ae463d35dc58",
    "exact_126bar_self_quartic_basis_v20.py": "6b945b21b991ad1c055e7ae39190bcbb258fd8503c1ad37789003310041ddd30",
    "exact_hsigma_hermitian_family_closure_v20.py": "1d27e3a089fd7b4e44f3534eb91c58a1505c8396ddc6301df6df87d07cac9863",
    "exact_phi2_126dag126_six_contractions_v20.py": "78bd1110530be968ab2e62d150c73def74fe96d1d1100ccfb88cb9c4710a6dba",
    "exact_phisigma_126bar_minus_projectors_v20.py": "35574f536dd6a5a6619075784324d3a8e5965544dd91fdca5ce2ce3de6bb2af7",
    "exact_phi2_hdagh_channel_family_v20.py": "42f347e5d8cb8d378f737425d7b152cc71e678627b8a2128b8faba0ce41261cf",
}

# (parameter id, amplitude exponents p,h,d,s,x, exact normalized coupling,
#  exact invariant value at the target).  Zero target values are omitted;
#  all 28 remaining entries are retained before like monomials are combined.
SOURCE_CONTRIBUTIONS = (
    ("lambda::O03_B01_singlet_polynomial", (0, 0, 0, 0, 2), "-89207490960/210003444253", "1/2"),
    ("lambda::O04_B01_singlet_polynomial", (0, 0, 0, 2, 0), "-7826687400/210003444253", "1/50"),
    ("lambda::O05_B01_126bar_norm", (0, 0, 2, 0, 0), "11015601260/210003444253", "1/50"),
    ("lambda::O06_B01_Hdag_H_norm", (0, 2, 0, 0, 0), "-153934744950/210003444253", "1"),
    ("lambda::O07_B01_Phi_norm", (2, 0, 0, 0, 0), "-1107212577224/1050017221265", "1"),
    ("lambda::O14_B01_Phi_Sigma_Sigmadag_cubic", (1, 0, 2, 0, 0), "-4483045420/210003444253", "1/25"),
    ("lambda::O20_B01_singlet_polynomial", (0, 0, 0, 0, 4), "26520070500/210003444253", "1/4"),
    ("lambda::O22_B01_singlet_polynomial", (0, 0, 0, 2, 2), "-471540300/210003444253", "1/100"),
    ("lambda::O23_B01_singlet_polynomial", (0, 0, 0, 4, 0), "262509061500/210003444253", "1/2500"),
    ("lambda::O25_B01_126bar_norm", (0, 0, 2, 0, 2), "-1177316700/210003444253", "1/100"),
    ("lambda::O26_B01_126bar_norm", (0, 0, 2, 2, 0), "121684500/210003444253", "1/2500"),
    ("lambda::O27_B03_126bar_self_projectors", (0, 0, 4, 0, 0), "263008662000/210003444253", "1/2500"),
    ("lambda::O33_B01_Hdag_H_norm", (0, 2, 0, 0, 2), "45394307700/210003444253", "1/2"),
    ("lambda::O34_B01_Hdag_H_norm", (0, 2, 0, 2, 0), "-903665700/210003444253", "1/50"),
    ("lambda::O35_B01_H_Sigma_hermitian", (0, 2, 2, 0, 0), "16325379000/210003444253", "1/50"),
    ("lambda::O35_B02_H_Sigma_hermitian", (0, 2, 2, 0, 0), "-20192346300/210003444253", "1/50"),
    ("lambda::O36_B02_H_self_quartics", (0, 4, 0, 0, 0), "39889411800/210003444253", "1"),
    ("lambda::O42_B01_Phi_norm", (2, 0, 0, 0, 2), "17326089900/210003444253", "1/2"),
    ("lambda::O43_B01_Phi_norm", (2, 0, 0, 2, 0), "-1536672900/210003444253", "1/50"),
    ("lambda::O44_B01_Phi2_Sigma_projectors", (2, 0, 2, 0, 0), "5851780200/210003444253", "1/1050"),
    ("lambda::O44_B04_Phi2_Sigma_projectors", (2, 0, 2, 0, 0), "37366736400/210003444253", "-1/375"),
    ("lambda::O44_B06_Phi2_Sigma_projectors", (2, 0, 2, 0, 0), "-39819378900/210003444253", "3/1750"),
    ("lambda::O46_B01_Phi2_HdagH_channels", (2, 2, 0, 0, 0), "57854223000/210003444253", "1"),
    ("lambda::O46_B03_Phi2_HdagH_channels", (2, 2, 0, 0, 0), "-10500071400/210003444253", "3/5"),
    ("lambda::O48_B01_Phi_self_quartics", (4, 0, 0, 0, 0), "47581800/210003444253", "1"),
    ("lambda::O48_B02_Phi_self_quartics", (4, 0, 0, 0, 0), "173733000/210003444253", "24"),
    ("lambda::O48_B03_Phi_self_quartics", (4, 0, 0, 0, 0), "-2747637900/210003444253", "192"),
    ("lambda::O48_B04_Phi_self_quartics", (4, 0, 0, 0, 0), "170068500/210003444253", "3552"),
)

# Active witness rows whose invariant happens to vanish at the target.  They
# do not enter the restricted polynomial coefficient table, but their parity
# is required before calling the sixteen solutions exact sign symmetries of
# the *full selected witness* rather than an accident of target evaluation.
ZERO_TARGET_SUPPORT = (
    ("lambda::O17_B01_Phi_cubic", (3, 0, 0, 0, 0)),
    ("lambda::O27_B01_126bar_self_projectors", (0, 0, 4, 0, 0)),
    ("lambda::O27_B02_126bar_self_projectors", (0, 0, 4, 0, 0)),
    ("lambda::O27_B04_126bar_self_projectors", (0, 0, 4, 0, 0)),
    ("lambda::O36_B01_H_self_quartics", (0, 4, 0, 0, 0)),
    ("lambda::O44_B02_Phi2_Sigma_projectors", (2, 0, 2, 0, 0)),
    ("lambda::O44_B03_Phi2_Sigma_projectors", (2, 0, 2, 0, 0)),
    ("lambda::O44_B05_Phi2_Sigma_projectors", (2, 0, 2, 0, 0)),
    ("lambda::O46_B02_Phi2_HdagH_channels", (2, 2, 0, 0, 0)),
)

EXPECTED_DENOMINATOR = 1_050_017_221_265
EXPECTED_NUMERATOR = (
    "526017324*d**4 - 386696730*d**2*h**2 - 811666494*d**2*p**2 "
    "- 896609084*d**2*p + 243369*d**2*s**2 - 58865835*d**2*x**2 "
    "+ 1101560126*d**2 + 199447059000*h**4 + 257770900800*h**2*p**2 "
    "- 90366570*h**2*s**2 + 113485769250*h**2*x**2 - 769673724750*h**2 "
    "+ 403770045000*p**4 - 153667290*p**2*s**2 + 43315224750*p**2*x**2 "
    "- 1107212577224*p**2 + 525018123*s**4 - 23577015*s**2*x**2 "
    "- 782668740*s**2 + 33150088125*x**4 - 223018727400*x**2"
)


def _jsonable(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    if isinstance(value, Fraction):
        return str(value)
    if isinstance(value, sp.Basic):
        return str(value)
    return value


def canonical_json_bytes(value: Any) -> bytes:
    return (json.dumps(_jsonable(value), sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def _portable_lf_sha256(path: Path) -> str:
    """Hash text dependencies after canonical CRLF/CR-to-LF normalization."""
    payload = path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    return hashlib.sha256(payload).hexdigest()


def source_bindings() -> dict[str, Any]:
    bindings: dict[str, Any] = {}
    for name, expected in SOURCE_HASHES.items():
        path = ROOT / name
        if not path.is_file():
            raise FileNotFoundError(f"five-amplitude source dependency missing: {name}")
        observed = _portable_lf_sha256(path)
        if observed != expected:
            raise ArithmeticError(f"five-amplitude source dependency drifted: {name}")
        bindings[name] = {
            "portable_lf_sha256": observed,
            "expected_portable_lf_sha256": expected,
            "matches": True,
        }
    foundation = json.loads((ROOT / "PHYSICAL_SM_VACUUM_LOCAL_FEASIBILITY_V20.json").read_text(encoding="utf-8"))
    core = foundation.get("integrity", {}).get("core_sha256")
    if core != FOUNDATION_CORE_SHA256:
        raise ArithmeticError("physical-SM foundation core drifted")
    return {
        "files": bindings,
        "foundation_core_sha256": core,
        "expected_foundation_core_sha256": FOUNDATION_CORE_SHA256,
        "all_portable_lf_and_core_pins_match": True,
    }


def symbols() -> tuple[sp.Symbol, ...]:
    return sp.symbols("p h d s x")


def exact_slice_potential(
    contributions: Iterable[tuple[str, tuple[int, ...], str, str]] = SOURCE_CONTRIBUTIONS,
) -> sp.Expr:
    variables = symbols()
    result = sp.S.Zero
    for _parameter_id, exponents, coefficient, target_value in contributions:
        if len(exponents) != len(variables) or any(int(value) < 0 for value in exponents):
            raise ArithmeticError("invalid five-amplitude exponent row")
        result += sp.Rational(coefficient) * sp.Rational(target_value) * sp.prod(
            variable ** int(exponent)
            for variable, exponent in zip(variables, exponents, strict=True)
        )
    combined = sp.together(result)
    numerator, denominator = sp.fraction(combined)
    expected = sp.sympify(EXPECTED_NUMERATOR, locals=dict(zip(("p", "h", "d", "s", "x"), variables, strict=True)))
    if denominator != EXPECTED_DENOMINATOR or sp.expand(numerator - expected) != 0:
        raise ArithmeticError("exact five-amplitude source table drifted")
    return combined


def _primitive_integer_polynomial(expression: sp.Expr) -> sp.Expr:
    polynomial = sp.Poly(expression, *symbols(), domain=sp.QQ)
    return sp.expand(polynomial.clear_denoms()[1].primitive()[1].as_expr())


def exact_groebner_certificate() -> dict[str, Any]:
    variables = symbols()
    potential = exact_slice_potential()
    generators = tuple(
        _primitive_integer_polynomial(sp.diff(potential, variable))
        for variable in variables
    ) + (_primitive_integer_polynomial(potential + 1),)
    basis = sp.groebner(generators, *variables, order="grevlex", method="f5b")
    observed_basis = tuple(sp.expand(row.as_expr()) for row in basis.polys)
    p, h, d, s, x = variables
    expected_basis = (h**2 - 1, d**2 - 1, s**2 - 1, x**2 - 1, p - 1)
    expected_ideal = sp.groebner(expected_basis, *variables, order="grevlex")
    source_remainders = tuple(expected_ideal.reduce(row)[1] for row in generators)
    reverse_remainders = tuple(basis.reduce(row)[1] for row in expected_basis)
    mutual_containment = all(row == 0 for row in source_remainders + reverse_remainders)
    target = {variable: 1 for variable in variables}
    hessian = sp.hessian(potential, variables).subs(target)
    leading_principal_minors = tuple(sp.factor(hessian[:size, :size].det()) for size in range(1, 6))
    return {
        "coefficient_domain": "QQ",
        "monomial_order": "grevlex",
        "variables": [str(value) for value in variables],
        "source_generator_count": len(generators),
        "source_generators": [str(sp.factor(value)) for value in generators],
        "reduced_Groebner_basis": [str(value) for value in observed_basis],
        "expected_reduced_Groebner_basis": [str(value) for value in expected_basis],
        "observed_basis_equals_expected": observed_basis == expected_basis,
        "source_ideal_contained_in_expected_ideal": all(row == 0 for row in source_remainders),
        "expected_ideal_contained_in_source_ideal": all(row == 0 for row in reverse_remainders),
        "ideals_equal_by_mutual_exact_reduction": mutual_containment,
        "ideal_zero_dimensional": bool(basis.is_zero_dimensional),
        "ideal_is_radical_from_squarefree_separated_basis": True,
        "complex_solution_count_with_multiplicity": 16,
        "all_solutions_real": True,
        "solution_set": "p=1; h,d,s,x independently in {-1,+1}",
        "target_slice_Hessian_leading_principal_minors": [str(value) for value in leading_principal_minors],
        "target_slice_Hessian_positive_definite": all(value > 0 for value in leading_principal_minors),
    }


def _core_payload(report: dict[str, Any]) -> dict[str, Any]:
    return {
        key: report[key]
        for key in (
            "schema",
            "status",
            "model_contract_id",
            "source_bindings",
            "restriction",
            "exact_polynomial",
            "exact_Groebner_certificate",
            "discrete_variants",
            "closure_claims",
            "remaining_scope",
        )
    }


def build_report() -> dict[str, Any]:
    bindings = source_bindings()
    potential = exact_slice_potential()
    numerator, denominator = sp.fraction(potential)
    polynomial = sp.Poly(potential, *symbols(), domain=sp.QQ)
    groebner = exact_groebner_certificate()
    full_support_exponents = tuple(
        (parameter_id, exponents)
        for parameter_id, exponents, _coefficient, _target_value in SOURCE_CONTRIBUTIONS
    ) + ZERO_TARGET_SUPPORT
    independent_sign_even = all(
        all(exponents[index] % 2 == 0 for index in range(1, 5))
        for _parameter_id, exponents in full_support_exponents
    )
    claims = {
        "exact_radial_theorem_strictly_extended": True,
        "five_real_amplitude_slice_stationary_equality_classified": True,
        "full_486_field_stationary_equality_classified": False,
        "declared_continuous_symmetry_orbit_equivalence_of_16_variants_proved": False,
        "direct_source_algebra_full_486_Hessian_available": False,
        "physical_SM_G3_closed": False,
        "physical_SM_G4_closed": False,
        "physical_SM_G5_closed": False,
    }
    checks = {
        "all_source_portable_lf_and_core_pins_match": bindings["all_portable_lf_and_core_pins_match"],
        "source_table_has_28_nonzero_target_contributions": len(SOURCE_CONTRIBUTIONS) == 28,
        "all_37_witness_rows_have_even_H_Sigma_S_Phi17_parity": len(full_support_exponents) == 37 and independent_sign_even,
        "aggregate_polynomial_has_21_monomials": len(polynomial.terms()) == 21,
        "aggregate_denominator_is_frozen": int(denominator) == EXPECTED_DENOMINATOR,
        "exact_target_value_is_minus_one": potential.subs(dict.fromkeys(symbols(), 1)) == -1,
        "all_five_target_slice_derivatives_vanish": all(sp.diff(potential, value).subs(dict.fromkeys(symbols(), 1)) == 0 for value in symbols()),
        "Groebner_basis_is_exact_expected_basis": groebner["observed_basis_equals_expected"],
        "ideals_equal_by_mutual_exact_reduction": groebner["ideals_equal_by_mutual_exact_reduction"],
        "exactly_16_real_discrete_sign_variants": groebner["complex_solution_count_with_multiplicity"] == 16 and groebner["all_solutions_real"],
        "target_is_strict_minimum_on_five_amplitude_slice": groebner["target_slice_Hessian_positive_definite"],
        "full_486_and_physical_G3_G4_G5_remain_fail_closed": not any((claims["full_486_field_stationary_equality_classified"], claims["physical_SM_G3_closed"], claims["physical_SM_G4_closed"], claims["physical_SM_G5_closed"])),
    }
    failures = [name for name, passed in checks.items() if not passed]
    report: dict[str, Any] = {
        "schema": SCHEMA,
        "status": STATUS,
        "model_contract_id": MODEL_CONTRACT_ID,
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "checks": checks,
        "source_bindings": bindings,
        "restriction": {
            "ambient_real_field_dimension": 486,
            "slice_dimension": 5,
            "map": "(Phi,H,Sigma,S,Phi17)=(p Phi*,h H*,d Sigma*,s S*,x Phi17*)",
            "amplitudes_are_real": True,
            "construction": "exact source invariant values times exact multihomogeneous amplitude monomials",
            "polynomial_fitting_or_float_sampling_used": False,
            "exact_algebra_is_conditional_on_frozen_upstream_witness_table": True,
            "witness_coefficients_origin": "exact rational lattice reconstruction in physical_sm_vacuum_local_feasibility_v20.py",
            "witness_coefficients_directly_derived_from_integer_projector_source_algebra": False,
            "target_invariant_table_is_portable_lf_hash_bound_to_normalized_source_modules": True,
            "target_invariant_table_independently_rederived_by_integer_arithmetic_in_this_artifact": False,
            "renormalizable_witness_nonzero_parameter_count": 37,
            "nonzero_target_contribution_count": len(SOURCE_CONTRIBUTIONS),
        },
        "exact_polynomial": {
            "V_restricted": str(sp.factor(potential)),
            "common_denominator": int(denominator),
            "integer_numerator": str(sp.expand(numerator)),
            "aggregate_monomial_count": len(polynomial.terms()),
            "source_contributions": [
                {
                    "parameter_id": parameter_id,
                    "amplitude_exponents_p_h_d_s_x": list(exponents),
                    "exact_normalized_coupling": coefficient,
                    "exact_target_invariant_value": target_value,
                }
                for parameter_id, exponents, coefficient, target_value in SOURCE_CONTRIBUTIONS
            ],
        },
        "exact_Groebner_certificate": groebner,
        "discrete_variants": {
            "count": 16,
            "description": "p=1 with independent signs of h,d,s,x",
            "full_witness_support_row_count": len(full_support_exponents),
            "zero_at_target_but_parity_checked_row_count": len(ZERO_TARGET_SUPPORT),
            "all_support_rows_even_in_h_d_s_x": independent_sign_even,
            "exact_discrete_sign_symmetries_of_selected_witness": independent_sign_even,
            "full_486_stationarity_inherited_from_upstream_target_under_discrete_sign_symmetry": True,
            "continuous_SO10_x_U1X_x_PQ_orbit_equivalence_classified": False,
            "reason_for_not_calling_one_orbit": "no exact group elements connecting all sixteen variants are supplied here",
        },
        "closure_claims": claims,
        "remaining_scope": [
            "derive the complete 486-real stationary Hessian directly from integer/Gaussian-integer projector algebra",
            "classify stationary equality points with arbitrary non-amplitude field components",
            "classify the sixteen discrete variants under the declared continuous symmetry only with explicit exact group elements",
        ],
    }
    report["integrity"] = {"core_sha256": hashlib.sha256(canonical_json_bytes(_core_payload(report))).hexdigest()}
    return report


def render_markdown(report: dict[str, Any]) -> str:
    certificate = report["exact_Groebner_certificate"]
    return "\n".join(
        [
            "# Exact physical-SM five-amplitude equality theorem — v20",
            "",
            f"**Status:** `{report['status']}`",
            "",
            "For real block amplitudes `(p,h,d,s,x)`, the exact stationary-equality ideal has reduced Gröbner basis",
            "",
            "`p-1, h^2-1, d^2-1, s^2-1, x^2-1`.",
            "",
            f"It therefore has exactly `{certificate['complex_solution_count_with_multiplicity']}` distinct real sign variants. They are exact discrete symmetries of the selected witness; this artifact does not claim that all are one declared continuous-symmetry orbit.",
            "",
            "This strictly extends the radial equality theorem, but arbitrary non-amplitude directions in the 486-real field space remain unclassified. Physical G3, G4 and G5 remain false.",
            "",
            f"Core SHA-256: `{report['integrity']['core_sha256']}`.",
        ]
    ) + "\n"


def write_outputs() -> dict[str, Any]:
    report = build_report()
    OUT_JSON.write_text(json.dumps(_jsonable(report), indent=2) + "\n", encoding="utf-8", newline="\n")
    OUT_MD.write_text(render_markdown(report), encoding="utf-8", newline="\n")
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    report = write_outputs() if args.write else build_report()
    print(json.dumps(_jsonable(report), indent=2))
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
