#!/usr/bin/env python3
"""All-component pure-irrep Phi-Sigma quartic projectors.

This module extends the exact triplet Casimir construction to arbitrary real
210_H four-forms and arbitrary chiral 126bar_H five-forms.  It exposes a public
pure-invariant evaluator for Q=1,45,210,770,5940,8910 and exports the complete
126x126 Hessian matrices generated by a general singlet background
Phi=pP+aA+omegaW.

The projector normalization remains

    ||C_Phi Sigma||^2 = sum_Q I_Q.

The full 126 matrices are saved as quadratic-polynomial coefficient arrays for
p^2,a^2,omega^2,p a,p omega,a omega.  Consequently every Sigma component, not
only the proton-decay triplets, can be evaluated for six independent pure
quartic couplings.

This closes the all-component Clebsch evaluator for the Phi^2 Sigma^dag Sigma
quartic family.  It does not complete the independent 210 self-potential,
other field sectors, the global vacuum, or the physical full Hessian.
"""
from __future__ import annotations

import argparse
import json
from functools import lru_cache
from pathlib import Path
from typing import Any

import numpy as np

import direct_phi_h_sigmabar_tensor_v20 as direct
import exact_126bar_triplet_clebsch_v20 as triplets
import exact_phisigma_casimir_projectors_v20 as projectors

ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "EXACT_PHISIGMA_ALL_COMPONENT_PROJECTORS_V20.json"
OUT_MD = ROOT / "EXACT_PHISIGMA_ALL_COMPONENT_PROJECTORS_V20.md"
OUT_NPZ = ROOT / "EXACT_PHISIGMA_ALL_COMPONENT_PROJECTORS_V20.npz"
CHANNELS = tuple(projectors.COMMON_CHANNEL_EIGENVALUES)
MONOMIALS = projectors.MONOMIALS


def phi_vector(form: direct.Form) -> np.ndarray:
    vector = projectors._form_to_vector(form)
    if np.max(np.abs(vector.imag), initial=0.0) > 1.0e-12:
        raise ValueError("210_H is real in this non-SUSY model")
    return vector.real


def symmetric_phi_pair(left: direct.Form, right: direct.Form) -> np.ndarray:
    left_vector = phi_vector(left)
    right_vector = phi_vector(right)
    return 0.5 * (
        np.outer(left_vector, right_vector)
        + np.outer(right_vector, left_vector)
    )


def projected_phi_pair(
    channel: str, left: direct.Form, right: direct.Form
) -> np.ndarray:
    if channel not in projectors.COMMON_CHANNEL_EIGENVALUES:
        raise KeyError(channel)
    pair = symmetric_phi_pair(left, right)
    powers = projectors.casimir_powers(pair)
    return projectors.project_from_powers(
        powers, projectors.COMMON_CHANNEL_EIGENVALUES[channel]
    )


def sigma_contraction_map(state: direct.Form) -> np.ndarray:
    matrix = np.zeros((10, 210), dtype=complex)
    for column, phi_state in enumerate(projectors.FOUR_BASIS):
        image = direct.contract(phi_state, state)
        for row in range(10):
            matrix[row, column] = image.get((row,), 0.0)
    return matrix


def polarized_C_invariant(
    phi_left: direct.Form,
    phi_right: direct.Form,
    sigma_left: direct.Form,
    sigma_right: direct.Form,
) -> complex:
    first = direct.tensor_inner(
        direct.contract(phi_left, sigma_left),
        direct.contract(phi_right, sigma_right),
    )
    second = direct.tensor_inner(
        direct.contract(phi_right, sigma_left),
        direct.contract(phi_left, sigma_right),
    )
    return 0.5 * (first + second)


def pure_invariant(
    channel: str,
    phi_left: direct.Form,
    phi_right: direct.Form,
    sigma_left: direct.Form,
    sigma_right: direct.Form,
) -> complex:
    pair = projected_phi_pair(channel, phi_left, phi_right)
    kernel = (
        sigma_contraction_map(sigma_left).conj().T
        @ sigma_contraction_map(sigma_right)
    )
    return projectors._evaluate_kernel(pair, kernel)


@lru_cache(maxsize=1)
def sigma_basis() -> tuple[direct.Form, ...]:
    return tuple(triplets._hodge_basis("+i"))


@lru_cache(maxsize=1)
def full_contraction_tensor() -> np.ndarray:
    basis = sigma_basis()
    tensor = np.zeros((10, 210, 126), dtype=complex)
    for phi_index, phi_state in enumerate(projectors.FOUR_BASIS):
        tensor[:, phi_index, :] = direct.contraction_matrix(
            phi_state, list(basis)
        )
    return tensor


def full_sigma_operator(pair: np.ndarray) -> np.ndarray:
    pair = np.asarray(pair, dtype=complex)
    if pair.shape != (210, 210):
        raise ValueError("pair matrix must be 210x210")
    tensor = full_contraction_tensor()
    result = np.zeros((126, 126), dtype=complex)
    for vector_index in range(10):
        block = tensor[vector_index]
        result += block.conj().T @ pair @ block
    return 0.5 * (result + result.conj().T)


@lru_cache(maxsize=1)
def all_component_coefficients() -> dict[str, dict[str, np.ndarray]]:
    projected = projectors.projected_monomials()
    spectral_name = {
        "1": "1",
        "45": "45",
        "210": "210",
        "770": "770_plus_1050_plus_1050bar",
        "5940": "5940",
        "8910": "8910",
    }
    return {
        channel: {
            monomial: full_sigma_operator(
                projected[eigenspace][monomial]
            )
            for monomial in MONOMIALS
        }
        for channel, eigenspace in spectral_name.items()
    }


def evaluate_full_sigma_operator(
    channel: str, p: float, a: float, omega: float
) -> np.ndarray:
    if channel not in CHANNELS:
        raise KeyError(channel)
    values = {
        "p2": p * p,
        "a2": a * a,
        "omega2": omega * omega,
        "p_a": p * a,
        "p_omega": p * omega,
        "a_omega": a * omega,
    }
    coefficients = all_component_coefficients()[channel]
    return sum(
        (values[name] * coefficients[name] for name in MONOMIALS),
        np.zeros((126, 126), dtype=complex),
    )


def _random_form_210(rng: np.random.Generator) -> direct.Form:
    coefficients = rng.normal(size=210)
    coefficients /= np.linalg.norm(coefficients)
    return {
        indices: complex(coefficients[index])
        for index, indices in enumerate(projectors.FOUR_INDICES)
        if abs(coefficients[index]) > 1.0e-14
    }


def _random_form_126(rng: np.random.Generator) -> direct.Form:
    coefficients = rng.normal(size=126) + 1j * rng.normal(size=126)
    coefficients /= np.linalg.norm(coefficients)
    return triplets._form(coefficients, sigma_basis())


def _all_component_reconstruction_audit() -> dict[str, Any]:
    rng = np.random.default_rng(260806)
    phi_left = _random_form_210(rng)
    phi_right = _random_form_210(rng)
    sigma_left = _random_form_126(rng)
    sigma_right = _random_form_126(rng)
    target = polarized_C_invariant(
        phi_left, phi_right, sigma_left, sigma_right
    )
    by_channel = {
        channel: pure_invariant(
            channel, phi_left, phi_right, sigma_left, sigma_right
        )
        for channel in CHANNELS
    }
    reconstructed = sum(by_channel.values())
    return {
        "target": {"re": float(target.real), "im": float(target.imag)},
        "by_channel_abs": {
            channel: float(abs(value))
            for channel, value in by_channel.items()
        },
        "reconstruction_abs_residual": float(abs(reconstructed - target)),
        "minimum_channel_overlap": float(
            min(abs(value) for value in by_channel.values())
        ),
    }


def _projector_covariance_audit() -> float:
    rng = np.random.default_rng(1701)
    left = _random_form_210(rng)
    right = _random_form_210(rng)
    pair = symmetric_phi_pair(left, right)
    powers = projectors.casimir_powers(pair)
    maximum = 0.0
    for generator_index in (0, 7, 23, 44):
        generator = projectors.generator_matrices()[generator_index]
        transformed_pair = (
            generator @ pair
            + (generator @ pair.T).T
        )
        transformed_powers = projectors.casimir_powers(transformed_pair)
        for channel, eigenvalue in projectors.COMMON_CHANNEL_EIGENVALUES.items():
            projected = projectors.project_from_powers(powers, eigenvalue)
            expected = generator @ projected + (generator @ projected.T).T
            observed = projectors.project_from_powers(
                transformed_powers, eigenvalue
            )
            maximum = max(
                maximum, float(np.max(np.abs(observed - expected)))
            )
    return maximum


def _triplet_vectors() -> dict[str, np.ndarray]:
    states = projectors.aligned_triplet_forms()
    basis = sigma_basis()
    result: dict[str, np.ndarray] = {}
    for name, source_name in (
        ("t2", "t2_triplet"),
        ("t2bar", "t2bar_antitriplet"),
        ("t4bar", "t4bar_antitriplet"),
    ):
        state = states[source_name][0]
        result[name] = np.asarray(
            [direct.sigma_kinetic_inner(item, state) for item in basis],
            dtype=complex,
        )
    return result


def _triplet_restriction_residual(
    channel: str, operator: np.ndarray, p: float, a: float, omega: float
) -> float:
    vectors = _triplet_vectors()
    u = np.asarray(
        [[np.vdot(vectors["t2"], operator @ vectors["t2"])]],
        dtype=complex,
    )
    v_basis = np.column_stack((vectors["t2bar"], vectors["t4bar"]))
    v = v_basis.conj().T @ operator @ v_basis
    expected = projectors.evaluate_channel_blocks(channel, p, a, omega)
    return max(
        float(np.max(np.abs(u - expected["A_u_sigma_GeV2"]))),
        float(np.max(np.abs(v - expected["A_v_sigma_GeV2"]))),
    )


def _matrix_summary(matrix: np.ndarray) -> dict[str, Any]:
    eigenvalues = np.linalg.eigvalsh(matrix)
    return {
        "trace": float(np.trace(matrix).real),
        "frobenius_norm": float(np.linalg.norm(matrix)),
        "minimum_eigenvalue": float(eigenvalues[0]),
        "maximum_eigenvalue": float(eigenvalues[-1]),
        "rank_at_1e-10": int(np.sum(np.abs(eigenvalues) > 1.0e-10)),
        "hermiticity_residual": float(
            np.max(np.abs(matrix - matrix.conj().T))
        ),
    }


def build_report() -> dict[str, Any]:
    projector_report = projectors.build_report()
    reconstruction = _all_component_reconstruction_audit()
    covariance = _projector_covariance_audit()
    p, a, omega = 0.9, 0.4, 0.7
    operators = {
        channel: evaluate_full_sigma_operator(channel, p, a, omega)
        for channel in CHANNELS
    }
    total = sum(
        operators.values(), np.zeros((126, 126), dtype=complex)
    )
    phi_basis = direct.singlet_basis()
    phi = direct.add_forms(
        direct.scale_form(phi_basis["p"], p),
        direct.scale_form(phi_basis["a"], a),
        direct.scale_form(phi_basis["omega"], omega),
    )
    direct_matrix = direct.contraction_matrix(phi, list(sigma_basis()))
    expected_total = direct_matrix.conj().T @ direct_matrix
    full_reconstruction = float(
        np.max(np.abs(total - expected_total))
    )
    triplet_residual = max(
        _triplet_restriction_residual(
            channel, operator, p, a, omega
        )
        for channel, operator in operators.items()
    )
    maximum_hermiticity = max(
        float(np.max(np.abs(matrix - matrix.conj().T)))
        for matrix in operators.values()
    )

    projected = projectors.projected_monomials()
    noncommon = {}
    for name, eigenspace in (
        ("54", "54"), ("4125", "4125")
    ):
        operator = sum(
            (
                value
                * full_sigma_operator(
                    projected[eigenspace][monomial]
                )
                for monomial, value in {
                    "p2": p * p,
                    "a2": a * a,
                    "omega2": omega * omega,
                    "p_a": p * a,
                    "p_omega": p * omega,
                    "a_omega": a * omega,
                }.items()
            ),
            np.zeros((126, 126), dtype=complex),
        )
        noncommon[name] = float(np.max(np.abs(operator)))

    coefficients = all_component_coefficients()
    npz_payload = {
        f"Q{channel}_{monomial}": matrix
        for channel, rows in coefficients.items()
        for monomial, matrix in rows.items()
    }
    np.savez_compressed(OUT_NPZ, **npz_payload)

    checks = {
        "triplet_projector_upstream_passes": projector_report["n_failed"] == 0,
        "arbitrary_all_component_invariant_reconstructs_C": reconstruction[
            "reconstruction_abs_residual"
        ]
        < 1.0e-9,
        "all_six_arbitrary_component_overlaps_nonzero": reconstruction[
            "minimum_channel_overlap"
        ]
        > 1.0e-10,
        "projectors_commute_with_pair_generators": covariance < 1.0e-8,
        "full_126_operator_sum_reconstructs_CdagC": full_reconstruction < 1.0e-9,
        "full_operators_restrict_to_exact_triplet_blocks": triplet_residual < 1.0e-9,
        "all_full_operators_hermitian": maximum_hermiticity < 1.0e-10,
        "noncommon_full_54_and_4125_pairings_vanish": max(noncommon.values()) < 1.0e-9,
        "all_36_polynomial_coefficient_matrices_exported": len(npz_payload) == 36,
        "complete_scalar_potential_not_claimed": True,
        "physical_full_Hessian_not_claimed": True,
    }
    failures = [name for name, ok in checks.items() if not ok]
    return {
        "status": (
            "EXACT_PHISIGMA_ALL_COMPONENT_PROJECTORS_DERIVED"
            if not failures
            else "EXACT_PHISIGMA_ALL_COMPONENT_PROJECTORS_FAILED"
        ),
        "overall_state": "CLOSED_SUBPROBLEM" if not failures else "EXECUTION_FAIL",
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "checks": checks,
        "public_evaluator": (
            "pure_invariant(channel, phi_left, phi_right, sigma_left, sigma_right)"
        ),
        "normalization_convention": projectors.build_report()[
            "normalization_convention"
        ],
        "all_component_reconstruction": reconstruction,
        "covariance_max_abs_residual": covariance,
        "full_126_background_certificate": {
            "benchmark": {"p": p, "a": a, "omega": omega},
            "channel_summaries": {
                channel: _matrix_summary(matrix)
                for channel, matrix in operators.items()
            },
            "sum_reconstruction_max_abs_residual": full_reconstruction,
            "triplet_restriction_max_abs_residual": triplet_residual,
            "maximum_hermiticity_residual": maximum_hermiticity,
            "noncommon_max_abs_entries": noncommon,
            "coefficient_archive": OUT_NPZ.name,
            "coefficient_matrix_count": len(npz_payload),
        },
        "newly_closed_subproblem": {
            "arbitrary_component_pure_invariant_evaluator": not failures,
            "all_six_full_126_background_Hessian_matrices": not failures,
            "all_component_PhiSigma_quartic_Clebsch_algorithm": not failures,
        },
        "remaining_blockers": {
            "independent_210_self_potential_channels": True,
            "other_field_sector_all_component_potentials": True,
            "complete_component_scalar_potential": True,
            "unique_gauge_quotiented_vacuum": True,
            "positive_physical_full_Hessian": True,
            "physical_threshold_spectrum": True,
            "component_level_two_loop_matching": True,
            "exact_unique_proton_lifetime": True,
        },
        "flag": {
            "all_PhiSigma_quartic_all_component_Clebsches_complete": not failures,
            "complete_component_potential": False,
            "unique_full_vacuum": False,
            "physical_full_Hessian_complete": False,
            "physical_threshold_spectrum_complete": False,
            "exact_unique_proton_lifetime": False,
            "whole_model_validated": False,
            "whole_model_excluded": False,
            "empirical_discovery": False,
        },
        "verdict": (
            "The six pure PhiSigma quartic invariants now have an arbitrary-"
            "component evaluator and complete 126x126 polynomial Hessian matrices "
            "for a general p,a,omega background. Other scalar sectors and the "
            "physical full vacuum/Hessian remain open."
        ),
    }


def write_markdown(report: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Exact all-component Phi–Sigma projectors — v20",
            "",
            f"**Status:** `{report['status']}`",
            "",
            report["verdict"],
            "",
            "- Public arbitrary-component evaluator is available.",
            "- 36 full `126x126` polynomial coefficient matrices are archived.",
            "- Other scalar sectors and the unique physical Hessian remain open.",
            "",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    argparse.ArgumentParser(description=__doc__).parse_args(argv)
    report = build_report()
    payload = json.dumps(report, indent=2) + "\n"
    OUT_JSON.write_text(payload, encoding="utf-8")
    OUT_MD.write_text(write_markdown(report), encoding="utf-8")
    print(payload, end="")
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
