#!/usr/bin/env python3
"""Effective Higgs quartic at the tuned physical G3 target.

``g3_candidate_physical_target_audit_v20`` shows that the certified G3 point
breaks electroweak symmetry at M_GUT.  Its physical counterpart keeps
(Phi, Sigma, S, Phi17) = (F, r Delta_R, r, 1) and retunes only the H mass
coefficient O06 (-2 -> 0), so one electroweak doublet is exactly massless at
H=0 and v_EW << M can be generated by a small negative doublet mass.  Near
that point the light doublet h has, at tree level,

    V = lambda_eff (h^dag h)^2,
    lambda_eff = lambda_direct - (1/2) sum_a c_a^2 / m_a^2  (per real direction),

where lambda_direct is the pure-H quartic and c_a the trilinear coupling of
|h|^2 to heavy mode a.  Along a unit real chart direction u of the doublet,
with the exact polynomial identities

    c(u) = grad V(q0+u) + grad V(q0-u) - 2 grad V(q0),
    Q(u) = u.(Hess V(q0+u) + Hess V(q0-u) - 2 Hess V(q0)).u,

the normalization is lambda_direct = Q/6 and
lambda_eff = (Q - 3 c.M^+.c)/6.  All derivatives come from the repository's
live 51-parameter exact-X compiler on the 486-real canonical chart.

Results:
* The tuned point is stationary.  Its Hessian is positive semidefinite with
  39 zero modes: 33 SO(10)/SM Goldstones, the U(1)_X and PQ phases, and the
  four real components of the massless doublet.
* The light H spectrum is a massless doublet, its colour-triplet partner at
  beta r^2 = 1/500, and the opposite five-plet at 6/5 and 6/5 - 1/500.
* c vanishes identically, so the light doublet has no tree-level coupling
  to any heavy mode and lambda_eff = lambda_direct = 1.
* One-loop SM running from M_GUT = 1e16 GeV gives m_h ~ 173 GeV; the
  certified coupling point is excluded by the Higgs mass.
* Bounded-below along the pure-H ray needs lambda_direct >= 0.  Without
  heavy-mode feedback that means lambda_eff >= 0, which already gives
  m_h >= 133.6 GeV at one loop.  m_h = 125 GeV needs lambda(M_GUT) ~ -0.034
  at one loop.
* The sufficient H-Sigma BFB certificate (lambda_H > beta^2/(4 t) = 2 beta^2
  at t=1/8) costs only another ~1.2 GeV, so a sharper BFB bound cannot
  close the gap.  What is required is a negative GUT-scale matching
  contribution of that size: heavy exchange through portal couplings, which
  all vanish in the benchmark, or loop thresholds.

Scope: tree-level matching plus one-loop SM running.  This is a constraint on
the coupling point, not an exclusion of the model; G3 stays open.
"""
from __future__ import annotations

import argparse
import json
import math
from functools import lru_cache
from pathlib import Path
from typing import Any

import numpy as np
from scipy.integrate import solve_ivp
from scipy.optimize import brentq

import exact_gauged_u1x_g3_su5_delta_hsx_extension_v20 as candidate_source
import exact_gauged_u1x_physical_quotient_v20 as quotient_source
import g3_candidate_physical_target_audit_v20 as target
import gauged_u1x_g2_derivative_audit_v20 as g2_audit
import live_g2_canonical_486_field_chart_v20 as chart

ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "G3_TUNED_TARGET_EFFECTIVE_HIGGS_QUARTIC_V20.json"
OUT_MD = ROOT / "G3_TUNED_TARGET_EFFECTIVE_HIGGS_QUARTIC_V20.md"

MODEL_CONTRACT_ID = target.MODEL_CONTRACT_ID
ZERO_MODE_ATOL = 1.0e-9
COUPLING_ATOL = 1.0e-10
QUARTIC_ATOL = 1.0e-10
LIGHT_STATE_THRESHOLD = 1.0e-2
EXPECTED_GAUGE_ORBIT_RANK = 33
EXPECTED_SYMMETRY_ORBIT_RANK = 35
EXPECTED_LIGHT_DOUBLET_REAL_DIM = 4

# Standard Model inputs: MSbar couplings at mu = M_t (Buttazzo et al. 2013,
# arXiv:1307.3536, central values).  v = 246.22 GeV.
MU_TOP_GEV = 173.10
SM_INPUTS_AT_MT = {"gY": 0.35830, "g2": 0.64779, "g3": 1.1666, "yt": 0.93690}
LAMBDA_SM_AT_MT = 0.12604
V_EW_GEV = 246.22
M_H_OBSERVED_GEV = 125.20
M_GUT_SCAN_GEV = (2.0e15, 1.0e16, 2.0e16)
M_GUT_REFERENCE_GEV = 1.0e16
LOOP_FACTOR = 16.0 * math.pi**2
BETA_SCAN = (1 / 20, 1 / 40, 1 / 80, 1 / 160)


def tuned_coefficients() -> dict[str, float]:
    coefficients = target.candidate_coefficients()
    coefficients[target.O06_ID] = target.o06_tuning_audit()["tuned_O06"]
    return coefficients


@lru_cache(maxsize=1)
def _h_rows_at_tuned_point() -> dict[str, Any]:
    return target.parameter_rows(
        target.gut_point_state(), include=target.involves_fields(target.H_FIELDS)
    )


@lru_cache(maxsize=1)
def tuned_point_hessian() -> dict[str, Any]:
    state = target.gut_point_state()
    _, gradient, hessian = target.assemble(target.gut_point_rows(), tuned_coefficients())
    eigenvalues, eigenvectors = np.linalg.eigh(hessian)
    return {
        "state": state,
        "q": chart.pack(state),
        "gradient": gradient,
        "hessian": hessian,
        "eigenvalues": eigenvalues,
        "eigenvectors": eigenvectors,
    }


def symmetry_orbit(state: Any) -> tuple[np.ndarray, int]:
    gauge = chart.gauge_orbit_matrix(state)
    orbit = np.column_stack(
        (
            gauge,
            g2_audit.u1x_tangent(state),
            quotient_source._phase_tangent(state, quotient_source.PQ_CHARGES),
        )
    )
    gauge_rank = int(np.linalg.matrix_rank(gauge, tol=1.0e-10))
    return orbit, gauge_rank


def light_doublet_directions(hessian: np.ndarray) -> np.ndarray:
    """Unit real chart directions spanning the massless doublet (rows)."""
    matrix, _ = target.hermitian_h_mass_matrix(hessian)
    values, vectors = np.linalg.eigh(matrix[target.DOUBLET_BLOCK, target.DOUBLET_BLOCK])
    directions = []
    for value, vector in zip(values, vectors.T):
        if abs(value) > target.SPECTRUM_ATOL:
            continue
        h = np.zeros(chart.H_COMPLEX_DIM, dtype=complex)
        h[target.DOUBLET_BLOCK] = vector
        for phase in (1.0, 1.0j):
            q = np.zeros(chart.TOTAL_DIM, dtype=float)
            q[chart.H_SLICE] = chart._pack_complex_interleaved(phase * h / math.sqrt(2.0))
            directions.append(q / np.linalg.norm(q))
    return np.asarray(directions)


def _block_weights(vectors: np.ndarray) -> dict[str, float]:
    blocks = {
        "Phi210": chart.PHI_SLICE,
        "H10": chart.H_SLICE,
        "Sigma126bar": chart.SIGMA_SLICE,
        "S": chart.S_SLICE,
        "Phi17": chart.X_SLICE,
    }
    total = float(np.sum(vectors**2))
    return {
        name: float(np.sum(vectors[block] ** 2)) / total
        for name, block in blocks.items()
        if float(np.sum(vectors[block] ** 2)) / total > 1.0e-3
    }


def hessian_audit() -> dict[str, Any]:
    data = tuned_point_hessian()
    eigenvalues = data["eigenvalues"]
    eigenvectors = data["eigenvectors"]
    hessian = data["hessian"]
    orbit, gauge_rank = symmetry_orbit(data["state"])
    singular_values = np.linalg.svd(orbit, compute_uv=False)
    orbit_rank = int(np.sum(singular_values > 1.0e-10 * singular_values[0]))
    light = light_doublet_directions(hessian)
    zero = eigenvectors[:, np.abs(eigenvalues) <= ZERO_MODE_ATOL]
    span = np.column_stack((orbit, light.T))
    coefficients = np.linalg.lstsq(span, zero, rcond=None)[0]
    matrix, _ = target.hermitian_h_mass_matrix(hessian)

    light_states = []
    massive = eigenvalues > ZERO_MODE_ATOL
    values = eigenvalues[massive & (eigenvalues < LIGHT_STATE_THRESHOLD)]
    for value in np.unique(np.round(values, 9)):
        members = np.abs(eigenvalues - value) <= 1.0e-8
        light_states.append(
            {
                "mass_squared": float(value),
                "real_multiplicity": int(np.sum(members)),
                "field_weights": _block_weights(eigenvectors[:, members]),
            }
        )
    return {
        "state": "(F, r Delta_R, H=0, r, 1) with O06 tuned to the massless-doublet value",
        "gradient_max_abs": float(np.max(np.abs(data["gradient"]))),
        "minimum_eigenvalue": float(eigenvalues[0]),
        "negative_eigenvalues_below_minus_1e_minus_9": int(np.sum(eigenvalues < -ZERO_MODE_ATOL)),
        "zero_modes": int(zero.shape[1]),
        "gauge_orbit_rank": gauge_rank,
        "symmetry_orbit_rank_gauge_plus_X_plus_PQ": orbit_rank,
        "light_doublet_real_dimension": int(light.shape[0]),
        "hessian_on_symmetry_orbit_max_abs": float(np.max(np.abs(hessian @ orbit))),
        "hessian_on_light_doublet_max_abs": float(np.max(np.abs(hessian @ light.T))),
        "zero_modes_outside_orbit_plus_light_doublet": float(
            np.max(np.abs(span @ coefficients - zero))
        ),
        "heavy_sector_zero_modes": int(zero.shape[1]) - int(light.shape[0]),
        "smallest_nonzero_eigenvalue": float(eigenvalues[massive][0]),
        "light_h_spectrum": target.sm_branch_spectrum(matrix),
        "light_non_goldstone_states_below_1e_minus_2": light_states,
    }


def _h_rows_at(q: np.ndarray, parameter_ids: frozenset[str]) -> dict[str, Any]:
    rows = target.parameter_rows(
        chart.unpack(q), include=target.involves_fields(target.H_FIELDS)
    )
    if frozenset(rows) != parameter_ids:
        raise AssertionError("H-involving parameter rows changed between states")
    return rows


def effective_quartic_audit() -> dict[str, Any]:
    """lambda_direct and lambda_eff along each light-doublet chart direction.

    Terms without H are identical at q0 and q0 +/- u, so only H-involving
    rows enter the exact polynomial differences.
    """
    data = tuned_point_hessian()
    q0 = data["q"]
    eigenvalues = data["eigenvalues"]
    eigenvectors = data["eigenvectors"]
    massive = np.abs(eigenvalues) > ZERO_MODE_ATOL
    heavy_vectors = eigenvectors[:, massive]
    heavy_values = eigenvalues[massive]
    zero_vectors = eigenvectors[:, ~massive]

    base_rows = _h_rows_at_tuned_point()
    parameter_ids = frozenset(base_rows)
    coefficients = {
        key: value for key, value in tuned_coefficients().items() if key in parameter_ids
    }
    _, g0, h0 = target.assemble(base_rows, coefficients)

    light = light_doublet_directions(data["hessian"])
    directions = {f"u{index}": vector for index, vector in enumerate(light)}
    directions["mixed_u0_u2"] = (light[0] + light[2]) / math.sqrt(2.0)
    rows_out: dict[str, Any] = {}
    for name, u in directions.items():
        plus = _h_rows_at(q0 + u, parameter_ids)
        minus = _h_rows_at(q0 - u, parameter_ids)
        _, gp, hp = target.assemble(plus, coefficients)
        _, gm, hm = target.assemble(minus, coefficients)
        coupling = gp + gm - 2.0 * g0
        quartic = float(u @ (hp + hm - 2.0 * h0) @ u)
        heavy_components = heavy_vectors.T @ coupling
        shift = 3.0 * float(np.sum(heavy_components**2 / heavy_values))
        per_parameter = {}
        for key, value in coefficients.items():
            term = {key: value}
            contribution = float(
                u
                @ (
                    target.assemble({key: plus[key]}, term)[2]
                    + target.assemble({key: minus[key]}, term)[2]
                    - 2.0 * target.assemble({key: base_rows[key]}, term)[2]
                )
                @ u
            )
            if abs(contribution) > QUARTIC_ATOL:
                per_parameter[key] = contribution / 6.0
        rows_out[name] = {
            "coupling_vector_norm": float(np.linalg.norm(coupling)),
            "coupling_heavy_projection_norm": float(np.linalg.norm(heavy_components)),
            "coupling_zero_mode_projection_norm": float(
                np.linalg.norm(zero_vectors.T @ coupling)
            ),
            "Q_fourth_derivative": quartic,
            "lambda_direct": quartic / 6.0,
            "heavy_exchange_shift": shift / 6.0,
            "lambda_eff": (quartic - shift) / 6.0,
            "lambda_direct_by_parameter": per_parameter,
        }
    lambdas = [row["lambda_eff"] for row in rows_out.values()]
    directs = [row["lambda_direct"] for row in rows_out.values()]
    return {
        "normalization": "V = lambda (h^dag h)^2 with canonically normalized h; lambda = Q/6 along a unit chart direction",
        "directions": rows_out,
        "max_coupling_vector_norm": max(row["coupling_vector_norm"] for row in rows_out.values()),
        "lambda_direct": float(np.mean(directs)),
        "lambda_eff": float(np.mean(lambdas)),
        "lambda_spread_over_directions": float(max(directs) - min(directs)),
        "lambda_eff_minus_direct": float(np.mean(lambdas) - np.mean(directs)),
    }


def _sm_beta(_: float, y: np.ndarray) -> np.ndarray:
    g_y, g2, g3, yt, lam = y
    return (
        np.array(
            [
                41.0 / 6.0 * g_y**3,
                -19.0 / 6.0 * g2**3,
                -7.0 * g3**3,
                yt * (4.5 * yt**2 - 8.0 * g3**2 - 2.25 * g2**2 - 17.0 / 12.0 * g_y**2),
                24.0 * lam**2
                - 6.0 * yt**4
                + 12.0 * lam * yt**2
                - 3.0 * lam * (3.0 * g2**2 + g_y**2)
                + 0.375 * (2.0 * g2**4 + (g2**2 + g_y**2) ** 2),
            ]
        )
        / LOOP_FACTOR
    )


def _run(y0: list[float], mu_from: float, mu_to: float) -> np.ndarray:
    solution = solve_ivp(
        _sm_beta,
        (math.log(mu_from), math.log(mu_to)),
        y0,
        method="DOP853",
        rtol=1.0e-12,
        atol=1.0e-14,
    )
    if not solution.success:
        raise ArithmeticError(solution.message)
    return solution.y[:, -1]


@lru_cache(maxsize=None)
def _sm_couplings_at(mu: float) -> tuple[float, ...]:
    inputs = SM_INPUTS_AT_MT
    y = _run(
        [inputs["gY"], inputs["g2"], inputs["g3"], inputs["yt"], LAMBDA_SM_AT_MT],
        MU_TOP_GEV,
        mu,
    )
    return tuple(float(value) for value in y)


def lambda_at_top(lambda_gut: float, m_gut: float) -> float:
    g_y, g2, g3, yt, _ = _sm_couplings_at(m_gut)
    return float(_run([g_y, g2, g3, yt, lambda_gut], m_gut, MU_TOP_GEV)[4])


def higgs_mass_tree(lambda_top: float) -> float:
    return math.sqrt(2.0 * lambda_top) * V_EW_GEV if lambda_top > 0 else float("nan")


def lambda_gut_for_sm(m_gut: float) -> float:
    return brentq(
        lambda value: lambda_at_top(value, m_gut) - LAMBDA_SM_AT_MT, -0.15, 0.3, xtol=1.0e-13
    )


def sm_running_audit(lambda_eff: float) -> dict[str, Any]:
    bfb_floor = float(2 * candidate_source.BETA**2)
    table = []
    for m_gut in M_GUT_SCAN_GEV:
        entries = {}
        for label, value in (
            ("certified_lambda_eff", lambda_eff),
            ("sufficient_BFB_floor_2beta2", bfb_floor),
            ("zero", 0.0),
        ):
            lam_top = lambda_at_top(value, m_gut)
            entries[label] = {
                "lambda_gut": value,
                "lambda_at_mt": lam_top,
                "m_h_tree_GeV": higgs_mass_tree(lam_top),
            }
        table.append(
            {
                "M_GUT_GeV": m_gut,
                "predictions": entries,
                "lambda_gut_required_for_SM": lambda_gut_for_sm(m_gut),
                "SM_lambda_at_M_GUT": _sm_couplings_at(m_gut)[4],
            }
        )
    reference = next(row for row in table if row["M_GUT_GeV"] == M_GUT_REFERENCE_GEV)
    return {
        "scheme": "one-loop SM RGEs, tree-level matching lambda(M_GUT)=lambda_eff, m_h=sqrt(2 lambda(M_t)) v",
        "inputs": {
            "mu_top_GeV": MU_TOP_GEV,
            "couplings_at_mt": SM_INPUTS_AT_MT,
            "lambda_SM_at_mt": LAMBDA_SM_AT_MT,
            "v_GeV": V_EW_GEV,
            "source": "Buttazzo et al. 2013 (arXiv:1307.3536) central MSbar values",
        },
        "sm_calibration_m_h_tree_GeV": higgs_mass_tree(LAMBDA_SM_AT_MT),
        "table": table,
        "reference_M_GUT_GeV": M_GUT_REFERENCE_GEV,
        "reference_m_h_certified_GeV": reference["predictions"]["certified_lambda_eff"]["m_h_tree_GeV"],
        "reference_m_h_bfb_floor_GeV": reference["predictions"]["sufficient_BFB_floor_2beta2"]["m_h_tree_GeV"],
        "reference_m_h_lambda_zero_GeV": reference["predictions"]["zero"]["m_h_tree_GeV"],
        "reference_lambda_gut_required": reference["lambda_gut_required_for_SM"],
        "caveat": (
            "One loop only. The literature NNLO analysis puts the SM lambda near M_GUT at "
            "about -0.01 rather than -0.03 (not recomputed here); the required matching "
            "contribution stays negative, which is what the conclusions below use."
        ),
    }


def beta_tradeoff_audit() -> dict[str, Any]:
    """beta sets both the BFB floor on lambda_H and the triplet partner mass."""
    t = float(candidate_source.SIGMA_SCALE)
    r = float(candidate_source.R)
    rows = []
    for beta in BETA_SCAN:
        floor = beta * beta / (4.0 * t)
        rows.append(
            {
                "beta": beta,
                "lambda_H_BFB_floor": floor,
                "m_h_tree_GeV_at_floor": higgs_mass_tree(lambda_at_top(floor, M_GUT_REFERENCE_GEV)),
                "partner_triplet_mass_over_M": math.sqrt(beta) * r,
            }
        )
    return {
        "BFB_certificate": "lambda_H N_H^2 + t N_Sigma^2 - beta N_H N_Sigma >= 0 needs beta^2 < 4 t lambda_H, t = 1/8",
        "rows": rows,
        "lambda_H_floor_is_2_beta_squared": all(
            abs(row["lambda_H_BFB_floor"] - 2.0 * row["beta"] ** 2) < 1.0e-15 for row in rows
        ),
    }


def build_report() -> dict[str, Any]:
    hessian = hessian_audit()
    quartic = effective_quartic_audit()
    running = sm_running_audit(quartic["lambda_eff"])
    tradeoff = beta_tradeoff_audit()
    spectrum = hessian["light_h_spectrum"]
    beta_r2 = float(target.BETA_R2)
    checks = {
        "tuned_O06_is_zero": abs(tuned_coefficients()[target.O06_ID]) <= target.SPECTRUM_ATOL,
        "tuned_point_is_stationary": hessian["gradient_max_abs"] < target.STATIONARITY_ATOL,
        "tuned_hessian_is_positive_semidefinite": hessian["negative_eigenvalues_below_minus_1e_minus_9"] == 0,
        "gauge_orbit_rank_is_33_SO10_over_SM": hessian["gauge_orbit_rank"] == EXPECTED_GAUGE_ORBIT_RANK,
        "symmetry_orbit_rank_is_35": (
            hessian["symmetry_orbit_rank_gauge_plus_X_plus_PQ"] == EXPECTED_SYMMETRY_ORBIT_RANK
        ),
        "hessian_annihilates_orbit_and_light_doublet": (
            hessian["hessian_on_symmetry_orbit_max_abs"] < 1.0e-10
            and hessian["hessian_on_light_doublet_max_abs"] < 1.0e-10
        ),
        "zero_modes_are_goldstones_plus_massless_doublet": (
            hessian["zero_modes"] == EXPECTED_SYMMETRY_ORBIT_RANK + EXPECTED_LIGHT_DOUBLET_REAL_DIM
            and hessian["light_doublet_real_dimension"] == EXPECTED_LIGHT_DOUBLET_REAL_DIM
            and hessian["zero_modes_outside_orbit_plus_light_doublet"] < 1.0e-9
        ),
        "light_h_spectrum_is_massless_doublet_and_beta_r2_triplet": (
            target._close(target._values(spectrum["weak_doublets"]), [0.0, 1.2])
            and target._close(
                target._values(spectrum["colour_triplets"]), [beta_r2, 1.2 - beta_r2]
            )
        ),
        "light_doublet_has_no_heavy_mode_coupling": quartic["max_coupling_vector_norm"] < COUPLING_ATOL,
        "quartic_is_su2_x_u1_invariant_on_the_doublet": (
            quartic["lambda_spread_over_directions"] < QUARTIC_ATOL
        ),
        "lambda_eff_equals_lambda_direct": abs(quartic["lambda_eff_minus_direct"]) < QUARTIC_ATOL,
        "sm_running_reproduces_negative_sm_lambda_at_gut_scale": all(
            row["SM_lambda_at_M_GUT"] < 0 for row in running["table"]
        ),
        "no_gate_closed_or_model_excluded": True,
    }
    failures = [name for name, passed in checks.items() if not passed]
    ok = not failures
    outcomes = {
        "lambda_eff_at_certified_couplings": quartic["lambda_eff"],
        "certified_couplings_predict_m_h_GeV": running["reference_m_h_certified_GeV"],
        "certified_coupling_point_excluded_by_higgs_mass": ok
        and running["reference_m_h_certified_GeV"] > M_H_OBSERVED_GEV + 20.0,
        "nonnegative_tree_matching_gives_m_h_above_observed": ok
        and running["reference_m_h_lambda_zero_GeV"] > M_H_OBSERVED_GEV,
        "sharper_BFB_bound_alone_cannot_reach_observed_m_h": ok
        and running["reference_m_h_lambda_zero_GeV"] > M_H_OBSERVED_GEV,
        "negative_gut_matching_required": ok and running["reference_lambda_gut_required"] < 0,
        "portal_feedback_absent_in_benchmark": ok,
    }
    return {
        "model_contract_id": MODEL_CONTRACT_ID,
        "status": (
            "G3_TUNED_TARGET_LAMBDA_EFF_EQUALS_DIRECT_H_QUARTIC__CERTIFIED_COUPLINGS_EXCLUDED_BY_HIGGS_MASS__G3_OPEN"
            if ok
            else "G3_TUNED_TARGET_HIGGS_QUARTIC_AUDIT_FAILED"
        ),
        "overall_state": "PHYSICAL_TARGET_CONSTRAINT" if ok else "EXECUTION_FAIL",
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "checks": checks,
        "scientific_outcomes": outcomes,
        "units": target.UNITS,
        "tuned_point_hessian": hessian,
        "effective_quartic": quartic,
        "sm_running": running,
        "beta_tradeoff": tradeoff,
        "flags": {
            "g3_closed": False,
            "whole_model_validated": False,
            "whole_model_excluded": False,
            "tree_level_matching_only": True,
            "one_loop_running_only": True,
        },
        "scope": (
            "The tuned point keeps the certified hierarchy r = 1/5 for Sigma and S. "
            "The tree-level decoupling (c = 0) does not depend on r, but at the "
            "physical hierarchy (Sigma, S at M_I) intermediate-scale states would "
            "modify the running between M_I and M_GUT; the m_h values assume SM "
            "running all the way from M_GUT."
        ),
        "verdict": (
            "At the tuned physical target the light doublet has no tree-level coupling "
            "to any heavy mode, so lambda_eff equals the direct H quartic, 1 for the "
            "certified couplings; one-loop running then gives m_h ~ 173 GeV, which "
            "excludes this coupling point. Because bounded-below along the pure-H ray "
            "needs lambda_direct >= 0, every coupling point of this family without "
            "portal feedback has m_h >= 133.6 GeV at one loop; the sufficient BFB floor "
            "2 beta^2 costs only another ~1.2 GeV. Reaching 125 GeV needs a negative "
            "GUT-scale matching contribution of about -0.03 (one loop), from heavy "
            "exchange through portals that vanish in the benchmark or from loop "
            "thresholds. G3 stays open; the model is not excluded."
        ),
    }


def _markdown(report: dict[str, Any]) -> str:
    running = report["sm_running"]
    hessian = report["tuned_point_hessian"]
    return "\n".join(
        [
            "# Effective Higgs quartic at the tuned G3 target -- v20",
            "",
            f"**Status:** `{report['status']}`",
            "",
            report["verdict"],
            "",
            f"- tuned-point Hessian: PSD, {hessian['zero_modes']} zero modes "
            f"({hessian['symmetry_orbit_rank_gauge_plus_X_plus_PQ']} symmetry + "
            f"{hessian['light_doublet_real_dimension']} light doublet);",
            f"- lambda_eff = lambda_direct = `{report['effective_quartic']['lambda_eff']:.12g}`;",
            f"- m_h (one loop, M_GUT = 1e16 GeV): certified `{running['reference_m_h_certified_GeV']:.1f}` GeV, "
            f"BFB floor `{running['reference_m_h_bfb_floor_GeV']:.1f}` GeV, lambda=0 "
            f"`{running['reference_m_h_lambda_zero_GeV']:.1f}` GeV;",
            f"- lambda(M_GUT) needed for the SM: `{running['reference_lambda_gut_required']:.4f}` (one loop);",
            "- G3: `OPEN`; whole model: neither validated nor excluded.",
            "",
        ]
    )


def write_report(report: dict[str, Any]) -> None:
    OUT_JSON.write_text(
        json.dumps(target._jsonable(report), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    OUT_MD.write_text(_markdown(report), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    report = build_report()
    if args.write:
        write_report(report)
    print(json.dumps(target._jsonable(report), indent=2, sort_keys=True))
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
