#!/usr/bin/env python3
"""Insert six independent pure Phi-Sigma quartic couplings into triplet M2.

The exact Casimir projectors provide a complete pure-irrep basis

    Q = 1, 45, 210, 770, 5940, 8910

for the color-triplet matrices generated by
210_H^2 126bar_H^dag 126bar_H.  This gate replaces the mixed legacy
parameterization

    lambda210_126       (universal singlet),
    lambda_phi_sigma_45 (current-normalized 45),
    lambda_phi_sigma_C  (one recoupled contraction)

with six independent projector-normalized couplings lambda_Q.

The exact normalization map is

    I_1(projector)  = (1/21) I_norm,
    I_45(projector) = -(1/35) I_45(current),
    I_C             = sum_Q I_Q.

Thus a legacy point is reproduced by

    lambda_1    = lambda_C + 21 lambda_norm,
    lambda_45   = lambda_C - 35 lambda_45_old,
    lambda_210  = lambda_C,
    lambda_770  = lambda_C,
    lambda_5940 = lambda_C,
    lambda_8910 = lambda_C.

The old Phi-Sigma singlet, 45 and C contributions are set to zero internally
before the six pure matrices are inserted, preventing double counting.
"""
from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any

import numpy as np

import exact_phisigma_casimir_projectors_v20 as pure
import next_gen_triplet_hsigma_hermitian_family_gate_v20 as upstream
import next_gen_triplet_nambu_hessian_v20 as nambu

ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "NEXT_GEN_TRIPLET_PURE_PHISIGMA_GATE_V20.json"
OUT_MD = ROOT / "NEXT_GEN_TRIPLET_PURE_PHISIGMA_GATE_V20.md"
CHANNELS = ("1", "45", "210", "770", "5940", "8910")


def validate_couplings(couplings: dict[str, float]) -> dict[str, float]:
    if set(couplings) != set(CHANNELS):
        missing = sorted(set(CHANNELS) - set(couplings))
        extra = sorted(set(couplings) - set(CHANNELS))
        raise ValueError(f"pure Phi-Sigma couplings mismatch: missing={missing}, extra={extra}")
    return {name: float(couplings[name]) for name in CHANNELS}


def legacy_to_pure_couplings(
    *, lambda_norm: float, lambda_45_old: float, lambda_C: float
) -> dict[str, float]:
    return {
        "1": float(lambda_C + 21.0 * lambda_norm),
        "45": float(lambda_C - 35.0 * lambda_45_old),
        "210": float(lambda_C),
        "770": float(lambda_C),
        "5940": float(lambda_C),
        "8910": float(lambda_C),
    }


def pure_phisigma_delta(
    *, p: float, a: float, omega: float, couplings: dict[str, float]
) -> dict[str, np.ndarray]:
    normalized = validate_couplings(couplings)
    delta_u = np.zeros((1, 1), dtype=complex)
    delta_v = np.zeros((2, 2), dtype=complex)
    by_channel: dict[str, dict[str, np.ndarray]] = {}
    for channel in CHANNELS:
        blocks = pure.evaluate_channel_blocks(channel, p, a, omega)
        scaled = {
            "A_u_sigma_GeV2": normalized[channel] * blocks["A_u_sigma_GeV2"],
            "A_v_sigma_GeV2": normalized[channel] * blocks["A_v_sigma_GeV2"],
        }
        by_channel[channel] = scaled
        delta_u += scaled["A_u_sigma_GeV2"]
        delta_v += scaled["A_v_sigma_GeV2"]
    return {
        "A_u_sigma_GeV2": delta_u,
        "A_v_sigma_GeV2": delta_v,
        "by_channel": by_channel,
    }


def build_with_pure_phisigma(
    *,
    norm_parameters: dict[str, Any],
    anisotropic_residual_m2: dict[str, float],
    p: float,
    a: float,
    omega: float,
    s_expectation: float,
    lambda4: complex,
    mu_eta: complex,
    kappa10: complex,
    lambda10_hol: complex,
    h_background_bilinear: complex,
    lambda_phi_h_54: float,
    lambda_phi_h_45: float,
    h_u: float,
    h_d: float,
    v_r: float,
    lambda_hsigma_45: float,
    lambda_phi_sigma_irreps: dict[str, float],
    unknown_a_u_offdiag_m2: complex = 0.0,
    unknown_a_v_h_t2bar_m2: complex = 0.0,
    unknown_a_v_h_t4bar_m2: complex = 0.0,
    unknown_a_v_t2bar_t4bar_m2: complex = 0.0,
) -> dict[str, Any]:
    couplings = validate_couplings(lambda_phi_sigma_irreps)
    stripped_norm = copy.deepcopy(norm_parameters)
    legacy_norm = float(stripped_norm.get("lambda210_126", 0.0))
    stripped_norm["lambda210_126"] = 0.0

    blocks = upstream.build_with_hsigma_hermitian_family(
        norm_parameters=stripped_norm,
        anisotropic_residual_m2=anisotropic_residual_m2,
        p=p,
        a=a,
        omega=omega,
        s_expectation=s_expectation,
        lambda4=lambda4,
        mu_eta=mu_eta,
        kappa10=kappa10,
        lambda10_hol=lambda10_hol,
        h_background_bilinear=h_background_bilinear,
        lambda_phi_h_54=lambda_phi_h_54,
        lambda_phi_h_45=lambda_phi_h_45,
        lambda_phi_sigma_45=0.0,
        lambda_phi_sigma_contract=0.0,
        h_u=h_u,
        h_d=h_d,
        v_r=v_r,
        lambda_hsigma_45=lambda_hsigma_45,
        unknown_a_u_offdiag_m2=unknown_a_u_offdiag_m2,
        unknown_a_v_h_t2bar_m2=unknown_a_v_h_t2bar_m2,
        unknown_a_v_h_t4bar_m2=unknown_a_v_h_t4bar_m2,
        unknown_a_v_t2bar_t4bar_m2=unknown_a_v_t2bar_t4bar_m2,
    )
    delta = pure_phisigma_delta(
        p=p, a=a, omega=omega, couplings=couplings
    )
    blocks["A_u_GeV2"] = np.asarray(blocks["A_u_GeV2"], dtype=complex)
    blocks["A_v_GeV2"] = np.asarray(blocks["A_v_GeV2"], dtype=complex)
    blocks["A_u_GeV2"][1:2, 1:2] += delta["A_u_sigma_GeV2"]
    blocks["A_v_GeV2"][1:3, 1:3] += delta["A_v_sigma_GeV2"]

    blocks["operator_provenance"] = dict(blocks["operator_provenance"])
    blocks["operator_provenance"]["A_u_11"] = (
        blocks["operator_provenance"].get("A_u_11", "diagonal")
        + " + sum_Q lambda_PhiSigma_Q P_Q(p,a,omega)[t2]"
    )
    for slot in ("A_v_11", "A_v_12", "A_v_22"):
        blocks["operator_provenance"][slot] = (
            blocks["operator_provenance"].get(slot, "PhiSigma quartic")
            + " + sum_Q lambda_PhiSigma_Q P_Q(p,a,omega)[t2bar,t4bar]"
        )
    blocks["exact_pure_PhiSigma_quartics"] = {
        "couplings": couplings,
        "legacy_lambda210_126_removed_internally": legacy_norm,
        "legacy_lambda_phi_sigma_45_inserted": 0.0,
        "legacy_lambda_phi_sigma_contract_inserted": 0.0,
        "Delta_A_u_sigma_GeV2": delta["A_u_sigma_GeV2"],
        "Delta_A_v_sigma_GeV2": delta["A_v_sigma_GeV2"],
        "by_channel": delta["by_channel"],
        "all_six_pure_triplet_matrices_inserted": True,
    }
    return blocks


def _inputs() -> tuple[dict[str, Any], dict[str, float], dict[str, Any]]:
    h_u, h_d, v_r = 0.13, 0.07, 0.9
    norm = {
        "m10_sq": 40.0,
        "m126_sq": 50.0,
        "lambda10": 0.1,
        "lambda126": 0.12,
        "lambda10_126": 0.31,
        "lambda210_10": 0.04,
        "lambda210_126": 0.05,
        "lambdaS_10": 0.02,
        "lambdaS_126": 0.025,
        "lambdaX_10": 0.01,
        "lambdaX_126": 0.015,
        "h_norm_sq": h_u**2 + h_d**2,
        "sigma_norm_sq": v_r**2,
        "s_abs_sq": 0.04,
        "phi17_abs_sq": 0.09,
    }
    residuals = {
        "delta_T10_Ym13_m2": 0.0,
        "delta_t2_Ym13_m2": 0.0,
        "delta_T10bar_Yp13_m2": 0.0,
        "delta_t2bar_Yp13_m2": 0.0,
        "delta_t4bar_Yp13_m2": 0.0,
    }
    inputs = {
        "p": 0.9,
        "a": 0.4,
        "omega": 0.7,
        "s_expectation": 0.2,
        "lambda4": 0.05,
        "mu_eta": 0.3,
        "kappa10": 0.2,
        "lambda10_hol": 0.17,
        "h_background_bilinear": 0.11 + 0.03j,
        "lambda_phi_h_54": 0.07,
        "lambda_phi_h_45": 0.03,
        "h_u": h_u,
        "h_d": h_d,
        "v_r": v_r,
        "lambda_hsigma_45": 0.21,
    }
    return norm, residuals, inputs


def _matrix_payload(matrix: np.ndarray) -> list[list[dict[str, float]]]:
    return [
        [
            {"re": float(np.real(value)), "im": float(np.imag(value))}
            for value in row
        ]
        for row in np.asarray(matrix, dtype=complex)
    ]


def build_report() -> dict[str, Any]:
    projector_report = pure.build_report()
    upstream_report = upstream.build_report()
    norm, residuals, inputs = _inputs()

    legacy_45 = 0.02
    legacy_C = 0.04
    legacy = upstream.build_with_hsigma_hermitian_family(
        norm_parameters=norm,
        anisotropic_residual_m2=residuals,
        lambda_phi_sigma_45=legacy_45,
        lambda_phi_sigma_contract=legacy_C,
        **inputs,
    )
    mapped = legacy_to_pure_couplings(
        lambda_norm=norm["lambda210_126"],
        lambda_45_old=legacy_45,
        lambda_C=legacy_C,
    )
    replacement = build_with_pure_phisigma(
        norm_parameters=norm,
        anisotropic_residual_m2=residuals,
        lambda_phi_sigma_irreps=mapped,
        **inputs,
    )
    legacy_residual = max(
        float(np.max(np.abs(replacement[key] - legacy[key])))
        for key in ("A_u_GeV2", "A_v_GeV2", "B_holomorphic_GeV2")
    )

    arbitrary_couplings = {
        "1": 0.13,
        "45": -0.08,
        "210": 0.05,
        "770": 0.02,
        "5940": -0.03,
        "8910": 0.04,
    }
    arbitrary = build_with_pure_phisigma(
        norm_parameters=norm,
        anisotropic_residual_m2=residuals,
        lambda_phi_sigma_irreps=arbitrary_couplings,
        **inputs,
    )
    matrix = nambu.nambu_matrix_from_blocks(
        arbitrary["A_u_GeV2"],
        arbitrary["A_v_GeV2"],
        arbitrary["B_holomorphic_GeV2"],
    )
    eigenvalues = np.linalg.eigvalsh(matrix)
    expected_delta = pure_phisigma_delta(
        p=inputs["p"],
        a=inputs["a"],
        omega=inputs["omega"],
        couplings=arbitrary_couplings,
    )
    recorded = arbitrary["exact_pure_PhiSigma_quartics"]
    insertion_residual = max(
        float(np.max(np.abs(recorded["Delta_A_u_sigma_GeV2"] - expected_delta["A_u_sigma_GeV2"]))),
        float(np.max(np.abs(recorded["Delta_A_v_sigma_GeV2"] - expected_delta["A_v_sigma_GeV2"]))),
    )
    checks = {
        "projector_upstream_passes": projector_report["n_failed"] == 0,
        "assembled_upstream_passes": upstream_report["n_failed"] == 0,
        "legacy_parameterization_reconstructed_exactly": legacy_residual < 1.0e-10,
        "pure_insertion_matches_six_channel_sum": insertion_residual < 1.0e-12,
        "old_singlet_removed_before_pure_insertion": recorded[
            "legacy_lambda210_126_removed_internally"
        ]
        == norm["lambda210_126"],
        "old_45_and_C_not_double_counted": recorded[
            "legacy_lambda_phi_sigma_45_inserted"
        ]
        == 0.0
        and recorded["legacy_lambda_phi_sigma_contract_inserted"] == 0.0,
        "assembled_matrix_hermitian": float(np.max(np.abs(matrix - matrix.conj().T))) < 1.0e-12,
        "conditional_benchmark_positive": float(eigenvalues[0]) > 0.0,
        "all_six_independent_couplings_accepted": set(arbitrary_couplings) == set(CHANNELS),
        "full_component_potential_not_claimed": True,
        "physical_spectrum_not_claimed": True,
    }
    failures = [name for name, ok in checks.items() if not ok]
    return {
        "status": (
            "NEXT_GEN_PURE_PHISIGMA_TRIPLET_FAMILY_INSERTED"
            if not failures
            else "NEXT_GEN_PURE_PHISIGMA_TRIPLET_GATE_FAILED"
        ),
        "overall_state": "PARTIAL" if not failures else "EXECUTION_FAIL",
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "checks": checks,
        "normalization_and_legacy_map": {
            "I1_projector_equals_I_norm_over_21": True,
            "I45_projector_equals_minus_I45_current_over_35": True,
            "IC_equals_sum_of_six_projected_invariants": True,
            "legacy_inputs": {
                "lambda_norm": norm["lambda210_126"],
                "lambda_45_old": legacy_45,
                "lambda_C": legacy_C,
            },
            "mapped_pure_couplings": mapped,
            "maximum_full_block_residual": legacy_residual,
        },
        "arbitrary_six_coupling_benchmark": {
            "scope": "conditional algebraic point, not the unique v20 vacuum",
            "couplings": arbitrary_couplings,
            "minimum_eigenvalue_m2": float(eigenvalues[0]),
            "insertion_residual": insertion_residual,
            "A_u_GeV2": _matrix_payload(arbitrary["A_u_GeV2"]),
            "A_v_GeV2": _matrix_payload(arbitrary["A_v_GeV2"]),
            "B_holomorphic_GeV2": _matrix_payload(arbitrary["B_holomorphic_GeV2"]),
        },
        "newly_closed_subproblem": {
            "six_independent_PhiSigma_triplet_couplings_inserted": not failures,
            "legacy_mixed_parameterization_replaced_without_double_counting": not failures,
            "complete_PhiSigma_quartic_triplet_family_in_Nambu_matrix": not failures,
        },
        "remaining_blockers": {
            "all_component_210_projectors": True,
            "complete_component_scalar_potential": True,
            "unique_gauge_quotiented_vacuum": True,
            "positive_full_component_Hessian": True,
            "physical_threshold_spectrum": True,
            "component_level_two_loop_matching": True,
            "exact_unique_proton_lifetime": True,
        },
        "flag": {
            "complete_PhiSigma_quartic_triplet_family_inserted": not failures,
            "complete_PhiSigma_quartic_all_component_family_inserted": False,
            "complete_component_potential": False,
            "physical_triplet_spectrum_complete": False,
            "exact_unique_proton_lifetime": False,
            "whole_model_validated": False,
            "whole_model_excluded": False,
            "empirical_discovery": False,
        },
        "verdict": (
            "The Nambu triplet matrix now accepts six independent pure PhiSigma "
            "quartic couplings. The exact legacy map reproduces the old singlet, "
            "45-current and C-contraction parameterization without double counting."
        ),
    }


def write_markdown(report: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Next-generation pure Phi–Sigma triplet gate — v20",
            "",
            f"**Status:** `{report['status']}`",
            "",
            report["verdict"],
            "",
            "- Independent couplings: `lambda_1, lambda_45, lambda_210, lambda_770, lambda_5940, lambda_8910`.",
            f"- Legacy reconstruction residual: `{report['normalization_and_legacy_map']['maximum_full_block_residual']:.3e}`.",
            "- The all-component potential and physical spectrum remain open.",
            "",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    argparse.ArgumentParser(description=__doc__).parse_args(argv)
    report = build_report()
    payload = json.dumps(report, indent=2, default=lambda obj: obj.tolist() if isinstance(obj, np.ndarray) else None) + "\n"
    OUT_JSON.write_text(payload, encoding="utf-8")
    OUT_MD.write_text(write_markdown(report), encoding="utf-8")
    print(payload, end="")
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
