#!/usr/bin/env python3
r"""Nonsusy colour-triplet M_T from charge-allowed operators only (v20).

Next step after ``nonsusy_z17_pq_potential_filter_v20``:

1. Build the nonsusy ``{T_10, T_126}`` mass matrix using **only** operators
   that pass the v20 PQ/X/Z₁₇ filter.
2. Include the PQ-safe within-10 mixing from ``10_H^2 S`` (∼κ⟨S⟩), not bare
   ``10_H^2``.
3. Optionally include the CONDITIONAL ``10_H 126bar_H S`` mixing (SO(10)
   existence still open) as an explicit on/off switch.
4. Compute a reduced **phase Hessian** for the charge-allowed locking
   operator ``126bar_H^2 10_H^2 S^2``.
5. Route lightest eigenvalues into Patel–Shukla / interference tests.

Honesty
-------
* Couplings (λ, κ, μ) remain free parameters — full CG normalizations for
  nonsusy 210^n contractions are still OPEN.
* Published Aulakh CG is used only as structural precedent for which
  210–odd-tensor mixings exist; numerical CG factors are absorbed into λ's.
* This is not a unique vacuum spectrum.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import numpy as np

import conditional_mt_interference_v20 as cmt
import nonsusy_z17_pq_potential_filter_v20 as z17
import patel_shukla_scalar_pdecay_v20 as ps
import scalar_vacuum_proton_decay_v20 as scalar_pd

ROOT = Path(__file__).resolve().parent

SOURCES = {
    "z17_filter": "nonsusy_z17_pq_potential_filter_v20",
    "patel_shukla": ps.SOURCE,
    "aulakh_structure": {
        "citation": "Aulakh–Girdhar hep-ph/0204097",
        "use": "Existence of 210–10 and 210–126 triplet mixings; CG absorbed into λ",
    },
}


def allowed_mt_operator_ledger() -> dict[str, Any]:
    """Pull M_T-feeding operators from the Z17/PQ filter."""
    ops = z17.operator_catalogue()
    allowed = [
        o
        for o in ops
        if o.get("feeds_triplet_mass")
        and o["charge_allowed"]["all"]
        and o["status"] in {"ALLOWED", "CHARGE_OK_SO10_OPEN"}
    ]
    forbidden_mt = [
        o
        for o in ops
        if o.get("feeds_triplet_mass") and not o["charge_allowed"]["all"]
    ]
    return {
        "allowed_feeding_M_T": [
            {
                "name": o["name"],
                "dim": o["dim"],
                "so10_invariant_exists": o["so10_invariant_exists"],
                "status": o["status"],
            }
            for o in allowed
        ],
        "forbidden_feeding_M_T": [o["name"] for o in forbidden_mt],
        "bare_10_squared_excluded": "bare_10_H^2" in [o["name"] for o in forbidden_mt],
        "ten2_S_included": any(o["name"] == "10_H^2 S" for o in allowed),
        "conditional_10_126_S": any(o["name"] == "10_H 126bar_H S" for o in allowed),
    }


def fill_charge_allowed_mt(
    *,
    v210: float,
    vS: float,
    mu10: float,
    mu126: float,
    lam210_10: float,
    lam210_126: float,
    lamS_10: float,
    lamS_126: float,
    lam_mix: float,
    include_conditional_mix: bool,
) -> np.ndarray:
    """Hermitian 2×2 in basis (T_10, T_126).

    M11 = μ10 + λ210_10 ⟨210⟩ + λS_10 ⟨S⟩
    M22 = μ126 + λ210_126 ⟨210⟩ + λS_126 ⟨S⟩
    M12 = λ_mix ⟨S⟩   (only if include_conditional_mix; else 0)

    Bare 10^2 contribution is identically absent (PQ-forbidden).
    """
    m11 = mu10 + lam210_10 * v210 + lamS_10 * vS
    m22 = mu126 + lam210_126 * v210 + lamS_126 * vS
    m12 = (lam_mix * vS) if include_conditional_mix else 0.0
    return np.array([[m11, m12], [m12, m22]], dtype=float)


def within_10_mixing_from_S(
    *,
    m_t: float,
    m_tbar: float,
    kappa: float,
    vS: float,
) -> dict[str, Any]:
    """PQ-safe θ_T from 10_H^2 S: μ^2 = κ⟨S⟩ (Patel–Shukla Eq. 27 structure)."""
    mu2 = kappa * vS * vS  # κ dimensionless ⇒ μ² has mass²
    denom = m_tbar**2 - m_t**2
    if abs(denom) < 1e-30:
        theta = math.pi / 4.0 if abs(mu2) > 0 else 0.0
    else:
        theta = 0.5 * math.atan2(2.0 * mu2, denom)
    return {
        "operator": "10_H^2 S",
        "mu2_GeV2": mu2,
        "m_T_GeV": m_t,
        "m_Tbar_GeV": m_tbar,
        "theta_T_rad": theta,
        "theta_T_deg": float(math.degrees(theta)),
        "bare_10_squared_used": False,
        "note": "θ_T regenerated by κ⟨S⟩, not by PQ-forbidden bare 10^2",
    }


def locking_phase_hessian(*, A_lock: float) -> dict[str, Any]:
    """Reduced phase Hessian for V = −A cos(2φ_Δ + 2φ_10 + 2φ_S).

    At the aligned minimum (argument = 0), second derivatives w.r.t.
    (φ_Δ, φ_10, φ_S) give the 3×3 Hessian H_ij = 4 A n_i n_j with
    n = (2, 2, 2) wait: θ = 2φ_Δ + 2φ_10 + 2φ_S ⇒ ∂θ/∂φ = (2,2,2),
    V_θθ = A at min, so H = A * outer(g,g) with g=(2,2,2).
    """
    g = np.array([2.0, 2.0, 2.0], dtype=float)
    hess = A_lock * np.outer(g, g)
    eigs = np.linalg.eigvalsh(hess)
    # One massive phase combination; two flat directions (overall rephase /
    # orthogonal combinations) at this single-operator level.
    return {
        "potential": "V=-A_lock cos(2 φ_Delta + 2 φ_10 + 2 φ_S)",
        "A_lock": A_lock,
        "fields": ["phi_DeltaR_126", "phi_10", "phi_S"],
        "hessian": hess.tolist(),
        "eigenvalues": [float(x) for x in eigs],
        "n_positive": int(np.sum(eigs > 1e-12 * max(1.0, abs(A_lock)))),
        "n_zero": int(np.sum(np.abs(eigs) <= 1e-12 * max(1.0, abs(A_lock)))),
        "interpretation": (
            "Single locking operator massifies one phase combination and "
            "leaves two flat directions; complete phase Hessian needs the "
            "full charge-allowed potential (still OPEN)."
        ),
        "flag": {
            "locking_operator_included": True,
            "complete_phase_hessian": False,
        },
    }


SCENARIOS: list[dict[str, Any]] = [
    {
        "name": "decoupled_MI_no_mix",
        "mu10_over_MI": 1.0,
        "mu126_over_MI": 1.0,
        "lam210_10": 0.0,
        "lam210_126": 0.0,
        "lamS_10": 0.0,
        "lamS_126": 0.0,
        "lam_mix": 0.0,
        "include_conditional_mix": False,
        "kappa": 0.0,
    },
    {
        "name": "210_push_10",
        "mu10_over_MI": 0.0,
        "mu126_over_MI": 1.0,
        "lam210_10": 1.0,
        "lam210_126": 0.0,
        "lamS_10": 0.0,
        "lamS_126": 0.0,
        "lam_mix": 0.0,
        "include_conditional_mix": False,
        "kappa": 0.0,
    },
    {
        "name": "S_dressed_diagonals",
        "mu10_over_MI": 0.5,
        "mu126_over_MI": 0.5,
        "lam210_10": 0.0,
        "lam210_126": 0.0,
        "lamS_10": 1.0,
        "lamS_126": 1.0,
        "lam_mix": 0.0,
        "include_conditional_mix": False,
        "kappa": 0.1,
    },
    {
        "name": "conditional_mix_on",
        "mu10_over_MI": 1.0,
        "mu126_over_MI": 1.0,
        "lam210_10": 0.0,
        "lam210_126": 0.0,
        "lamS_10": 0.0,
        "lamS_126": 0.0,
        "lam_mix": 1.0,
        "include_conditional_mix": True,
        "kappa": 0.0,
    },
    {
        "name": "light_10_stress",
        "mu10_over_MI": 0.1,
        "mu126_over_MI": 5.0,
        "lam210_10": 0.0,
        "lam210_126": 0.0,
        "lamS_10": 0.0,
        "lamS_126": 0.0,
        "lam_mix": 0.0,
        "include_conditional_mix": False,
        "kappa": 0.01,
    },
    {
        "name": "full_allowed_O1",
        "mu10_over_MI": 1.0,
        "mu126_over_MI": 1.0,
        "lam210_10": 0.1,
        "lam210_126": 0.1,
        "lamS_10": 0.5,
        "lamS_126": 0.5,
        "lam_mix": 0.2,
        "include_conditional_mix": True,
        "kappa": 0.2,
    },
    {
        "name": "forbid_check_no_bare10",
        "mu10_over_MI": 1.0,
        "mu126_over_MI": 1.0,
        "lam210_10": 0.0,
        "lam210_126": 0.0,
        "lamS_10": 0.0,
        "lamS_126": 0.0,
        "lam_mix": 0.0,
        "include_conditional_mix": False,
        "kappa": 1.0,
    },
]


def evaluate_scenario(
    scenario: dict[str, Any],
    *,
    m_i: float,
    m_gut: float,
    tau_gauge: float,
) -> dict[str, Any]:
    v210, vS = m_gut, m_i
    mu10 = scenario["mu10_over_MI"] * m_i
    mu126 = scenario["mu126_over_MI"] * m_i
    matrix = fill_charge_allowed_mt(
        v210=v210,
        vS=vS,
        mu10=mu10,
        mu126=mu126,
        lam210_10=float(scenario["lam210_10"]),
        lam210_126=float(scenario["lam210_126"]),
        lamS_10=float(scenario["lamS_10"]),
        lamS_126=float(scenario["lamS_126"]),
        lam_mix=float(scenario["lam_mix"]),
        include_conditional_mix=bool(scenario["include_conditional_mix"]),
    )
    # Physical masses from absolute eigenvalues of the real-symmetric matrix.
    w, v = np.linalg.eigh(matrix)
    order = np.argsort(np.abs(w))
    w = w[order]
    v = v[:, order]
    light = float(abs(w[0]))
    frac10 = float(v[0, 0] ** 2)
    frac126 = float(v[1, 0] ** 2)
    if frac10 >= 0.70:
        dominance = "10_H"
    elif frac126 >= 0.70:
        dominance = "126bar_H"
    else:
        dominance = "mixed"

    mix10 = within_10_mixing_from_S(
        m_t=abs(matrix[0, 0]),
        m_tbar=abs(matrix[0, 0]) * 1.1,  # schematic split; full T/Tbar OPEN
        kappa=float(scenario["kappa"]),
        vS=vS,
    )

    singular = light <= 0.0
    ps_rows: list[dict[str, Any]] = []
    if not singular:
        for alpha_ps in (0.01, 0.1, 0.3):
            if dominance == "mixed":
                r10 = ps.evaluate_channel(
                    "10_H", "p_to_mu_K0", alpha=alpha_ps, M_T_GeV=light, M_Tbar_GeV=light
                )
                r126 = ps.evaluate_channel(
                    "126bar_H",
                    "p_to_mu_K0",
                    alpha=alpha_ps,
                    M_T_GeV=light,
                    M_Tbar_GeV=light,
                )
                row = dict(
                    r10
                    if r10["predicted_lifetime_years"] <= r126["predicted_lifetime_years"]
                    else r126
                )
                row["dominance_routing"] = "mixed_take_shorter"
            else:
                row = dict(
                    ps.evaluate_channel(
                        dominance,
                        "p_to_mu_K0",
                        alpha=alpha_ps,
                        M_T_GeV=light,
                        M_Tbar_GeV=light,
                    )
                )
                row["dominance_routing"] = dominance
            tau_s = float(row["predicted_lifetime_years"])
            row["interference_incoherent_years"] = cmt.interference_lifetime_years(
                tau_gauge, tau_s, 0.0
            )
            ps_rows.append(row)

    excluded = singular or any(not r["passes_experimental_limit"] for r in ps_rows)
    return {
        "name": scenario["name"],
        "include_conditional_10_126_S": bool(scenario["include_conditional_mix"]),
        "mass_matrix_GeV": matrix.tolist(),
        "eigenvalues_GeV": [float(x) for x in w],
        "lightest_GeV": light,
        "frac_10": frac10,
        "frac_126": frac126,
        "dominance_class": dominance,
        "within_10_mixing": mix10,
        "bare_10_squared_contribution_GeV": 0.0,
        "patel_shukla_mu_K0": ps_rows,
        "flag": {
            "charge_allowed_ops_only": True,
            "bare_10_squared_absent": True,
            "conditionally_excluded_by_ps_mu_K0": excluded,
            "singular": singular,
        },
    }


def build_report() -> dict[str, Any]:
    anchor = scalar_pd._unification_anchor()
    if not anchor.get("available"):
        return {
            "status": "NONSUSY_CHARGE_ALLOWED_MT_NOT_EXECUTED__ANCHOR_MISSING",
            "n_failed": 1,
            "failures": ["unification_anchor"],
            "flag": {"charge_allowed_mt_built": False},
        }

    m_i = float(anchor["M_I_GeV"])
    m_gut = float(anchor["M_GUT_GeV"])
    gauge = scalar_pd.gauge_proton_decay(anchor)
    tau_gauge = float(gauge["central"]["lifetime_years"])
    ledger = allowed_mt_operator_ledger()
    zrep = z17.build_report()

    # Locking amplitude scale: schematic A ~ λ_lock v_Δ² v_10² v_S² / M^2
    # with v_10 ~ v_EW effective omitted → use M_I^6 / M_GUT^2 as dim-6 estimate
    a_lock = (m_i**6) / (m_gut**2)
    phase = locking_phase_hessian(A_lock=float(a_lock))

    rows = [
        evaluate_scenario(s, m_i=m_i, m_gut=m_gut, tau_gauge=tau_gauge)
        for s in SCENARIOS
    ]
    excluded = [r for r in rows if r["flag"]["conditionally_excluded_by_ps_mu_K0"]]
    physical = [r for r in rows if not r["flag"]["singular"]]
    lightest = min(physical, key=lambda r: r["lightest_GeV"])

    # Identity: matrix with mix off has M12=0; bare10 always 0
    m_test = fill_charge_allowed_mt(
        v210=m_gut,
        vS=m_i,
        mu10=m_i,
        mu126=m_i,
        lam210_10=0.0,
        lam210_126=0.0,
        lamS_10=0.0,
        lamS_126=0.0,
        lam_mix=1.0,
        include_conditional_mix=False,
    )

    checks = {
        "anchor_available": True,
        "ledger_has_ten2_S": ledger["ten2_S_included"],
        "ledger_excludes_bare10": ledger["bare_10_squared_excluded"],
        "mix_off_forces_M12_zero": bool(abs(m_test[0, 1]) < 1e-30),
        "phase_hessian_one_positive": phase["n_positive"] == 1,
        "phase_hessian_two_zero": phase["n_zero"] == 2,
        "some_survive": len(excluded) < len(rows),
        "some_excluded": len(excluded) > 0,
        "upstream_z17_ok": zrep.get("n_failed", 1) == 0,
        "cg_normalizations_still_open": True,
        "whole_model_not_declared_dead": True,
    }
    failures = [n for n, ok in checks.items() if not ok]

    return {
        "status": (
            "NONSUSY_CHARGE_ALLOWED_MT_BUILT__CG_NORMALIZATIONS_OPEN"
            if not failures
            else "NONSUSY_CHARGE_ALLOWED_MT_FAILED"
        ),
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "sources": SOURCES,
        "operator_ledger": ledger,
        "fill_convention": {
            "M11": "μ10 + λ210_10⟨210⟩ + λS_10⟨S⟩",
            "M22": "μ126 + λ210_126⟨210⟩ + λS_126⟨S⟩",
            "M12": "λ_mix⟨S⟩ if CONDITIONAL 10·126·S included, else 0",
            "bare_10_squared": "IDENTICALLY_ZERO",
            "within_10_theta_T": "from 10_H^2 S only (κ⟨S⟩)",
        },
        "locking_phase_hessian": phase,
        "n_scenarios": len(rows),
        "n_excluded_by_ps_mu_K0": len(excluded),
        "excluded_scenario_names": [r["name"] for r in excluded],
        "lightest_scenario": {
            "name": lightest["name"],
            "lightest_GeV": lightest["lightest_GeV"],
            "dominance": lightest["dominance_class"],
            "conditional_mix": lightest["include_conditional_10_126_S"],
        },
        "scenarios": rows,
        "upstream_z17_filter_status": zrep.get("status"),
        "next_exact_calculation": [
            "Replace free λ/κ by normalized nonsusy 210^n and mixed CG contractions",
            "Resolve SO(10) existence of 10·126·S and 126^2·S singlets",
            "Extend basis beyond 2×2 (T', Tbar physical states)",
            "Complete multi-operator phase Hessian + radial-phase cross terms",
        ],
        "flag": {
            "charge_allowed_mt_built": True,
            "bare_10_squared_absent": True,
            "ten2_S_mixing_included": True,
            "conditional_10_126_S_optional": True,
            "locking_phase_hessian_computed": True,
            "complete_phase_hessian": False,
            "invented_unpublished_cg_normalizations": False,
            "complete_so10_scalar_potential": False,
            "exact_unique_proton_lifetime": False,
            "conditional_parameter_points_excluded": len(excluded) > 0,
            "whole_model_excluded": False,
        },
        "verdict": (
            "Nonsusy M_T is now built from charge-allowed operators only: bare "
            "10_H^2 is absent, 10_H^2 S supplies θ_T∼κ⟨S⟩, and optional "
            "10·126·S mixing is gated. A reduced locking phase Hessian has one "
            "massive mode. Free λ/κ await true nonsusy CG normalizations."
        ),
    }


def write_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Nonsusy charge-allowed M_T — v20",
        "",
        f"**Status:** `{report['status']}`",
        "",
        report["verdict"],
        "",
        f"- Scenarios: {report['n_scenarios']}",
        f"- Excluded by PS μ⁺K⁰: {report['n_excluded_by_ps_mu_K0']}",
        f"- Lightest: `{report['lightest_scenario']['name']}` at "
        f"{report['lightest_scenario']['lightest_GeV']:.3e} GeV",
        "",
        "## Fill convention",
        "",
        f"- M11 = `{report['fill_convention']['M11']}`",
        f"- M22 = `{report['fill_convention']['M22']}`",
        f"- M12 = `{report['fill_convention']['M12']}`",
        f"- bare 10²: `{report['fill_convention']['bare_10_squared']}`",
        "",
        "## Phase Hessian (locking)",
        "",
        f"- Positive modes: {report['locking_phase_hessian']['n_positive']}",
        f"- Zero modes: {report['locking_phase_hessian']['n_zero']}",
        "",
        "## Next exact calculation",
        "",
    ]
    for step in report["next_exact_calculation"]:
        lines.append(f"1. {step}")
    lines.extend(["", "## Flags", ""])
    for k, v in report["flag"].items():
        lines.append(f"- `{k}`: {v}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args(argv)
    report = build_report()
    ROOT.joinpath("NONSUSY_CHARGE_ALLOWED_MT_V20_VERDICT.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    ROOT.joinpath("NONSUSY_CHARGE_ALLOWED_MT_V20.md").write_text(
        write_markdown(report), encoding="utf-8"
    )
    print(
        json.dumps(
            {
                "status": report["status"],
                "n_failed": report["n_failed"],
                "n_scenarios": report.get("n_scenarios"),
                "n_excluded": report.get("n_excluded_by_ps_mu_K0"),
                "lightest": report.get("lightest_scenario"),
                "phase": {
                    "n_positive": report.get("locking_phase_hessian", {}).get(
                        "n_positive"
                    ),
                    "n_zero": report.get("locking_phase_hessian", {}).get("n_zero"),
                },
                "flag": report.get("flag"),
                "verdict": report.get("verdict"),
            },
            indent=2,
        )
    )
    return 0 if report.get("n_failed", 1) == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
