#!/usr/bin/env python3
"""Sample the full complex three-family portal-orientation sphere for v20.

At fixed portal norm and the previously solved ordered-heavy y_Q, draw a
low-discrepancy sample of complex vectors

    lam_Q_F = kappa * z,  z in C^3, ||z||_2 = 1.

The chosen orientation measure is the rotationally invariant (Haar) measure on
the real five-sphere S^5, generated by normalized complex Gaussian vectors.
Scrambled Sobol replicates make the calculation deterministic and provide a
replicate-spread diagnostic.  This geometric measure is not a UV prior,
posterior, probability of nature, or scan of the remaining portal magnitudes.
"""
from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Iterable

import numpy as np
from scipy.stats import norm, qmc

import channel_fcnc_rates_v20 as rates
import na62_pointwise_limit_v20 as na62
import physical_cf_matching_v20 as physical
import portal_boundary_heavy_spectrum_v20 as spectrum
import portal_family_orientation_map_v20 as plane
import portal_tensors_abcd_v20 as portals
import twist_massless_limit_v20 as twist

ROOT = Path(__file__).resolve().parent
KAPPA = plane.KAPPA
LAM_Q_R = plane.LAM_Q_R
LAM_S_Q_RBAR = plane.LAM_S_Q_RBAR
SOBOL_SEEDS = (1701, 1709, 1721, 1733, 1747, 1753, 1777, 1789)
SOBOL_POWER = 11  # 2048 orientations per replicate; 16384 total.


def ordered_yq() -> float:
    scan = spectrum.solve_lightest_equals_vS()
    boundary = scan["unique_ordering_boundary"]
    if boundary is None:
        raise RuntimeError("ordered-heavy boundary was not uniquely solved")
    return float(boundary["y_Q"])


def normalize_complex_vector(values: Iterable[complex], *, kappa: float = KAPPA) -> np.ndarray:
    vector = np.asarray(list(values), dtype=complex)
    if vector.shape != (3,):
        raise ValueError("expected exactly three complex family components")
    if not np.all(np.isfinite(vector.real)) or not np.all(np.isfinite(vector.imag)):
        raise ValueError("family components must be finite")
    if not math.isfinite(kappa) or kappa <= 0.0:
        raise ValueError("kappa must be finite and positive")
    norm_value = float(np.linalg.norm(vector))
    if norm_value <= 0.0:
        raise ValueError("family vector norm must be positive")
    return kappa * vector / norm_value


def sobol_complex_vectors(*, seed: int, power: int = SOBOL_POWER) -> np.ndarray:
    if power < 2:
        raise ValueError("Sobol power must be at least two")
    sampler = qmc.Sobol(d=6, scramble=True, seed=int(seed))
    unit = sampler.random_base2(m=power)
    clipped = np.clip(unit, 1.0e-12, 1.0 - 1.0e-12)
    gaussian = norm.ppf(clipped)
    vectors = gaussian[:, :3] + 1j * gaussian[:, 3:]
    norms = np.linalg.norm(vectors, axis=1)
    if np.any(~np.isfinite(norms)) or np.any(norms <= 0.0):
        raise ValueError("Sobol-to-Gaussian map produced an invalid vector")
    return KAPPA * vectors / norms[:, None]


def portal_block(vector: np.ndarray, *, y_q: float) -> dict[str, Any]:
    normalized = normalize_complex_vector(vector)
    return portals.build_abcd(
        portals.PortalCouplings(
            y_Q=y_q,
            lam_Q_F=tuple(complex(z) for z in normalized),
            lam_Q_R=LAM_Q_R,
            lam_S_Q_Rbar=LAM_S_Q_RBAR,
        )
    )


def heavy_singular_values(block: dict[str, Any]) -> np.ndarray:
    top = np.hstack(
        [np.asarray(block["A"], dtype=complex), np.asarray(block["C"], dtype=complex)]
    )
    bottom = np.hstack(
        [
            np.asarray(block["B"], dtype=complex),
            np.asarray([[block["D"]]], dtype=complex),
        ]
    )
    values = np.sort(np.linalg.svd(np.vstack([top, bottom]), compute_uv=False))
    if values.shape != (3,) or np.min(values) <= 0.0 or not np.all(np.isfinite(values)):
        raise ValueError("expected three finite positive heavy singular values")
    return values


def experimental_limits() -> tuple[float, float]:
    anchor = na62.load_anchor()
    kaon = float(
        na62.observed_limit_at_mass(na62.TARGET_MASS_MEV, anchor)[
            "observed_br_ul_90cl"
        ]
    )
    muon = min(
        float(row["branching_ratio_upper_limit_90cl"])
        for row in twist.load_limits()["limits"]
    )
    return kaon, muon


def complex_payload(vector: np.ndarray) -> list[dict[str, float]]:
    return [
        {"re": float(z.real), "im": float(z.imag), "abs": float(abs(z))}
        for z in np.asarray(vector, dtype=complex)
    ]


def evaluate_vector(
    vector: np.ndarray,
    *,
    y_q: float,
    bases: dict[str, Any],
    na62_limit: float,
    twist_limit: float,
) -> dict[str, Any]:
    normalized = normalize_complex_vector(vector)
    block = portal_block(normalized, y_q=y_q)
    result = rates.scenario_rates("full_complex_orientation", block, bases)
    br_k = float(result["K_to_pi_a"]["branching_ratio"])
    br_mu = float(result["mu_to_e_a"]["branching_ratio"])
    singular = heavy_singular_values(block)
    return {
        "lam_Q_F": complex_payload(normalized),
        "norm": float(np.linalg.norm(normalized)),
        "BR_K_to_pi_a": br_k,
        "NA62_ratio": float(br_k / na62_limit),
        "NA62_excluded": bool(br_k > na62_limit),
        "BR_mu_to_e_a": br_mu,
        "TWIST_ratio": float(br_mu / twist_limit),
        "TWIST_excluded_strongest_published_case": bool(br_mu > twist_limit),
        "lightest_heavy_singular_GeV": float(singular[0]),
        "lightest_heavy_over_vS": float(singular[0] / portals.VS),
    }


def _replace_extreme(
    current: dict[str, Any] | None,
    candidate: dict[str, Any],
    key: str,
    *,
    maximize: bool,
) -> dict[str, Any]:
    if current is None:
        return dict(candidate)
    left = float(current[key])
    right = float(candidate[key])
    if (right > left) if maximize else (right < left):
        return dict(candidate)
    return current


def scan_replicate(
    *,
    seed: int,
    power: int,
    y_q: float,
    bases: dict[str, Any],
    na62_limit: float,
    twist_limit: float,
) -> dict[str, Any]:
    vectors = sobol_complex_vectors(seed=seed, power=power)
    counts = {
        "n_points": int(vectors.shape[0]),
        "n_NA62_excluded": 0,
        "n_TWIST_excluded": 0,
    }
    extrema: dict[str, dict[str, Any] | None] = {
        "min_NA62_ratio": None,
        "max_NA62_ratio": None,
        "min_TWIST_ratio": None,
        "max_TWIST_ratio": None,
    }
    reference_heavy: float | None = None
    max_heavy_relative_drift = 0.0
    norm_drift = 0.0
    for index, vector in enumerate(vectors):
        row = evaluate_vector(
            vector,
            y_q=y_q,
            bases=bases,
            na62_limit=na62_limit,
            twist_limit=twist_limit,
        )
        row["replicate_seed"] = int(seed)
        row["sample_index"] = int(index)
        counts["n_NA62_excluded"] += int(row["NA62_excluded"])
        counts["n_TWIST_excluded"] += int(
            row["TWIST_excluded_strongest_published_case"]
        )
        extrema["min_NA62_ratio"] = _replace_extreme(
            extrema["min_NA62_ratio"], row, "NA62_ratio", maximize=False
        )
        extrema["max_NA62_ratio"] = _replace_extreme(
            extrema["max_NA62_ratio"], row, "NA62_ratio", maximize=True
        )
        extrema["min_TWIST_ratio"] = _replace_extreme(
            extrema["min_TWIST_ratio"], row, "TWIST_ratio", maximize=False
        )
        extrema["max_TWIST_ratio"] = _replace_extreme(
            extrema["max_TWIST_ratio"], row, "TWIST_ratio", maximize=True
        )
        heavy = float(row["lightest_heavy_singular_GeV"])
        if reference_heavy is None:
            reference_heavy = heavy
        max_heavy_relative_drift = max(
            max_heavy_relative_drift, abs(heavy / reference_heavy - 1.0)
        )
        norm_drift = max(norm_drift, abs(float(row["norm"]) / KAPPA - 1.0))
    n_points = counts["n_points"]
    counts.update(
        {
            "n_NA62_surviving": n_points - counts["n_NA62_excluded"],
            "n_TWIST_surviving": n_points - counts["n_TWIST_excluded"],
            "NA62_excluded_fraction_under_chosen_geometric_measure": float(
                counts["n_NA62_excluded"] / n_points
            ),
            "TWIST_excluded_fraction_under_chosen_geometric_measure": float(
                counts["n_TWIST_excluded"] / n_points
            ),
        }
    )
    return {
        "seed": int(seed),
        "power": int(power),
        "counts": counts,
        "extrema": extrema,
        "max_norm_relative_drift": float(norm_drift),
        "max_heavy_relative_drift": float(max_heavy_relative_drift),
    }


def anchor_vectors() -> dict[str, np.ndarray]:
    original = np.asarray((1.0 + 0.0j, 0.01 + 0.0j, 0.0 + 0.0j))
    return {
        "F1": normalize_complex_vector((1.0, 0.0, 0.0)),
        "F2": normalize_complex_vector((0.0, 1.0, 0.0)),
        "F3": normalize_complex_vector((0.0, 0.0, 1.0)),
        "equal_real": normalize_complex_vector((1.0, 1.0, 1.0)),
        "equal_120deg": normalize_complex_vector(
            (1.0, np.exp(2j * math.pi / 3.0), np.exp(4j * math.pi / 3.0))
        ),
        "original_direction": normalize_complex_vector(original),
        "original_common_phase_pi2": normalize_complex_vector(1j * original),
    }


def scan_full_sphere(
    *,
    seeds: tuple[int, ...] = SOBOL_SEEDS,
    power: int = SOBOL_POWER,
) -> dict[str, Any]:
    if len(seeds) < 2:
        raise ValueError("at least two scrambled replicates are required")
    y_q = ordered_yq()
    bases = physical.flavour_mass_bases()
    na62_limit, twist_limit = experimental_limits()
    replicates = [
        scan_replicate(
            seed=seed,
            power=power,
            y_q=y_q,
            bases=bases,
            na62_limit=na62_limit,
            twist_limit=twist_limit,
        )
        for seed in seeds
    ]
    total_points = sum(int(row["counts"]["n_points"]) for row in replicates)
    total_na62_excluded = sum(
        int(row["counts"]["n_NA62_excluded"]) for row in replicates
    )
    total_twist_excluded = sum(
        int(row["counts"]["n_TWIST_excluded"]) for row in replicates
    )
    na62_fractions = np.asarray(
        [
            float(
                row["counts"][
                    "NA62_excluded_fraction_under_chosen_geometric_measure"
                ]
            )
            for row in replicates
        ]
    )
    twist_fractions = np.asarray(
        [
            float(
                row["counts"][
                    "TWIST_excluded_fraction_under_chosen_geometric_measure"
                ]
            )
            for row in replicates
        ]
    )
    global_extrema: dict[str, dict[str, Any] | None] = {
        "min_NA62_ratio": None,
        "max_NA62_ratio": None,
        "min_TWIST_ratio": None,
        "max_TWIST_ratio": None,
    }
    for replicate in replicates:
        for name, maximize in (
            ("min_NA62_ratio", False),
            ("max_NA62_ratio", True),
            ("min_TWIST_ratio", False),
            ("max_TWIST_ratio", True),
        ):
            key = "NA62_ratio" if "NA62" in name else "TWIST_ratio"
            global_extrema[name] = _replace_extreme(
                global_extrema[name], replicate["extrema"][name], key, maximize=maximize
            )
    anchors = {
        name: evaluate_vector(
            vector,
            y_q=y_q,
            bases=bases,
            na62_limit=na62_limit,
            twist_limit=twist_limit,
        )
        for name, vector in anchor_vectors().items()
    }
    return {
        "configuration": {
            "space": "complex three-family orientation sphere S^5",
            "fixed_norm_kappa": KAPPA,
            "fixed_lam_Q_R": LAM_Q_R,
            "fixed_lam_S_Q_Rbar": LAM_S_Q_RBAR,
            "ordered_y_Q": y_q,
            "sampling_measure": (
                "rotationally invariant Haar measure on S^5 via normalized complex "
                "Gaussian vectors generated by scrambled Sobol points"
            ),
            "sobol_seeds": list(seeds),
            "sobol_power": int(power),
            "points_per_replicate": int(2**power),
            "n_replicates": len(seeds),
            "n_total_points": total_points,
        },
        "limits": {
            "NA62_observed_br_upper_limit_90cl": na62_limit,
            "TWIST_strongest_published_br_upper_limit_90cl": twist_limit,
        },
        "aggregate_counts": {
            "n_total_points": total_points,
            "n_NA62_excluded": total_na62_excluded,
            "n_NA62_surviving": total_points - total_na62_excluded,
            "n_TWIST_excluded": total_twist_excluded,
            "n_TWIST_surviving": total_points - total_twist_excluded,
            "NA62_excluded_fraction_under_chosen_geometric_measure": float(
                total_na62_excluded / total_points
            ),
            "TWIST_excluded_fraction_under_chosen_geometric_measure": float(
                total_twist_excluded / total_points
            ),
            "geometric_fraction_is_uv_probability": False,
        },
        "replicate_fraction_diagnostics": {
            "NA62_replicate_fractions": [float(x) for x in na62_fractions],
            "NA62_mean": float(np.mean(na62_fractions)),
            "NA62_sample_standard_deviation": float(np.std(na62_fractions, ddof=1)),
            "NA62_standard_error_of_replicate_mean": float(
                np.std(na62_fractions, ddof=1) / math.sqrt(len(na62_fractions))
            ),
            "NA62_min": float(np.min(na62_fractions)),
            "NA62_max": float(np.max(na62_fractions)),
            "TWIST_replicate_fractions": [float(x) for x in twist_fractions],
            "TWIST_mean": float(np.mean(twist_fractions)),
            "replicate_spread_is_not_a_uv_posterior_uncertainty": True,
        },
        "replicates": replicates,
        "anchors": anchors,
        "sampled_extrema": global_extrema,
        "heavy_spectrum": {
            "max_relative_drift_across_replicates": float(
                max(row["max_heavy_relative_drift"] for row in replicates)
            ),
            "max_norm_relative_drift": float(
                max(row["max_norm_relative_drift"] for row in replicates)
            ),
        },
    }


def build_report() -> dict[str, Any]:
    scan = scan_full_sphere()
    counts = scan["aggregate_counts"]
    anchors = scan["anchors"]
    extrema = scan["sampled_extrema"]
    checks = {
        "expected_sample_size": counts["n_total_points"]
        == len(SOBOL_SEEDS) * 2**SOBOL_POWER,
        "original_anchor_survives_NA62": not anchors["original_direction"][
            "NA62_excluded"
        ],
        "original_anchor_survives_TWIST": not anchors["original_direction"][
            "TWIST_excluded_strongest_published_case"
        ],
        "na62_has_excluded_samples": counts["n_NA62_excluded"] > 0,
        "na62_has_surviving_samples": counts["n_NA62_surviving"] > 0,
        "twist_count_accounting": counts["n_TWIST_excluded"]
        + counts["n_TWIST_surviving"]
        == counts["n_total_points"],
        "na62_count_accounting": counts["n_NA62_excluded"]
        + counts["n_NA62_surviving"]
        == counts["n_total_points"],
        "na62_extrema_ordered": float(extrema["min_NA62_ratio"]["NA62_ratio"])
        <= float(extrema["max_NA62_ratio"]["NA62_ratio"]),
        "twist_extrema_ordered": float(extrema["min_TWIST_ratio"]["TWIST_ratio"])
        <= float(extrema["max_TWIST_ratio"]["TWIST_ratio"]),
        "fixed_norm_preserved": scan["heavy_spectrum"]["max_norm_relative_drift"]
        < 1.0e-12,
        "heavy_spectrum_orientation_invariant": scan["heavy_spectrum"][
            "max_relative_drift_across_replicates"
        ]
        < 1.0e-10,
        "geometric_fraction_not_uv_probability": not counts[
            "geometric_fraction_is_uv_probability"
        ],
        "remaining_portal_magnitudes_not_claimed_scanned": True,
        "uv_posterior_not_claimed": True,
        "whole_model_exclusion_not_claimed": True,
    }
    failures = [name for name, ok in checks.items() if not ok]
    return {
        "status": (
            "FULL_COMPLEX_THREE_FAMILY_ORIENTATION_SPHERE_SAMPLED__GEOMETRIC_MEASURE_RECORDED__FULL_PORTAL_MODEL_OPEN"
            if not failures
            else "FULL_COMPLEX_ORIENTATION_SPHERE_AUDIT_FAILED"
        ),
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "scan": scan,
        "flag": {
            "full_complex_three_family_orientation_sphere_sampled": True,
            "rotationally_invariant_orientation_measure_explicit": True,
            "scrambled_sobol_replicates_executed": True,
            "NA62_has_excluded_samples": counts["n_NA62_excluded"] > 0,
            "NA62_has_surviving_samples": counts["n_NA62_surviving"] > 0,
            "TWIST_has_excluded_samples": counts["n_TWIST_excluded"] > 0,
            "TWIST_has_surviving_samples": counts["n_TWIST_surviving"] > 0,
            "geometric_fraction_is_uv_probability": False,
            "all_portal_magnitudes_and_phases_scanned": False,
            "portal_yukawa_posterior_derived": False,
            "component_specific_uv_chiral_currents_derived": False,
            "continuous_experimental_likelihoods_implemented": False,
            "whole_v20_model_excluded": False,
        },
        "interpretation": (
            "The complex three-family orientation at fixed portal norm is now sampled "
            "with an explicit rotationally invariant geometric measure. The resulting "
            "excluded fraction describes only that chosen orientation measure with all "
            "other portal magnitudes and matching assumptions fixed. It is not a UV "
            "probability or posterior and cannot establish whole-model exclusion."
        ),
        "remaining_for_full_portal_inference": [
            "vary y_Q and the portal norm jointly with the full complex orientation",
            "vary lam_Q_R, lam_S_Q_Rbar, and all remaining portal magnitudes/phases",
            "derive component-specific left/right currents through threshold matching",
            "derive or fit a UV prior/posterior over portal tensors",
            "use continuous experimental likelihoods and nuisance correlations",
        ],
    }


def write_markdown(report: dict[str, Any]) -> str:
    scan = report["scan"]
    counts = scan["aggregate_counts"]
    diagnostics = scan["replicate_fraction_diagnostics"]
    extrema = scan["sampled_extrema"]
    return "\n".join(
        [
            "# Full complex three-family portal-orientation sphere — v20",
            "",
            f"**Status:** `{report['status']}`",
            "",
            f"- sampled orientations: {counts['n_total_points']}",
            f"- NA62 excluded samples: {counts['n_NA62_excluded']}",
            f"- NA62 surviving samples: {counts['n_NA62_surviving']}",
            f"- chosen-measure NA62 excluded fraction: {counts['NA62_excluded_fraction_under_chosen_geometric_measure']:.12g}",
            f"- replicate range: [{diagnostics['NA62_min']:.12g}, {diagnostics['NA62_max']:.12g}]",
            f"- TWIST excluded samples: {counts['n_TWIST_excluded']}",
            f"- sampled min NA62 ratio: {extrema['min_NA62_ratio']['NA62_ratio']:.12e}",
            f"- sampled max NA62 ratio: {extrema['max_NA62_ratio']['NA62_ratio']:.12e}",
            f"- sampled max TWIST ratio: {extrema['max_TWIST_ratio']['TWIST_ratio']:.12e}",
            "",
            "The geometric fraction is not a UV probability or posterior.",
            "",
            report["interpretation"],
            "",
        ]
    )


def main() -> int:
    report = build_report()
    ROOT.joinpath("PORTAL_FULL_COMPLEX_ORIENTATION_SPHERE_V20_VERDICT.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    ROOT.joinpath("PORTAL_FULL_COMPLEX_ORIENTATION_SPHERE_V20.md").write_text(
        write_markdown(report), encoding="utf-8"
    )
    scan = report["scan"]
    print(
        json.dumps(
            {
                "status": report["status"],
                "n_failed": report["n_failed"],
                "configuration": scan["configuration"],
                "aggregate_counts": scan["aggregate_counts"],
                "replicate_fraction_diagnostics": scan[
                    "replicate_fraction_diagnostics"
                ],
                "anchors": scan["anchors"],
                "sampled_extrema": scan["sampled_extrema"],
                "heavy_spectrum": scan["heavy_spectrum"],
                "flags": report["flag"],
            },
            indent=2,
        )
    )
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
