#!/usr/bin/env python3
"""Exact selected-vacuum test of the lambda4 Phi-H-Sigmabar-S portal.

The full map T_Phi:126bar->10 is nonzero and gives an exact off-diagonal
fluctuation mass block lambda4*vS*T_Phi. This does not imply that the portal
has a nonzero value on the selected vacuum.

This module evaluates T_Phi Delta_R for each canonical 210 singlet and for the
repository p,a,omega combination. The result is identically zero. Therefore

* V_lambda4 on (Phi,Delta_R,H_EW,S) is zero for every H direction;
* first derivatives generated by a scalar proxy p*Delta*h*S are absent;
* the full fluctuation mixing T_Phi remains nonzero on other 126bar modes.

Vacuum value and component fluctuation mixing are distinct statements.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np

import direct_phi_h_sigmabar_tensor_v20 as direct
import direct_phi_h_sigmabar_td_crosscheck_v20 as td
import scalar_vacuum_proton_decay_v20 as scalar_pd

ROOT = Path(__file__).resolve().parent
OUT_JSON = ROOT / "SELECTED_VACUUM_LAMBDA4_PORTAL_NULL_AUDIT_V20.json"
OUT_MD = ROOT / "SELECTED_VACUUM_LAMBDA4_PORTAL_NULL_AUDIT_V20.md"


def image_of_delta(phi: direct.Form) -> direct.Form:
    return direct.contract(phi, direct.delta_r())


def build_report() -> dict[str, Any]:
    anchor = scalar_pd._unification_anchor()
    m_gut = float(anchor["M_GUT_GeV"])
    singlets = direct.singlet_basis()
    sigma_basis = direct.anti_self_dual_five_form_basis()

    basis_images = {
        name: direct.tensor_norm(image_of_delta(state))
        for name, state in singlets.items()
    }
    selected_aulakh = {
        "p": 0.20 * m_gut,
        "a": 0.30 * m_gut,
        "omega": 0.50 * m_gut,
    }
    canonical = td.aulakh_to_canonical_singlets(**selected_aulakh)
    phi = direct.add_forms(
        *[
            direct.scale_form(singlets[name], value)
            for name, value in canonical.items()
        ]
    )
    selected_image = image_of_delta(phi)
    selected_image_norm = direct.tensor_norm(selected_image)
    full_matrix = direct.contraction_matrix(phi, sigma_basis)
    full_singular = np.linalg.svd(full_matrix, compute_uv=False)
    full_rank = int(np.sum(full_singular > 1e-12 * max(full_singular[0], 1.0)))

    # The direct Delta_R basis vector is normalized; verify it is in the null
    # space of the selected matrix by projecting it into the canonical basis.
    delta = direct.delta_r()
    delta_coefficients = np.array(
        [direct.sigma_kinetic_inner(state, delta) for state in sigma_basis],
        dtype=complex,
    )
    matrix_image = full_matrix @ delta_coefficients
    matrix_image_norm = float(np.linalg.norm(matrix_image))
    delta_reconstruction = direct.add_forms(
        *[
            direct.scale_form(state, coefficient)
            for state, coefficient in zip(sigma_basis, delta_coefficients)
        ]
    )
    reconstruction_residual = direct.tensor_norm(
        direct.add_forms(delta_reconstruction, direct.scale_form(delta, -1.0))
    )

    checks = {
        "DeltaR_canonical_norm": abs(direct.sigma_kinetic_norm(delta) - 1.0) < 1e-12,
        "p_image_of_DeltaR_zero": basis_images["p"] < 1e-12,
        "a_image_of_DeltaR_zero": basis_images["a"] < 1e-12,
        "omega_image_of_DeltaR_zero": basis_images["omega"] < 1e-12,
        "selected_combination_image_zero": selected_image_norm < 1e-6,
        "matrix_null_vector_check": matrix_image_norm < 1e-6,
        "DeltaR_basis_reconstruction": reconstruction_residual < 1e-10,
        "full_portal_map_nonzero": full_rank > 0 and float(full_singular[0]) > 0.0,
        "whole_model_not_overclaimed": True,
    }
    failures = [name for name, ok in checks.items() if not ok]

    return {
        "status": (
            "SELECTED_DELTAR_IN_KERNEL_OF_LAMBDA4_PORTAL__FLUCTUATION_MAP_RETAINED"
            if not failures
            else "SELECTED_VACUUM_LAMBDA4_NULL_AUDIT_FAILED"
        ),
        "overall_state": "BLOCKED",
        "n_checks": len(checks),
        "n_failed": len(failures),
        "failures": failures,
        "checks": checks,
        "selected_vevs": {
            "aulakh": selected_aulakh,
            "canonical": canonical,
        },
        "vacuum_contraction": {
            "basis_image_norms": basis_images,
            "selected_image_norm": selected_image_norm,
            "selected_image_components": {
                str(index[0]): [float(value.real), float(value.imag)]
                for index, value in selected_image.items()
            },
            "matrix_image_norm": matrix_image_norm,
            "DeltaR_basis_reconstruction_residual": reconstruction_residual,
            "conclusion": "T_Phi Delta_R = 0 for all p,a,omega singlet combinations",
        },
        "fluctuation_map": {
            "shape": list(full_matrix.shape),
            "rank": full_rank,
            "largest_singular_value_GeV": float(full_singular[0]),
            "nonzero": full_rank > 0,
            "interpretation": (
                "lambda4*vS*T_Phi remains a physical H-Sigmabar fluctuation "
                "mass-squared block for non-Delta_R component directions"
            ),
        },
        "withdrawn_selected_vacuum_claims": {
            "radial_proxy_minus_lambda4_p_Delta_h_S": True,
            "lambda4_vacuum_phase_curvature_on_DeltaR_H_S": True,
            "lambda4_stationarity_shifts_from_selected_DeltaR_vacuum": True,
            "historical_lambda4_radial_tachyon_as_full_physical_result": True,
        },
        "retained_results": {
            "direct_10x126_tensor_map": True,
            "analytic_3plus3plus2plus2_spectrum": True,
            "portal_offdiagonal_fluctuation_mass_block": True,
            "Schur_positivity_theorem_for_future_physical_diagonals": True,
        },
        "flags": {
            "selected_DeltaR_is_portal_null_vector": not bool(failures),
            "selected_vacuum_lambda4_amplitude_nonzero": False,
            "full_fluctuation_portal_map_nonzero": True,
            "historical_reduced_lambda4_vacuum_term_physical": False,
            "whole_model_validated": False,
            "whole_model_excluded": False,
        },
        "remaining_blockers": {
            "rebuild_stationarity_without_fake_lambda4_radial_monomial": True,
            "rebuild_phase_hessian_with_only_nonzero_vacuum_operators": True,
            "derive_full_component_diagonal_hessian": True,
            "search_alternative_nonzero_phase_sensitive_invariant": True,
        },
        "verdict": (
            "The selected physical Delta_R direction is an exact null vector "
            "of T_Phi for every 210 singlet combination p,a,omega. Thus the "
            "lambda4 portal has zero selected-vacuum value and cannot generate "
            "the historical radial monomial or phase curvature. The full "
            "10x126 fluctuation map remains nonzero and its Schur analysis is "
            "retained. Vacuum and fluctuation claims must now be separated."
        ),
    }


def write_report(report: dict[str, Any]) -> None:
    OUT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    OUT_MD.write_text(
        "# Selected-vacuum lambda4 portal null audit — v20\n\n"
        f"**Status:** `{report['status']}`\n\n"
        f"- ||T_Phi Delta_R||: `{report['vacuum_contraction']['selected_image_norm']}`\n"
        f"- Full map rank: `{report['fluctuation_map']['rank']}`\n\n"
        + report["verdict"]
        + "\n",
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    report = build_report()
    if args.write:
        write_report(report)
    print(json.dumps(report, indent=2))
    return 0 if report["n_failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
