from __future__ import annotations

import math
import subprocess
import sys

import susy_v33_derivation_campaign as v33


REPORT, EVIDENCE = v33.build_bundle()
EXACT = EVIDENCE[v33.EXACT_JSON.name]
GATES = EVIDENCE[v33.GATES_JSON.name]
NEW_PHYSICS = EVIDENCE[v33.NEW_PHYSICS_JSON.name]


def test_finite_internal_symmetry_no_go_has_no_scanned_x5_counterexample() -> None:
    no_go = EXACT["finite_symmetry_no_go"]
    assert no_go["ZN_scan_maximum_modulus"] == 256
    assert no_go["ZN_assignments_allowing_X_and_X3"] == 383
    assert no_go["ZN_assignments_forbidding_X5"] == 0
    assert no_go["Z4R_Z11_X_tower_first_terms"] == list(range(1, 26, 2))
    assert no_go["applies_to_nonabelian_finite_groups"].startswith("yes:")
    assert (
        no_go[
            "FCMA18_derivable_from_any_finite_internal_symmetry_with_neutral_coefficients"
        ]
        is False
    )


def test_z33_selector_preserves_exactly_the_v24_renormalizable_operator_set() -> None:
    selector = EXACT["Z33_selector"]
    rows = selector["renormalizable_operator_rows"]
    expected = {
        tuple(sorted(operator["monomial"]))
        for operator in v33.v24.RENORMALIZABLE_OPERATORS
    }
    observed = {tuple(sorted(row["monomial"])) for row in rows}

    assert selector["candidate"] == "PSZ4RZ33SUSYV33"
    assert selector["renormalizable_gauge_invariant_selector_count"] == 18
    assert len(rows) == 18
    assert observed == expected
    assert all(row["PS_singlet_multiplicity"] == 1 for row in rows)
    assert all(row["Z4R_sum_mod4"] == 2 for row in rows)
    assert all(row["Z33_sum_mod33"] == 0 for row in rows)


def test_z33_visible_gravity_congruence_passes_but_product_anomaly_stays_open() -> None:
    selector = EXACT["Z33_selector"]
    gauge = selector["mixed_gauge_anomaly"]
    gravity = selector["visible_gravitational_congruence"]
    cubic = selector["visible_cubic_arithmetic"]
    product = selector["mixed_product_anomaly_boundary"]

    assert gauge["raw_each_PS_factor"] == -2
    assert gauge["residue_mod33_each_PS_factor"] == (-2) % 33 == 31
    assert gauge["universal"] is True
    assert gravity["raw_signed"] == -15
    assert gravity["residue_mod33"] == (-15) % 33 == 18
    assert gravity["24rho_mod33"] == (24 * gauge["raw_each_PS_factor"]) % 33
    assert (gravity["raw_signed"] - 24 * gauge["raw_each_PS_factor"]) % 33 == 0
    assert gravity["passes_V24_convention"] is True
    assert cubic["microscopic_counterterm_derived"] is False
    assert product["residue_mod33"] == (-63) % 33 == 3
    assert product["nonzero_witnesses_require_UV_counterterm_or_cobordism_audit"] is True
    assert selector["full_product_discrete_gauge_anomaly_completion_established"] is False


def test_p33_is_the_first_pure_p_term_and_repairs_the_quality_estimate() -> None:
    selector = EXACT["Z33_selector"]
    quality = selector[
        "conditional_quality_assuming_A_N_1e4_GeV_unit_Wilson_and_P_equals_vP"
    ]
    z11 = quality["Z11_control"]
    z33 = quality["Z33_repair"]
    bound = quality["strong_CP_reference_bound"]
    p_tower = EXACT["finite_symmetry_no_go"]["Z4R_Z33_P_tower_first_terms"]

    assert selector["first_pure_P_superpotential_power"] == 33
    assert p_tower == [33, 99, 165, 231, 297]
    assert all(power % 33 == 0 and power % 2 == 1 for power in p_tower)
    assert z11["harmonic"] == 11
    assert z33["harmonic"] == 33
    assert z11["theta_bar_unit_coefficient_phase"] > bound
    assert z33["theta_bar_unit_coefficient_phase"] < 1.0e-150 < bound
    assert math.isclose(
        z33["log10_theta_bar_unit_coefficient_phase"],
        math.log10(z33["theta_bar_unit_coefficient_phase"]),
        abs_tol=1.0e-12,
    )
    assert "theta=(N/NDW)" in z33["formula"]
    assert z33["assumptions"]["PQ_soft_A_N_GeV"] == 1.0e4
    assert z33["assumptions"]["absolute_Wilson_coefficient"] == 1.0
    assert z33["assumptions"]["P_amplitude_convention"].startswith("|P|=vP")
    assert selector["P_VEV_stabilizer"] == "Z2 generated by the square of Z4R"
    assert selector["residual_matter_parity_exact_in_visible_EFT"] is True


def test_controlled_instanton_polynomial_is_exact_but_microscopic_geometry_is_open() -> None:
    repair = EXACT["controlled_instanton_repair"]
    k = repair["K"]

    assert k == 22027
    assert repair["integer_coefficients"] == [1, -2 * k, k**2]
    assert math.isclose(repair["x_star"], 1.0 / k, rel_tol=1.0e-15)
    assert math.isclose(repair["instanton_action"], math.log(k), rel_tol=1.0e-15)
    assert repair["instanton_action"] > 10.0
    assert math.isclose(repair["W_TT_over_C"], 8.0 * math.pi**2 / k)
    assert math.isclose(
        repair["omitted_order_one_x4_relative_to_retained_term"],
        repair["x_star"] ** 3,
        rel_tol=1.0e-15,
    )
    assert repair["rank_for_51_nonzero_Ci"] == 51
    assert repair["required_coefficient_charges"] == [
        {"harmonic": 1, "Z4R": 0, "Z33": 2},
        {"harmonic": 2, "Z4R": 2, "Z33": 4},
        {"harmonic": 3, "Z4R": 0, "Z33": 6},
    ]
    assert repair["all_terms_have_superpotential_charge_Z4R_Z33"] == [2, 0]
    assert repair["repairs_V30_local_action_control"] is True
    assert repair["repairs_V30_covariance_conditionally"] is True
    assert repair["microscopic_geometry_established"] is False


def test_component_accounting_hessian_and_split_ps_vector_spectrum_are_consistent() -> None:
    spectrum = EXACT["component_spectrum_and_vacuum"]
    hessian = spectrum["exact_PS_breaking_W_Hessian"]
    vectors = spectrum["PS_vectors"]
    neutralinos = spectrum["tree_neutralinos"]
    charginos = spectrum["tree_charginos"]

    assert spectrum["visible_complex_chiral_component_count"] == 111
    assert spectrum["PS_broken_generators_and_eaten_chirals"] == 9
    assert spectrum["physical_chiral_multiplets_after_PS_super_Higgs"] == 111 - 9
    assert hessian["dimension"] == [23, 23]
    assert hessian["rank"] + hessian["nullity"] == 23
    assert hessian["nullity"] == 9
    assert sum(row["multiplicity"] for row in hessian["mass_squared_classes"]) == 14
    assert sum(vectors["multiplicities"]) == 9
    assert len(set(vectors["masses_GeV"])) == 3
    assert vectors["V31_ninefold_degenerate_row_valid"] is False
    assert neutralinos["physical_masses_GeV"] == sorted(
        neutralinos["physical_masses_GeV"]
    )
    assert charginos["physical_singular_values_GeV"] == sorted(
        charginos["physical_singular_values_GeV"]
    )
    assert all(mass > 0.0 for mass in neutralinos["physical_masses_GeV"])
    assert all(mass > 0.0 for mass in charginos["physical_singular_values_GeV"])
    assert neutralinos["pole_self_energies_calculated"] is False
    assert charginos["pole_self_energies_calculated"] is False


def test_tree_vacuum_diagnostics_do_not_select_a_unique_full_vacuum() -> None:
    spectrum = EXACT["component_spectrum_and_vacuum"]
    ewsb = spectrum["EWSB_and_Higgs"]
    branches = spectrum["exact_reduced_F_flat_branches"]
    stops = spectrum["stop_consistency"]

    assert ewsb["origin_instability_determinant_GeV4"] < 0.0
    assert ewsb["D_flat_boundedness_margin_GeV2"] > 0.0
    assert ewsb["tree_Higgs_subspace_local_minimum"] is True
    assert ewsb["traditional_stop_CCB_inequality_passes"] is True
    assert ewsb["full_loop_pole_or_tunneling_certificate"] is False
    assert branches["both_global_SUSY_energies"] == 0.0
    assert math.isclose(branches["positive_coupling_saddle_s2_over_v2"], 1.0 / 3.0)
    assert math.isclose(branches["positive_coupling_saddle_x2_over_v2"], 1.0 / 3.0)
    assert branches["universal_positive_soft_masses_select_PS_branch"] is False
    assert stops["declared_At_compatible_with_inserted_pair"] is False
    assert spectrum["full_G2_G3_G4_closed"] is False


def test_live_and_formal_two_loop_rge_output_scope_is_explicit() -> None:
    running = EXACT["gauge_running_and_RGEs"]
    live = running["live_SARAH_declared_Z33_source"]
    soft = running["formal_soft_mirror"]

    assert live["model"] == "PSZ4RZ33SUSYV33"
    assert live["two_loop_RGE_calculation_succeeded"] is True
    assert live["beta_counts"] == {
        "gauge": 3,
        "trilinear_superpotential": 16,
        "bilinear_superpotential": 1,
        "linear_superpotential": 1,
        "soft_trilinear": 0,
        "soft_bilinear": 0,
        "soft_linear": 0,
        "soft_scalar_mass": 0,
        "gaugino_mass": 0,
    }
    assert sum(live["beta_counts"].values()) == 21
    assert REPORT["summary"]["raw_SARAH_two_loop_source_beta_group_count"] == 21
    assert live["raw_symbolic_output_captured"] is True
    assert live["dummy_index_contractions_validated"] is False
    assert live["reference_coefficient_validation_complete"] is False
    assert live["coupled_gauge_yukawa_soft_solution_present"] is False
    assert live["group_contractions_independently_reference_validated"] is False
    assert live["coupled_gauge_Yukawa_soft_system_integrated"] is False
    assert soft["continuous_Lagrangian_identical_to_Z33_source"] is True
    assert soft["two_loop_RGE_calculation_succeeded"] is True
    assert soft["beta_counts"]["soft_trilinear"] == 16
    assert soft["beta_counts"]["soft_bilinear"] == 1
    assert soft["beta_counts"]["soft_linear"] == 1
    assert soft["beta_counts"]["soft_scalar_mass"] == 18
    assert soft["beta_counts"]["gaugino_mass"] == 3
    assert soft["raw_soft_expression_hash_captured"] is True
    assert soft["full_soft_expression_payload_stored"] is False
    assert soft["coupled_gauge_Yukawa_soft_system_integrated"] is False
    assert soft["mediation_boundary_present"] is False


def test_two_loop_root_reverses_the_ordered_one_loop_ps_interval() -> None:
    running = EXACT["gauge_running_and_RGEs"]
    corrections = running["known_low_scale_corrections"]
    one_loop = running["corrected_one_loop_root"]
    two_loop = running["gauge_only_two_loop_root"]
    branches = running["axion_normalization_running_branches"]

    assert len(corrections["pole_threshold_sector_decomposition"]) == 7
    assert [
        row["sector"] for row in corrections["pole_threshold_sector_decomposition"]
    ] == [
        "wino",
        "gluino",
        "higgsinos",
        "heavy_Higgs_doublet",
        "first_second_generation_squarks",
        "third_generation_squarks",
        "all_sleptons",
    ]
    assert corrections["summed_Delta_b_equals_MSSM_minus_SM"] is True
    for value, expected in zip(
        corrections["pole_Delta_alpha_inverse"],
        [-0.0126812678675009, -0.168724108893521, 0.431105847553621],
    ):
        assert math.isclose(value, expected, rel_tol=0.0, abs_tol=2.0e-15)
    for value, expected in zip(
        corrections["corrected_alpha_inverse_MSUSY"],
        [56.9938475115719, 30.92029418286656, 12.273567491236912],
    ):
        assert math.isclose(value, expected, rel_tol=0.0, abs_tol=2.0e-13)
    assert one_loop["MPS_GeV"] < one_loop["MG_GeV"]
    assert one_loop["log_MG_over_MPS"] > 0.0
    assert max(one_loop["alpha_inverse_MG"]) - min(one_loop["alpha_inverse_MG"]) < 1.0e-12
    assert two_loop["iterations"] == 4
    assert two_loop["MG_GeV"] < two_loop["MPS_GeV"]
    assert two_loop["log_MG_over_MPS"] < 0.0
    assert max(abs(residual) for residual in two_loop["residuals"]) < 1.0e-10
    assert two_loop["physically_ordered_PS_interval"] is False
    assert math.isclose(one_loop["MPS_GeV"], 1.00807324966591e16, rel_tol=2.0e-12)
    assert math.isclose(one_loop["MG_GeV"], 1.05100911610111e16, rel_tol=2.0e-12)
    assert math.isclose(one_loop["alpha_G"], 0.0501952993750077, rel_tol=2.0e-12)
    assert math.isclose(two_loop["MPS_GeV"], 2.32240214812631e16, rel_tol=2.0e-10)
    assert math.isclose(two_loop["MG_GeV"], 5.70181169864905e15, rel_tol=2.0e-10)
    assert math.isclose(two_loop["alpha_G"], 0.05169447134895, rel_tol=2.0e-10)
    boundary = two_loop["boundary_repair"]
    assert math.isclose(
        boundary["common_boundary_GeV"], 1.17686674307818e16, rel_tol=2.0e-10
    )
    assert math.isclose(
        boundary["linearized_maximum_fractional_g_shift"],
        0.00676798840109,
        rel_tol=2.0e-9,
    )
    assert math.isclose(
        boundary["exact_maximum_fractional_g_shift"],
        0.00670004586216,
        rel_tol=2.0e-9,
    )
    assert boundary["derived_from_source"] is False
    alternative = branches["preserve_V31_claimed_physical_fa"]
    assert alternative["vectorlike_threshold_GeV"] == 2.0e12
    assert math.isclose(
        alternative["corrected_one_loop_root"]["alpha_G"],
        0.0480660005447262,
        rel_tol=2.0e-12,
    )
    assert math.isclose(
        alternative["gauge_only_two_loop_root"]["MPS_GeV"],
        2.22496471844272e16,
        rel_tol=2.0e-10,
    )
    assert math.isclose(
        alternative["gauge_only_two_loop_root"]["MG_GeV"],
        5.65343328667476e15,
        rel_tol=2.0e-10,
    )
    assert math.isclose(
        alternative["gauge_only_two_loop_root"]["alpha_G"],
        0.04930121319991,
        rel_tol=2.0e-10,
    )
    assert running["precision_unification_closed"] is False


def test_g5_g7_g8_conditionals_are_replayed_and_not_promoted() -> None:
    physics = EXACT["cosmology_flavour_and_proton"]
    quality = physics["Z11_to_Z33_quality_and_wall_tradeoff"]
    pq = physics["conditional_radiative_PQ_breaking"]
    proton = physics["source_baryon_operators"]
    neutrino = physics["conditional_neutrino_derived_observables"]

    assert physics["PQ_anomaly"]["source_local_NDW"] == 4
    assert physics["PQ_anomaly"]["GS_mixed_physical_NDW_derived"] is False
    assert quality["conditional_quality_assumptions"]["PQ_soft_A_N_GeV"] == 1.0e4
    assert math.isclose(
        quality["preinflation_branches"][0]["preinflation_misalignment_angle_rad"],
        1.775878895487986,
        rel_tol=2.0e-13,
    )
    assert math.isclose(
        quality["preinflation_branches"][1]["preinflation_misalignment_angle_rad"],
        0.9115525393746486,
        rel_tol=2.0e-13,
    )
    assert pq["source_soft_boundary_present"] is False
    assert math.isclose(pq["equal_two_active_couplings_minimum"], math.sqrt(2.425 / 16.0))
    assert proton["renormalizable_PS_vector_mediated_proton_decay_present"] is False
    assert proton["complete_independent_flavour_operator_basis_derived"] is False
    assert math.isclose(
        proton["illustrative_wino_dressed_C6_GeV_inverse2"],
        1.27206179815628e-38,
        rel_tol=2.0e-14,
    )
    assert 2.0e47 < proton["illustrative_lifetime_years"] < 2.2e47
    assert proton["lifetime_is_prediction"] is False
    assert math.isclose(neutrino["m_beta_eV"], 0.0102077583595, rel_tol=2.0e-11)
    assert neutrino["derived_from_fitted_oscillation_inputs"] is True
    assert neutrino["out_of_sample_prediction"] is False


def test_all_frontiers_advance_but_the_strict_full_gate_verdict_is_zero_of_eight() -> None:
    rows = GATES["gates"]
    active = NEW_PHYSICS["active_EFT_repair"]

    assert [row["gate"] for row in rows] == [f"G{index}" for index in range(1, 9)]
    assert all(row["new_exact_or_reproducible_derivations"] for row in rows)
    assert all(row["remaining_promotion_requirement"] for row in rows)
    assert all(row["established_full_predictive_closed"] is False for row in rows)
    assert GATES["gate_frontiers_advanced_count"] == 8
    assert GATES["established_full_predictive_closed_count"] == 0
    assert GATES["complete_theory_exists"] is False
    assert REPORT["summary"]["gate_frontiers_advanced_count"] == 8
    assert REPORT["summary"]["established_full_predictive_closed_count"] == 0
    assert REPORT["summary"]["complete_theory_exists"] is False
    assert active["checks"]["renormalizable_terms"] == 18
    assert active["checks"]["leading_P_power"] == 33
    assert active["full_discrete_UV_completion"] is False
    assert NEW_PHYSICS["safe_to_claim_new_fundamental_law"] is False


def test_frozen_outputs_and_cli_check() -> None:
    assert all(row["exists"] for row in REPORT["source_manifest"])
    assert all(len(row["sha256"]) == 64 for row in REPORT["source_manifest"])
    assert v33.canonical_sha(REPORT) == REPORT["core_sha256"]
    assert v33.check_outputs(REPORT, EVIDENCE) is True
    completed = subprocess.run(
        [sys.executable, "-B", str(v33.ROOT / "susy_v33_derivation_campaign.py"), "--check"],
        cwd=v33.ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    assert completed.returncode == 0, completed.stdout + completed.stderr
    assert v33.STATUS in completed.stdout
