#!/usr/bin/env python3
"""Focused, artifact-aware tests for the first full-coordinate G3 stage."""
from __future__ import annotations

import json
import os
import unittest
from pathlib import Path

import numpy as np

import g3_full_stationarity_feasibility_v20 as mod


class G3FullStationarityFeasibilityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.artifact_path = Path(mod.OUT_JSON)
        cls.report = (
            json.loads(cls.artifact_path.read_text(encoding="utf-8"))
            if cls.artifact_path.exists()
            else None
        )

    def test_authoritative_metadata_partition(self):
        directions = mod.direction_metadata()
        self.assertEqual(len(directions), 64)
        self.assertEqual(
            sum(1 if row.self_conjugate else 2 for row in directions), 91
        )
        self.assertEqual(len(mod.g2.covered_families()), 18)

    def test_tiny_electroweak_tangents_survive_and_rank_increments_by_three(self):
        audit = mod.gauge_orbit_audit()
        self.assertEqual(
            audit["pre_EW_SO10_to_SM"]["column_normalized_rank"], 33
        )
        physical = audit["physical_EW_SO10_to_U1em"]
        self.assertEqual(physical["pre_EW_unbroken_generator_dimension"], 12)
        self.assertEqual(physical["EW_increment_rank_after_preEW_projection"], 3)
        self.assertEqual(physical["stage_resolved_total_rank"], 36)
        self.assertGreater(physical["increment_largest_column_norm"], 0.0)

    def test_generated_stationarity_artifact_when_present(self):
        if self.report is None:
            self.skipTest("G3 artifact is generated by the focused workflow")
        self.assertEqual(self.report["n_failed"], 0, self.report["failures"] )
        self.assertEqual(self.report["overall_state"], "PARTIAL")
        self.assertTrue(self.report["checks"]["G1_closed"] )
        self.assertTrue(self.report["checks"]["G2_18_family_partition_present"] )
        stationarity = self.report["stationarity"]
        self.assertEqual(stationarity["matrix_shape"], [486, 91])
        self.assertLess(stationarity["stationary_witness_relative_residual"], 1.0e-10)
        self.assertTrue(stationarity["stationary_witness_all_coefficients_within_4pi"] )
        self.assertEqual(
            self.report["gauge_orbits"]["physical_EW_SO10_to_U1em"][
                "stage_resolved_total_rank"
            ],
            36,
        )
        self.assertFalse(self.report["flags"]["G3_closed"] )
        self.assertFalse(self.report["flags"]["whole_model_validated"] )

    def test_full_crosscheck_when_ci_requires_it(self):
        if os.environ.get("G3_REQUIRE_FULL_CROSSCHECK") != "1":
            self.skipTest("full dense crosscheck is required only in focused CI")
        self.assertIsNotNone(self.report)
        crosscheck = self.report["fast_gradient_crosscheck"]
        self.assertTrue(crosscheck["executed"] )
        self.assertGreater(crosscheck["direction_count"], 0)
        self.assertTrue(crosscheck["all_gradients_within_mixed_tolerance"])
        self.assertLess(crosscheck["maximum_gradient_tolerance_ratio"], 1.0)
        # The raw relative ratio is intentionally retained as a diagnostic for
        # gradients whose exact norm is below the mixed absolute tolerance.
        self.assertGreaterEqual(crosscheck["maximum_gradient_raw_relative_residual"], 0.0)
        self.assertTrue(self.report["flags"]["full_fast_gradient_crosscheck_executed"] )
        self.assertTrue(self.report["flags"]["fast_gradients_match_exact_G2_adapters"] )


if __name__ == "__main__":
    unittest.main()
