(* ::Package:: *)

(* ::Text:: *)
(*This file was automatically generated by PyR@TE 3.*)
(*Model : SO10Z17AxionV20_quartic_live*)
(*Author : so10-axion-v20*)
(**)
(*Section 1 contains the renormalization group equations.*)
(*Section 2 is a proposition of a minimal working code to solve the RGEs and plot the running couplings.*)
(*Section 3 should be completed by the user since it contains the initial conditions for the running couplings.*)
(* ::Subsection:: *)
(*1. RGEs*)

(* \[Beta]-function definition *)

\[Beta][x_] := 1*Sum[If[With[{j=i}, ValueQ[\[Beta][x, j]]] && (!ValueQ[loops[x]] || i <= loops[x]),  1/(4 Pi)^(2*i)*\[Beta][x,i], 0], {i,1}]*Log[10];


(* Gauge Couplings *)

GaugeCouplings = {g10};

\[Beta][g10, 1] = -4*g10^3;


(* Quartic Couplings *)

QuarticCouplings = {lam10, lam126, lamS, lam210, lam10S, lam126S, lam210S, lam10126};

\[Beta][lam10, 1] = (27/2)*g10^4 - 54*g10^2*lam10 + 56*lam10^2 + lam10S^2 + 126*lam10126^2;
\[Beta][lam126, 1] = (135/2)*g10^4 - 150*g10^2*lam126 + 10*lam10126^2 + 520*lam126^2 + lam126S^2;
\[Beta][lamS, 1] = 10*lam10S^2 + 126*lam126S^2 + 420*lam210S^2 + 20*lamS^2;
\[Beta][lam210, 1] = 12*g10^4 - 144*g10^2*lam210 + 1744*lam210^2 + lam210S^2;
\[Beta][lam10S, 1] = -27*g10^2*lam10S + 44*lam10*lam10S + 4*lam10S^2 + 8*lam10S*lamS + 252*lam10126*lam126S;
\[Beta][lam126S, 1] = -75*g10^2*lam126S + 20*lam10S*lam10126 + 508*lam126*lam126S + 4*lam126S^2 + 8*lam126S*lamS;
\[Beta][lam210S, 1] = -72*g10^2*lam210S + 1696*lam210*lam210S + 8*lam210S^2 + 8*lam210S*lamS;
\[Beta][lam10126, 1] = 15*g10^4 - 102*g10^2*lam10126 + 44*lam10*lam10126 + 2*lam10S*lam126S + 4*lam10126^2 + 508*lam10126*lam126;


(* Trilinear Couplings *)

TrilinearCouplings = {kappa};

\[Beta][kappa, 1] = -27*g10^2*kappa + 4*kappa*lam10 + 4*kappa*lam10S;


(* Scalar Mass Couplings *)

ScalarMassCouplings = {m2102, m102, m1262, mS2};

\[Beta][m2102, 1] = -72*g10^2*m2102 + 1696*lam210*m2102 + 2*lam210S*mS2;
\[Beta][m102, 1] = -27*g10^2*m102 + 8*kappa*Conjugate[kappa] + 44*lam10*m102 + 2*lam10S*mS2 + 252*lam10126*m1262;
\[Beta][m1262, 1] = -75*g10^2*m1262 + 20*lam10126*m102 + 508*lam126*m1262 + 2*lam126S*mS2;
\[Beta][mS2, 1] = 40*kappa*Conjugate[kappa] + 20*lam10S*m102 + 252*lam126S*m1262 + 840*lam210S*m2102 + 8*lamS*mS2;
(* ::Subsection:: *)
(*2. Solving and plotting functions*)

(* ::Subsubsection::Closed:: *)
(*RG-solving functions*)

(* Solving function *)

RGsolve[initialScale_, range_] := Block[{allCouplings, couplingsToFunction, differentialEquations, initialConditions, allEquations, solutions, yukawaLike},
	(* Define and solve the system of coupled differential equations *)
	allCouplings = Join[GaugeCouplings, QuarticCouplings, TrilinearCouplings, ScalarMassCouplings];
	couplingsToFunction = # -> #[t] & /@ allCouplings;

	differentialEquations = (#'[t] == (\[Beta][#] /. couplingsToFunction) & /@ allCouplings);
	initialConditions = (#[initialScale] == init[#] & /@ allCouplings);
	allEquations = Join[differentialEquations, initialConditions];

	solutions = NDSolve[allEquations, allCouplings /. couplingsToFunction, {t, range[[1]], range[[2]]}][[1]];
	Return[solutions];
];

(* The following function removes from the list the couplings which seem to identically vanish over the energy range *)
DiscardZeroCouplings[range_, solutions_] := Block[{N, testPoints},
	N = 20;
	testPoints =  Range[range[[1]], range[[2]], (range[[2]] - range[[1]])/N];
	Return @ Select[solutions, (DeleteDuplicates[#[[2, 0]] /@ testPoints] != {0}) &];
];
(* ::Subsubsection::Closed:: *)
(*Plot function*)

(* Plotting function handling both real and complex quantities *)

Complexplot[funcs_, {min_, max_}, legends_, plotRange_] := Block[{cplxPos, newFuncs, newLegends},
	cplxPos = If[Head[Chop[funcs[[#]] /. t -> 1/2(max-min)]] === Complex,#, Nothing]& /@ Range[Length[funcs]];
	newFuncs = If[MemberQ[cplxPos, #], Sequence @@ {Re@funcs[[#]], Im@funcs[[#]]}, funcs[[#]]]& /@ Range[Length[funcs]];
	newLegends = If[MemberQ[cplxPos, #], Sequence @@ {Re@legends[[#]], Im@legends[[#]]}, legends[[#]]]& /@ Range[Length[funcs]];

	Return @ Plot[Evaluate @ newFuncs, {t, min, max}, PlotLegends->newLegends, PlotRange->plotRange]
 ]


RGplot[range_, solutions_] := Block[{selectType, toPlot},
	selectType[type_] := Select[solutions, MemberQ[type, If[Head@#[[1]] =!= Symbol, Head@#[[1]], #[[1]]]]&];

	toPlot = selectType[GaugeCouplings];
	If[toPlot =!= {},
		Print["### Gauge Couplings ###"];
		Print @ Complexplot[toPlot[[All, 2]], range, toPlot[[All, 1]], All];
	];

	toPlot = selectType[QuarticCouplings];
	If[toPlot =!= {},
		Print["### Quartic Couplings ###"];
		Print @ Complexplot[toPlot[[All, 2]], range, toPlot[[All, 1]], All];
	];

	toPlot = selectType[TrilinearCouplings];
	If[toPlot =!= {},
		Print["### Trilinear Couplings ###"];
		Print @ Complexplot[toPlot[[All, 2]], range, toPlot[[All, 1]], All];
	];

	toPlot = selectType[ScalarMassCouplings];
	If[toPlot =!= {},
		Print["### Scalar Mass Couplings ###"];
		Print @ Complexplot[toPlot[[All, 2]], range, toPlot[[All, 1]], All];
	];
];
(* ::Subsection:: *)
(*3. Actual solving*)


(* Some useful quantities. Energy and mass are in units of Log10[ GeV ] *)

MZ = 91.1876                 // Log10; (* Z boson mass *)
MP = 1.22*10^19              // Log10; (* Planck mass *)
Mp = 1.22*10^19 / Sqrt[8 Pi] // Log10; (* Reduced Planck mass *)

MT = 173.0 // Log10; (* Pole top mass *)

vev = 246.22 // Log10; (* SM Higgs vacuum-expectation value *)


(*** Initial conditions ; Energy range ***)

initialScale = MZ;
range = {0, MP};

(* Gauge Couplings *)

init[g10] = 0;

(* Quartic Couplings *)

init[lam10] = 0;
init[lam126] = 0;
init[lamS] = 0;
init[lam210] = 0;
init[lam10S] = 0;
init[lam126S] = 0;
init[lam210S] = 0;
init[lam10126] = 0;

(* Trilinear Couplings *)

init[kappa] = 0;

(* Scalar Mass Couplings *)

init[m2102] = 0;
init[m102] = 0;
init[m1262] = 0;
init[mS2] = 0;


(* Definition of the running scheme *)

(loops[#] = 1)& /@ GaugeCouplings;
(loops[#] = 1)& /@ QuarticCouplings;
(loops[#] = 1)& /@ TrilinearCouplings;
(loops[#] = 1)& /@ ScalarMassCouplings;


(* Now call the functions defined in section 2 *)

solutions = RGsolve[initialScale, range];
solutions = DiscardZeroCouplings[range, solutions];

RGplot[range, solutions]