(* ==================================================================== *)
(* Native non-supersymmetric SARAH 4 input: SO(10) x U(1)_X, residual  *)
(* Z_17, and the complete anomaly-cancelling v20 matter catalogue.      *)
(*                                                                      *)
(* This file establishes the gauge, matter, charge, kinetic, and        *)
(* representative renormalizable-interaction contract.  The independent *)
(* Clebsch contractions of the full 210/126bar/10 scalar potential are  *)
(* evaluated by the repository tensor backend; a single SARAH Dot       *)
(* contraction must not be interpreted as that multi-invariant basis.   *)
(* ==================================================================== *)

Model`Name = "SO10Z17AxionV20";
Model`NameLaTeX = "SO(10) x U(1)_X axion candidate v20";
Model`Authors = "SO10 axion v20 collaboration";
Model`Date = "2026-08-07";

NameOfStates = {GaugeES};

(* Gauge groups.  The fifth entry follows SARAH's adjoint-index-expansion
   convention; neither factor needs explicit adjoint components here. *)
Gauge[[1]] = {G10, SO[10], SOGUT, g10, False};
Gauge[[2]] = {GX, U[1], X, gX, False};

(* The gauged field Phi17 leaves this exact residual subgroup after its VEV. *)
Global[[1]] = {Z[17], Z17};

(* Native order: {multiplet, generations, components, SO(10), X, Z17}. *)
ScalarFields[[1]] = {Phi210,       1, phi210,      210,    0,  0};
ScalarFields[[2]] = {Delta126bar,  1, delta126bar, -126,  -2, 15};
ScalarFields[[3]] = {H10,          1, h10,           10,  -2, 15};
ScalarFields[[4]] = {S,            1, singletS,        1,   4,  4};
ScalarFields[[5]] = {Phi17,        1, phi17,           1,  17,  0};

(* The 210 is a real SO(10) representation. *)
RealScalars = {phi210};

(* Three light F families, P and R, five s/b spectator pairs, and Q sector. *)
FermionFields[[1]] = {F,      3, f16,      16,   1,  1};
FermionFields[[2]] = {P,      1, p16,      16,   1,  1};
FermionFields[[3]] = {R,      1, r16,      16,   1,  1};
FermionFields[[4]] = {SpecS,  5, s16,      16,   2,  2};
FermionFields[[5]] = {SpecB,  5, b16bar,  -16,  -6, 11};
FermionFields[[6]] = {Q,      1, q16,      16,  14, 14};
FermionFields[[7]] = {Pbar,   1, pbar16,  -16,  16, 16};
FermionFields[[8]] = {Qbar,   1, qbar16,  -16,   3,  3};
FermionFields[[9]] = {Rbar,   1, rbar16,  -16, -18, 16};

DEFINITION[GaugeES][LagrangianInput] = {
  {LagHC,   {AddHC -> True}},
  {LagNoHC, {AddHC -> False}}
};

(* Charge-neutral Yukawa, vectorlike-mass, mixing, and scalar interactions. *)
LagHC = -(
    Y10 F.F.H10
  + Y126 F.F.Delta126bar
  + yP conj[Phi17].P.Pbar
  + yQ conj[Phi17].Q.Qbar
  + yR Phi17.R.Rbar
  + ys S.SpecS.SpecB
  + lambdaP P.F.H10
  + lambdaR R.F.H10
  + lambdaQB conj[S].Qbar.F
  + lambdaQR S.Q.Rbar
  + kappaH H10.H10.S
);

(* Hermitian mass and singlet-quartic sector.  Covariant kinetic terms are
   generated by SARAH from the native gauge and matter declarations above. *)
LagNoHC = -(
    m210Sq/2 Phi210.Phi210
  + m126Sq conj[Delta126bar].Delta126bar
  + m10Sq conj[H10].H10
  + mSSq conj[S].S
  + m17Sq conj[Phi17].Phi17
  + lambdaS/2 conj[S].S.conj[S].S
  + lambda17/2 conj[Phi17].Phi17.conj[Phi17].Phi17
  + lambdaS17 conj[S].S.conj[Phi17].Phi17
);
