(* ::Package:: *)

(* ::Text:: *)
(*This file was automatically generated by PyR@TE 3.*)
(*Model : SO10Z17AxionV20_live*)
(*Author : so10-axion-v20*)
(**)
(*Section 1 contains the renormalization group equations.*)
(*Section 2 is a proposition of a minimal working code to solve the RGEs and plot the running couplings.*)
(*Section 3 should be completed by the user since it contains the initial conditions for the running couplings.*)
(* ::Subsection:: *)
(*1. RGEs*)

(* \[Beta]-function definition *)

\[Beta][x_] := 1*Sum[If[With[{j=i}, ValueQ[\[Beta][x, j]]] && (!ValueQ[loops[x]] || i <= loops[x]),  1/(4 Pi)^(2*i)*\[Beta][x,i], 0], {i,1}]*Log[10];


(* Gauge Couplings *)

GaugeCouplings = {g10};

\[Beta][g10, 1] = -4*g10^3;
(* ::Subsection:: *)
(*2. Solving and plotting functions*)

(* ::Subsubsection::Closed:: *)
(*RG-solving functions*)

(* Solving function *)

RGsolve[initialScale_, range_] := Block[{allCouplings, couplingsToFunction, differentialEquations, initialConditions, allEquations, solutions, yukawaLike},
	(* Define and solve the system of coupled differential equations *)
	allCouplings = Join[GaugeCouplings];
	couplingsToFunction = # -> #[t] & /@ allCouplings;

	differentialEquations = (#'[t] == (\[Beta][#] /. couplingsToFunction) & /@ allCouplings);
	initialConditions = (#[initialScale] == init[#] & /@ allCouplings);
	allEquations = Join[differentialEquations, initialConditions];

	solutions = NDSolve[allEquations, allCouplings /. couplingsToFunction, {t, range[[1]], range[[2]]}][[1]];
	Return[solutions];
];

(* The following function removes from the list the couplings which seem to identically vanish over the energy range *)
DiscardZeroCouplings[range_, solutions_] := Block[{N, testPoints},
	N = 20;
	testPoints =  Range[range[[1]], range[[2]], (range[[2]] - range[[1]])/N];
	Return @ Select[solutions, (DeleteDuplicates[#[[2, 0]] /@ testPoints] != {0}) &];
];
(* ::Subsubsection::Closed:: *)
(*Plot function*)

(* Plotting function handling both real and complex quantities *)

Complexplot[funcs_, {min_, max_}, legends_, plotRange_] := Block[{cplxPos, newFuncs, newLegends},
	cplxPos = If[Head[Chop[funcs[[#]] /. t -> 1/2(max-min)]] === Complex,#, Nothing]& /@ Range[Length[funcs]];
	newFuncs = If[MemberQ[cplxPos, #], Sequence @@ {Re@funcs[[#]], Im@funcs[[#]]}, funcs[[#]]]& /@ Range[Length[funcs]];
	newLegends = If[MemberQ[cplxPos, #], Sequence @@ {Re@legends[[#]], Im@legends[[#]]}, legends[[#]]]& /@ Range[Length[funcs]];

	Return @ Plot[Evaluate @ newFuncs, {t, min, max}, PlotLegends->newLegends, PlotRange->plotRange]
 ]


RGplot[range_, solutions_] := Block[{selectType, toPlot},
	selectType[type_] := Select[solutions, MemberQ[type, If[Head@#[[1]] =!= Symbol, Head@#[[1]], #[[1]]]]&];

	toPlot = selectType[GaugeCouplings];
	If[toPlot =!= {},
		Print["### Gauge Couplings ###"];
		Print @ Complexplot[toPlot[[All, 2]], range, toPlot[[All, 1]], All];
	];
];
(* ::Subsection:: *)
(*3. Actual solving*)


(* Some useful quantities. Energy and mass are in units of Log10[ GeV ] *)

MZ = 91.1876                 // Log10; (* Z boson mass *)
MP = 1.22*10^19              // Log10; (* Planck mass *)
Mp = 1.22*10^19 / Sqrt[8 Pi] // Log10; (* Reduced Planck mass *)

MT = 173.0 // Log10; (* Pole top mass *)

vev = 246.22 // Log10; (* SM Higgs vacuum-expectation value *)


(*** Initial conditions ; Energy range ***)

initialScale = MZ;
range = {0, MP};

(* Gauge Couplings *)

init[g10] = 0;


(* Definition of the running scheme *)

(loops[#] = 1)& /@ GaugeCouplings;


(* Now call the functions defined in section 2 *)

solutions = RGsolve[initialScale, range];
solutions = DiscardZeroCouplings[range, solutions];

RGplot[range, solutions]